CREATE OR REPLACE PACKAGE MM_PJM_EFTR AS

  -- PJM eMTR Interface Package
  -- $Revision: 1.45 $
  
  TYPE REF_CURSOR IS REF CURSOR;

  FUNCTION WHAT_VERSION RETURN VARCHAR;

PROCEDURE MARKET_EXCHANGE
	(
	p_BEGIN_DATE            	IN DATE,
	p_END_DATE              	IN DATE,
	p_EXCHANGE_TYPE  			IN VARCHAR2,
	p_LOG_ONLY					IN NUMBER :=0,
	p_LOG_TYPE 					IN NUMBER,
	p_TRACE_ON 					IN NUMBER,
	p_STATUS                	OUT NUMBER,
	p_MESSAGE               	OUT VARCHAR2
	);

PROCEDURE MARKET_SUBMIT
	(
	p_BEGIN_DATE                IN DATE,
	p_END_DATE 			        IN DATE,
	p_EXCHANGE_TYPE 		    IN VARCHAR2,
	p_ENTITY_LIST               IN VARCHAR2,
	p_ENTITY_LIST_DELIMITER 	IN CHAR,
	p_STATEMENT_TYPE_ID 	    IN NUMBER,
	p_SUBMIT_HOURS   		    IN VARCHAR2,
	p_TIME_ZONE       	        IN VARCHAR2,
	p_LOG_ONLY			        IN NUMBER :=0,
	p_LOG_TYPE			        IN NUMBER,
	p_TRACE_ON		            IN NUMBER,
	p_STATUS                    OUT NUMBER,
	p_MESSAGE         	        OUT VARCHAR2
	);

PROCEDURE  MARKET_SUBMIT_TRANSACTION_LIST
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_EXCHANGE_TYPE IN VARCHAR2,
	p_STATUS OUT NUMBER,
	p_CURSOR IN OUT REF_CURSOR
	);

FUNCTION GET_FTR_TRANSACTION_ID
	(
	p_AUCTION_DATE               IN DATE,
	p_NEW_TRANSACTION_END_DATE IN DATE,
	p_TRANSACTION_TYPE         IN VARCHAR2,
	p_CONTRACT_ID            	 IN NUMBER,
	p_FLOWGATE_NAME            IN VARCHAR2,
	p_SOURCE_NAME              IN VARCHAR2,
	p_SINK_NAME                IN VARCHAR2,
	p_COMMODITY_TYPE           IN VARCHAR2,
	p_AGREEMENT_TYPE           IN VARCHAR2,
	p_PEAK_CLASS 				 IN VARCHAR2,
	p_TRANSACTION_ROWNUM       IN VARCHAR2,
	p_CREATE_IF_NOT_FOUND      IN BOOLEAN,
	p_ERROR_MESSAGE            OUT VARCHAR2,
	p_CLEARED_MW 				 IN NUMBER := 0,
	p_AUCTION_TYPE 				 IN VARCHAR2 := NULL,
	p_TRANSACTION_DESC 			 IN VARCHAR2 := NULL
	) RETURN NUMBER;

FUNCTION ID_FOR_SERVICE_POINT_NAME
	(
	p_SERVICE_POINT_NAME IN VARCHAR2
	) RETURN NUMBER;

PROCEDURE SYSTEM_ACTION_USES_HOURS
	(
	p_ACTION IN VARCHAR2,
	p_SHOW_HOURS OUT NUMBER
	);

g_SECOND CONSTANT NUMBER(6, 5) := 1 / 86400;

-- Exchange Types 
-- used as of v3.5.1.3 (23-mar-2009)
g_ET_QUERY_MARKET_INFO VARCHAR2(50) := 'Query Market Info';
g_ET_QUERY_FTR_AUCTION_RESULTS VARCHAR2(50) := 'Query FTR Auction Results';
g_ET_QUERY_FTR_POSITION VARCHAR2(50) := 'Query FTR Position';
g_ET_SUBMIT_FTR_QUOTES VARCHAR2(50) := 'Submit FTR Quotes';
-- not referenced in action list as of v3.5.1.3 (23-mar-2009)
g_ET_IMPORT_FTR_AUCTION_RES VARCHAR2(50) := 'Import FTR Auction Results';

-- apparently not used in v3.5.1.3+ (as of 23-mar-2009)
g_ET_QUERY_FTR_QUOTES VARCHAR2(50) := 'Query FTR Quotes';
g_ET_QUERY_FTR_QUOTES_TO_INT VARCHAR2(50) := 'Query FTR Quotes To Internal';
g_ET_QUERY_FTR_NODES VARCHAR2(50) := 'Query FTR Nodes';
g_ET_QUERY_MESSAGES VARCHAR2(50) := 'Query Messages';
g_ET_QUERY_INITIAL_ARR VARCHAR2(50) := 'Query Initial ARR';
g_ET_QUERY_INITIAL_ARR_TO_INT VARCHAR2(50) := 'Query Initial ARR To Internal';
g_ET_QUERY_CLEARED_FTRS VARCHAR2(50) := 'Query Cleared FTRS';
g_ET_IMPORT_FTR_QUOTES VARCHAR2(50) := 'Import FTR Quotes';



END MM_PJM_EFTR;
/