CREATE OR REPLACE PACKAGE MM_PJM_EMKT_GEN IS
-- $Revision: 1.12 $

  -- Author  : AHUSSAIN
  -- Created : 11/10/2006 9:35:42 AM
  -- Purpose :

    g_PARAMETER_MAP MEX_PJM.PARAMETER_MAP;
    TYPE REF_CURSOR IS REF CURSOR;

FUNCTION WHAT_VERSION RETURN VARCHAR2;

PROCEDURE QUERY_UNIT_DETAIL
	(
	p_CRED			 IN mex_credentials,
	p_SCHEDULE_STATE IN NUMBER,
	p_REQUEST_DATE  IN DATE,
	p_LOG_ONLY      IN NUMBER,
	p_STATUS OUT NUMBER,
	p_ERROR_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
	);

PROCEDURE QUERY_UNIT_UPDATES
	(
	p_CRED			 IN mex_credentials,
	p_SCHEDULE_STATE IN NUMBER,
	p_REQUEST_DATE  IN DATE,
	P_LOG_ONLY IN NUMBER,
	p_STATUS OUT NUMBER,
	p_ERROR_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
	);

PROCEDURE QUERY_SCHEDULE_DETAIL
	(
	p_CRED			 IN mex_credentials,
	p_SCHEDULE_STATE IN NUMBER,
	p_REQUEST_DATE  IN DATE,
	p_LOG_ONLY      IN NUMBER,
	p_STATUS OUT NUMBER,
	p_ERROR_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
	);

PROCEDURE QUERY_SCHEDULE_OFFER
	(
	p_CRED			 IN mex_credentials,
	p_SCHEDULE_STATE IN NUMBER,
    p_REQUEST_DAY   IN DATE,
	p_LOG_ONLY      IN NUMBER,
    p_STATUS OUT NUMBER,
    p_ERROR_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
    );

PROCEDURE QUERY_SCHEDULE_SELECTION
	(
	p_CRED			 IN mex_credentials,
	p_SCHEDULE_STATE IN NUMBER,
	p_REQUEST_DATE IN DATE,
	p_LOG_ONLY      IN NUMBER,
	p_STATUS OUT NUMBER,
	p_ERROR_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
	);

PROCEDURE QUERY_REGULATION_OFFER
	(
	p_CRED			 IN mex_credentials,
	p_SCHEDULE_STATE IN NUMBER,
    p_REQUEST_DAY IN DATE,
	p_LOG_ONLY      IN NUMBER,
    p_STATUS OUT NUMBER,
    p_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
    );

PROCEDURE QUERY_SPIN_RESERVE_OFFER
	(
	p_CRED			 IN mex_credentials,
	p_SCHEDULE_STATE IN NUMBER,
    p_REQUEST_DAY IN DATE,
	p_LOG_ONLY      IN NUMBER,
    p_STATUS OUT NUMBER,
    p_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
    );

PROCEDURE QUERY_SPREG_AWARD
	(
	p_CRED			 IN mex_credentials,
	p_REQUEST_DATE IN DATE,
	p_LOG_ONLY      IN NUMBER,
	p_STATUS OUT NUMBER,
	p_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
	);

PROCEDURE QUERY_UNIT_SCHEDULES
	(
	p_CRED			 IN mex_credentials,
	p_LOG_ONLY      IN NUMBER,
	p_STATUS OUT NUMBER,
	p_ERROR_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
	);

PROCEDURE QUERY_REGULATION_UPDATE
	(
	p_CRED			 IN mex_credentials,
	p_SCHEDULE_STATE IN NUMBER,
    p_REQUEST_DAY IN DATE,
	p_LOG_ONLY      IN NUMBER,
    p_STATUS OUT NUMBER,
    p_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
    );

PROCEDURE QUERY_SPIN_RESERVE_UPDATE
	(
	p_CRED			 IN mex_credentials,
	p_SCHEDULE_STATE IN NUMBER,
    p_REQUEST_DAY IN DATE,
	p_LOG_ONLY      IN NUMBER,
    p_STATUS OUT NUMBER,
    p_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
    );

PROCEDURE QUERY_PARAMETER_LIMITS
	(
	p_CRED			 IN mex_credentials,
	p_SCHEDULE_STATE IN NUMBER,
	p_REQUEST_DATE  IN DATE,
	p_LOG_ONLY      IN NUMBER,
	p_STATUS OUT NUMBER,
	p_ERROR_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
	);

PROCEDURE IMPORT_BY_TRANSACTION_ID
	(
	p_XML IN XMLTYPE,
	p_ACCOUNT_NAME IN VARCHAR2,
	p_TRANSACTION_ID IN NUMBER,
	p_ACTION IN VARCHAR,
	p_STATUS OUT NUMBER,
	p_ERROR_MESSAGE OUT VARCHAR2
	);

PROCEDURE GET_SUBMIT_XML
	(
	p_EXCHANGE_TYPE IN VARCHAR2,
	p_TRANSACTION_ID IN NUMBER,
	p_SCHEDULE_DAY DATE,
	p_SUBMIT_HOURS IN VARCHAR2,
	p_TIME_ZONE IN VARCHAR2,
	p_XML OUT XMLTYPE,
	p_SUBMIT_MODE OUT NUMBER,
	p_STATUS OUT NUMBER,
	p_MESSAGE OUT VARCHAR2
	);

	--Exchange Types
	g_ET_SUBMIT_SCHED_OFFER CONSTANT VARCHAR2(64) := 'Submit Schedule Offer';
	g_ET_SUBMIT_SCHED_DETAIL CONSTANT VARCHAR2(64) := 'Submit Schedule Detail';
	g_ET_SUBMIT_SCHED_SELECTION CONSTANT VARCHAR2(64) := 'Submit Schedule Selection';
	g_ET_SUBMIT_UNIT_UPDATE CONSTANT VARCHAR2(64) := 'Submit Unit Update';
	g_ET_SUBMIT_UNIT_SCHEDULE CONSTANT VARCHAR2(64) := 'Submit Unit Schedule';
	g_ET_SUBMIT_UNIT_DETAIL CONSTANT VARCHAR2(64) := 'Submit Unit Detail';
	g_ET_SUBMIT_SPIN_OFFER CONSTANT VARCHAR2(64) := 'Submit Spinning Reserve Offer';
	g_ET_SUBMIT_SPIN_UPDATE CONSTANT VARCHAR2(64) := 'Submit Spinning Reserve Update';
	g_ET_SUBMIT_REG_OFFER CONSTANT VARCHAR2(64) := 'Submit Regulation Offer';
	g_ET_SUBMIT_REG_UPDATE CONSTANT VARCHAR2(64) := 'Submit Regulation Update';


END MM_PJM_EMKT_GEN;
/