CREATE OR REPLACE PACKAGE MM_PJM_UTIL IS

-- Author  : Josh Humphries
-- Created : 12/4/2004 5:43:02 PM
-- Purpose :
-- $Revision: 1.33 $

--This type can be used to track the status of submissions.
TYPE t_STATUS IS RECORD
(
SUCCEEDED PLS_INTEGER,
REJECTED PLS_INTEGER,
ERROR PLS_INTEGER
);

FUNCTION WHAT_VERSION RETURN VARCHAR2;

FUNCTION GET_CONTRACT_ID_FOR_ISO_ACCT
	(
	p_EXTERNAL_ACCOUNT_NAME IN VARCHAR2
	) RETURN INTERCHANGE_CONTRACT.CONTRACT_ID%TYPE;

FUNCTION HAS_ESUITE_ACCESS
	(
	p_ATTR_ID IN ENTITY_ATTRIBUTE.ATTRIBUTE_ID%TYPE,
	p_EXTERNAL_ACCOUNT_NAME IN VARCHAR2
	) RETURN BOOLEAN;

FUNCTION GET_TRANSACTION_ID
	(
	p_CONTRACT_NUMBER IN VARCHAR2,
	p_SERVICE_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_PSE
	(
	p_ORG_ID IN VARCHAR2,
	p_ORG_NAME IN VARCHAR2
	) RETURN NUMBER;

FUNCTION GET_PSE
	(
	p_ISO_ACCOUNT_NAME IN VARCHAR2
	) RETURN NUMBER;

FUNCTION GET_COMMODITY_ID
	(
	p_COMMODITY_NAME IN VARCHAR2
	) RETURN NUMBER;

FUNCTION CREATE_SERVICE_POINT
	(
	p_SERVICE_POINT_NAME IN VARCHAR2,
	p_EXTERNAL_IDENTIFIER IN VARCHAR2,
	p_NODE_TYPE IN VARCHAR2
	) RETURN NUMBER;

FUNCTION ID_FOR_SERVICE_POINT_NAME
	(
	p_SERVICE_POINT_NAME IN VARCHAR2
	) RETURN NUMBER;

FUNCTION ID_FOR_SERVICE_POINT_PNODE
	(
	p_PNODE_IDENT IN VARCHAR2
	) RETURN NUMBER;

FUNCTION GET_COMMIT_STATUS_RES_TRAIT RETURN NUMBER;
FUNCTION GET_ACTIVE_SCHEDULE_RES_TRAIT RETURN NUMBER;

PROCEDURE GET_SERVICE_POINT_OWNERSHIP
	(
	p_SERVICE_POINT_ID IN NUMBER,
	p_CONTRACT_ID IN NUMBER,
	p_DATE IN DATE,
	p_OWNERSHIP_PERCENT OUT NUMBER,
	p_IS_SCHEDULER OUT NUMBER
	);

FUNCTION GET_SERVICE_POINT_OWNERSHIP
	(
	p_TRANSACTION_ID IN NUMBER,
	p_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_STATUS_MESSAGE
	(
	p_REC IN t_STATUS,
	p_VERB_SUCCESS IN VARCHAR2 := 'processed',
	p_PLURAL_NOUN IN VARCHAR2 := 'schedules'
	) RETURN VARCHAR2;

PROCEDURE GET_CURRENT_TIME_ZONE
    (
    p_DATE IN DATE,
    p_TIME_ZONE OUT VARCHAR2
    );

PROCEDURE ADD_PRICE_TO_GEN_SCHED
    (
    p_SCHEDULE_DATE IN DATE,
    P_MARKET_TYPE IN VARCHAR2,
    p_EXTERNAL_ID IN VARCHAR2,
    p_PRICE IN NUMBER,
    p_STATUS OUT NUMBER,
    p_MESSAGE OUT VARCHAR2
    );    

--The following arrays hold the name or ID of the Statement Types that need to
--be filled in the IT_SCHEDULE table.
TYPE STATEMENT_TYPE_ARRAY IS VARRAY(10) OF STATEMENT_TYPE.STATEMENT_TYPE_NAME%TYPE;
TYPE STATEMENT_TYPE_ID_ARRAY IS VARRAY(10) OF STATEMENT_TYPE.STATEMENT_TYPE_ID%TYPE;
g_STATEMENT_TYPE_ARRAY STATEMENT_TYPE_ARRAY :=  STATEMENT_TYPE_ARRAY('Forecast','Preliminary','Final');
g_STATEMENT_TYPE_ID_ARRAY STATEMENT_TYPE_ID_ARRAY := STATEMENT_TYPE_ID_ARRAY();  --Initialized with package.

g_INTERNAL_STATE NUMBER(1) := 1;
g_EXTERNAL_STATE NUMBER(1) := 2;
g_PJM_TIME_ZONE  VARCHAR2(3) := LOCAL_TIME_ZONE;
--g_PJM_SC_ID SC.SC_ID%TYPE;

g_PJM_OP_RES_GO_LIVE DATE;

g_COMM_RT_ENERGY VARCHAR2(16) := 'RealTime Energy';
g_COMM_DA_ENERGY VARCHAR2(16) := 'DayAhead Energy';
g_COMM_REGULATION VARCHAR2(16) := 'Regulation';
g_COMM_SPIN_RES VARCHAR2(16) := 'Spinning Reserve';
g_COMM_VIRTUAL VARCHAR2(16) := 'Virtual Energy';
g_REALTIME VARCHAR2(16) := 'RealTime';
g_DAYAHEAD VARCHAR2(16) := 'DayAhead';

g_DST_SPRING_AHEAD_OPTION CONSTANT CHAR := 'B';

--Resource Traits
g_TG_SCH_MARKET CONSTANT NUMBER(9) := 501;
g_TG_SCH_USE_STARTUP_NO_LOAD CONSTANT NUMBER(9) := 502;
g_TG_SCH_PRIMARY_FUEL CONSTANT NUMBER(9) := 503;
g_TG_SCH_SECONDARY_FUEL CONSTANT NUMBER(9) := 504;
g_TG_SCH_ECON_MIN CONSTANT NUMBER(9) := 506;
g_TG_SCH_ECON_MAX CONSTANT NUMBER(9) := 507;
g_TG_SCH_EMER_MIN CONSTANT NUMBER(9) := 508;
g_TG_SCH_EMER_MAX CONSTANT NUMBER(9) := 509;
g_TG_SCH_MIN_RUNTIME CONSTANT NUMBER(9) := 510;
g_TG_SCH_MAX_RUNTIME CONSTANT NUMBER(9) := 511;
g_TG_SCH_MIN_DOWNTIME CONSTANT NUMBER(9) := 512;
g_TG_SCH_HOT_TO_COLD_TIME CONSTANT NUMBER(9) := 513;
g_TG_SCH_HOT_TO_INTER_TIME CONSTANT NUMBER(9) := 514;
g_TG_SCH_COLD_START_TIME CONSTANT NUMBER(9) := 515;
g_TG_SCH_INTER_START_TIME CONSTANT NUMBER(9) := 516;
g_TG_SCH_HOT_START_TIME CONSTANT NUMBER(9) := 517;
g_TG_SCH_COLD_NOTIF_TIME CONSTANT NUMBER(9) := 518;
g_TG_SCH_INTER_NOTIF_TIME CONSTANT NUMBER(9) := 519;
g_TG_SCH_HOT_NOTIF_TIME CONSTANT NUMBER(9) := 520;
g_TG_SCH_MAX_DAILY_STARTS CONSTANT NUMBER(9) := 521;
g_TG_SCH_MAX_WEEKLY_STARTS CONSTANT NUMBER(9) := 522;
g_TG_SCH_MAX_WEEKLY_ENERGY CONSTANT NUMBER(9) := 523;
g_TG_SCH_NO_LOAD_COST CONSTANT NUMBER(9) := 524;
g_TG_SCH_COLD_START_COST CONSTANT NUMBER(9) := 525;
g_TG_SCH_INTER_START_COST CONSTANT NUMBER(9) := 526;
g_TG_SCH_HOT_START_COST CONSTANT NUMBER(9) := 527;
--Regulation
g_TG_SCH_UNAVAILABLE CONSTANT NUMBER(9) := 582;
g_TG_SCH_SELF_SCHEDULED CONSTANT NUMBER(9) := 583;
--Spinning Reserve
g_TG_SCH_CONDENSE_AVAILABLE CONSTANT NUMBER(9) := 584;
g_TG_SCH_SPIN_AS_CONDENSER CONSTANT NUMBER(9) := 585;
g_TG_SCH_SELF_SCHED_MW CONSTANT NUMBER(9) := 587;

g_TG_OFF_SLOPE CONSTANT NUMBER(9) := 528;
g_TG_SEL_AVAILABLE CONSTANT NUMBER(9) := 505;

g_TG_DEF_COMMIT_STATUS CONSTANT NUMBER(9) := 529;
g_TG_DEF_FIXED_GEN CONSTANT NUMBER(9) := 530;
g_TG_DEF_ECON_MIN CONSTANT NUMBER(9) := 531;
g_TG_DEF_ECON_MAX CONSTANT NUMBER(9) := 532;
g_TG_DEF_EMER_MIN CONSTANT NUMBER(9) := 533;
g_TG_DEF_EMER_MAX CONSTANT NUMBER(9) := 534;
g_TG_DEF_REGULATION_MIN CONSTANT NUMBER(9) := 535;
g_TG_DEF_REGULATION_MAX CONSTANT NUMBER(9) := 536;
g_TG_DEF_SPINNING_MAX CONSTANT NUMBER(9) := 537;
g_TG_DEF_LOW_ECON_MW CONSTANT NUMBER(9) := 538;
g_TG_DEF_LOW_ECON_TEMP CONSTANT NUMBER(9) := 539;
g_TG_DEF_MID_ECON_MW CONSTANT NUMBER(9) := 540;
g_TG_DEF_MID_ECON_TEMP CONSTANT NUMBER(9) := 541;
g_TG_DEF_HIGH_ECON_MW CONSTANT NUMBER(9) := 542;
g_TG_DEF_HIGH_ECON_TEMP CONSTANT NUMBER(9) := 543;
g_TG_DEF_LOW_EMER_MW CONSTANT NUMBER(9) := 544;
g_TG_DEF_LOW_EMER_TEMP CONSTANT NUMBER(9) := 545;
g_TG_DEF_MID_EMER_MW CONSTANT NUMBER(9) := 546;
g_TG_DEF_MID_EMER_TEMP CONSTANT NUMBER(9) := 547;
g_TG_DEF_HIGH_EMER_MW CONSTANT NUMBER(9) := 548;
g_TG_DEF_HIGH_EMER_TEMP CONSTANT NUMBER(9) := 549;
g_TG_DEF_USE_COST_BASED_START CONSTANT NUMBER(9) := 550;
g_TG_DEF_NO_LOAD_COST CONSTANT NUMBER(9) := 551;
g_TG_DEF_COLD_START_COST CONSTANT NUMBER(9) := 552;
g_TG_DEF_INTER_START_COST CONSTANT NUMBER(9) := 553;
g_TG_DEF_HOT_START_COST CONSTANT NUMBER(9) := 554;
g_TG_DEF_RAMP_RATE CONSTANT NUMBER(9) := 555;
g_TG_DEF_CONDENSE_AVAILABLE CONSTANT NUMBER(9) := 556;
g_TG_DEF_CONDENSE_START_COST CONSTANT NUMBER(9) := 557;
g_TG_DEF_CONDENSE_ENERGY_USAGE CONSTANT NUMBER(9) := 558;
g_TG_DEF_CONDENSE_NOTIF CONSTANT NUMBER(9) := 559;
g_TG_DEF_CONDENSE_HOURLY_COST CONSTANT NUMBER(9) := 560;
g_TG_DEF_CC_MIN_TIME_BETWEEN CONSTANT NUMBER(9) := 1000;
g_TG_DEF_CC_ALLOW_SIMPLE_CYCLE CONSTANT NUMBER(9) := 1001;
g_TG_DEF_CC_FACTOR CONSTANT NUMBER(9) := 1002;
g_TG_DEF_PS_PUMPING_FACTOR CONSTANT NUMBER(9) := 1003;
g_TG_DEF_PS_INITIAL_MWH CONSTANT NUMBER(9) := 1004;
g_TG_DEF_PS_FINAL_MWH CONSTANT NUMBER(9) := 1005;
g_TG_DEF_PS_MAX_MWH CONSTANT NUMBER(9) := 1006;
g_TG_DEF_PS_MIN_MWH CONSTANT NUMBER(9) := 1007;
g_TG_DEF_PS_MIN_GEN_MW CONSTANT NUMBER(9) := 1008;
g_TG_DEF_PS_MIN_PUMP_MW CONSTANT NUMBER(9) := 1009;
g_TG_DEF_PARAM_LIMIT_DESC CONSTANT VARCHAR2(32) := 600;
g_TG_DEF_MAX_DAILY_START_LIMIT CONSTANT NUMBER(9) := 601;
g_TG_DEF_MAX_WEEKLY_STRT_LIMIT CONSTANT NUMBER(9) := 602;
g_TG_DEF_MIN_RUNTIME_LIMIT CONSTANT NUMBER(9) := 603;
g_TG_DEF_MIN_DOWNTIME_LIMIT CONSTANT NUMBER(9) := 604;
g_TG_DEF_TURNDOWN_RATIO_LIMIT CONSTANT NUMBER(9) := 605;

g_TG_UPD_ECON_MIN CONSTANT NUMBER(9) := 561;
g_TG_UPD_ECON_MAX CONSTANT NUMBER(9) := 562;
g_TG_UPD_EMER_MIN CONSTANT NUMBER(9) := 563;
g_TG_UPD_EMER_MAX CONSTANT NUMBER(9) := 564;
g_TG_UPD_COMMIT_STATUS CONSTANT NUMBER(9) := 565;
g_TG_UPD_FIXED_GEN CONSTANT NUMBER(9) := 566;
g_TG_UPD_DEF_ECON_MIN CONSTANT NUMBER(9) := 567;
g_TG_UPD_DEF_ECON_MAX CONSTANT NUMBER(9) := 568;
g_TG_UPD_DEF_EMER_MIN CONSTANT NUMBER(9) := 569;
g_TG_UPD_DEF_EMER_MAX CONSTANT NUMBER(9) := 570;
g_TG_UPD_NOTIF_TIME CONSTANT NUMBER(9) := 1010;
g_TG_UPD_PS_MIN_GEN_MW CONSTANT NUMBER(9) := 1011;
g_TG_UPD_PS_MIN_PUMP_MW CONSTANT NUMBER(9) := 1012;

g_TG_DEF_ENERGY_RAMP_CURVE CONSTANT NUMBER(9) := 571;
	g_TI_DEF_ENERGY_RAMP_MW CONSTANT NUMBER(3) := 1;
	g_TI_DEF_ENERGY_RAMP_RATE CONSTANT NUMBER(3) := 2;
g_TG_DEF_SPIN_RAMP_CURVE CONSTANT NUMBER(9) := 572;
	g_TI_DEF_SPIN_RAMP_MW CONSTANT NUMBER(3) := 1;
	g_TI_DEF_SPIN_RAMP_RATE CONSTANT NUMBER(3) := 2;

g_TG_IS_SELF_SCHEDULED CONSTANT NUMBER(9) := 573; -- USED IN BILLING.

g_TG_DEF_DEFAULT_STARTUP_COST CONSTANT NUMBER(9) := 574;
	g_TI_DEF_DSC_INTERVAL CONSTANT NUMBER(3) := 1;
    g_TI_DEF_DSC_USESTARTUP CONSTANT NUMBER(3) := 2;
    g_TI_DEF_DSC_NOLOADCOST CONSTANT NUMBER(3) := 3;
    g_TI_DEF_DSC_COLDSTARTUPCOST CONSTANT NUMBER(3) := 4;
    g_TI_DEF_DSC_INTMDSARTUPCOST CONSTANT NUMBER(3) := 5;
    g_TI_DEF_DSC_HOTSTARTUPCOST CONSTANT NUMBER(3) := 6;

g_TG_MR_ACTIVE_SCHEDULE CONSTANT NUMBER(9) := 575;

g_TG_OUT_DA_STARTUP_CST_APPLY CONSTANT NUMBER(9) := 576;
g_TG_OUT_RT_STARTUP_CST_APPLY CONSTANT NUMBER(9) := 577;
g_TG_OUT_RT_NOLOAD_CST_APPLY CONSTANT NUMBER(9) := 578;
g_TG_OUT_DESIRED_MWH CONSTANT NUMBER(9) := 579;
g_TG_OUT_SCHEDULE_ID CONSTANT NUMBER(9) := 580;
g_TG_OUT_MWH_REDUCED CONSTANT NUMBER(9) := 581;
g_TG_OUT_DA_NOLOAD_CST_APPLY CONSTANT NUMBER(9) := 599;
g_TG_OUT_FOLLOW_PJM_DISPATCH CONSTANT NUMBER(9) := 588;

g_TG_REG_UPD_MW CONSTANT NUMBER(9) := 589;
g_TG_REG_UPD_MIN_MW CONSTANT NUMBER(9) := 590;
g_TG_REG_UPD_MAX_MW CONSTANT NUMBER(9) := 591;
g_TG_REG_UPD_UNAVAILABLE CONSTANT NUMBER(9) := 592;
g_TG_REG_UPD_SELF_SCHEDULED CONSTANT NUMBER(9) := 593;
g_TG_REG_UPD_SPILLING CONSTANT NUMBER(9) := 594;

g_TG_SPIN_UPD_OFFER_MW CONSTANT NUMBER(9) := 595;
g_TG_SPIN_UPD_MAX_MW CONSTANT NUMBER(9) := 596;
g_TG_SPIN_UPD_UNAVAILABLE CONSTANT NUMBER(9) := 597;
g_TG_SPIN_UPD_SELF_SCHEDULED CONSTANT NUMBER(9) := 598;

g_TG_REG_OFF_UNAVAILABLE CONSTANT NUMBER(9) := 1013;
g_TG_REG_OFF_SELF_SCHEDULED CONSTANT NUMBER(9) := 1014;
g_TG_REG_OFF_MINIMUM_MW CONSTANT NUMBER(9) := 1015;

g_TG_SPIN_OFF_COND_AVAILABLE CONSTANT NUMBER(9) := 1016;
g_TG_SPIN_OFF_COND_START_COST CONSTANT NUMBER(9) := 1017;
g_TG_SPIN_OFF_COND_EN_USAGE CONSTANT NUMBER(9) := 1018;
g_TG_SPIN_OFF_COND_TO_GEN_COST CONSTANT NUMBER(9) := 1019;
g_TG_SPIN_OFF_SPIN_AS_COND CONSTANT NUMBER(9) := 1020;
g_TG_SPIN_OFF_FULL_LOAD_HR CONSTANT NUMBER(9) := 1021;
g_TG_SPIN_OFF_REDUCED_LOAD_HR CONSTANT NUMBER(9) := 1022;
g_TG_SPIN_OFF_VOM_RATE CONSTANT NUMBER(9) := 1023;

g_TG_OUT_ACTUAL_GEN_MKT_RESULT CONSTANT NUMBER(9) := 1024;

g_MEX_MARKET CONSTANT VARCHAR(30) := 'PJM';
END MM_PJM_UTIL;
/