CREATE OR REPLACE PACKAGE MM_PJM_SHADOW_BILL IS

-- $Revision: 1.31 $

FUNCTION WHAT_VERSION RETURN VARCHAR2;

FUNCTION GET_BID_OFFER_PAIRS
	(
	p_CONTRACT_ID IN NUMBER,
	p_CUT_BEGIN_DATE IN DATE,
	p_CUT_END_DATE IN DATE
	) RETURN NUMBER;

FUNCTION P2P_TRANSMISSION_CHARGE
	(
	p_DATE IN DATE,
	p_CONTRACT_ID          IN NUMBER,
	p_IS_FIRM              IN NUMBER,
	p_TRANSACTION_INTERVAL IN VARCHAR2
	) RETURN NUMBER;

FUNCTION DISPATCH_VARIATION
	(
	p_DATE IN DATE,
	p_CONTRACT_ID IN NUMBER
	) RETURN NUMBER;

FUNCTION NITS_CHARGES
	(
	p_DATE IN DATE,
	p_CONTRACT_ID IN NUMBER
	) RETURN NUMBER;

FUNCTION BLACK_START_CREDITS
	(
	p_DATE IN DATE,
	p_CONTRACT_ID IN NUMBER
	) RETURN NUMBER;

FUNCTION FTR_AUCTION_CHARGES
	(
	p_DATE IN DATE,
	p_CONTRACT_ID IN NUMBER
	) RETURN NUMBER;

FUNCTION FTR_AUCTION_CREDITS
	(
	p_DATE IN DATE,
	p_CONTRACT_ID IN NUMBER
	) RETURN NUMBER;

FUNCTION FTR_BID_HOURS
	(
	p_CUT_BEGIN_DATE          IN DATE,
	p_CUT_END_DATE IN DATE,
	p_CONTRACT_ID   IN NUMBER,
	p_IS_OBLIGATION IN NUMBER
	) RETURN NUMBER;

FUNCTION FTR_HOLDER_MW_HOURS
	(
	p_CUT_BEGIN_DATE IN DATE,
	p_CUT_END_DATE IN DATE,
	p_CONTRACT_ID IN NUMBER
	) RETURN NUMBER;

FUNCTION NITS_PEAK_DEMAND
	(
	p_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CONTRACT_ID IN NUMBER,
	p_ZONE IN VARCHAR2
	) RETURN NUMBER;

FUNCTION SUM_PEAK_DEMAND
	(
	p_CUT_BEGIN_DATE IN DATE,
	p_CUT_END_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CONTRACT_ID IN NUMBER,
	p_ZONE IN VARCHAR2
	) RETURN NUMBER;

FUNCTION TOCC_DEMAND
	(
	p_CUT_BEGIN_DATE IN DATE,
	p_CUT_END_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CONTRACT_ID IN NUMBER,
	p_ZONE IN VARCHAR2,
    p_TXN_TYPE IN VARCHAR2
	) RETURN NUMBER;

FUNCTION SYNC_CONDENS_DEMAND
	(
	p_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CONTRACT_ID IN NUMBER,
	p_AREA IN VARCHAR2
	) RETURN NUMBER;

FUNCTION LostOpportunityCost
	(
	pContractID IN NUMBER,
	pDate IN DATE
	) RETURN NUMBER;

FUNCTION RegulationScheduleAmount
	(
	pContractID      IN NUMBER,
	pDate            IN DATE
	) RETURN NUMBER;

FUNCTION RegulationAmountOffered
	(
	pContractID      IN NUMBER,
	pDate            IN DATE,
	pIsSelfScheduled IN NUMBER
	) RETURN NUMBER;

FUNCTION GET_FIRM_P2P_RATE
	(
    p_OASIS_NUMBER VARCHAR2,
    p_CONTRACT_ID NUMBER,
    p_DATE DATE
    ) RETURN NUMBER;

FUNCTION AVG_MONTHLY_PEAK_DEMAND
	(
	p_CUT_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CONTRACT_ID IN NUMBER,
	p_ZONE IN VARCHAR2
	) RETURN NUMBER;

FUNCTION POINT_TO_POINT_USAGE
	(
	p_CUT_BEGIN_DATE IN DATE,
	p_CUT_END_DATE IN DATE,
    p_STATEMENT_TYPE IN NUMBER,
    p_CONTRACT_ID IN NUMBER
    ) RETURN NUMBER;

FUNCTION AVG_P2P_ENERGY_RESV
	(
	p_CUT_BEGIN_DATE IN DATE,
	p_CUT_END_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CONTRACT_ID IN NUMBER,
	p_ZONE IN VARCHAR2
	) RETURN NUMBER;

FUNCTION AVG_P2P_ENERGY_RESV_PJM
	(
	p_CUT_BEGIN_DATE IN DATE,
	p_CUT_END_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CONTRACT_ID IN NUMBER
	) RETURN NUMBER;

FUNCTION SUM_PEAK_IMPORTS
	(
	p_CUT_BEGIN_DATE IN DATE,
	p_CUT_END_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CONTRACT_ID IN NUMBER,
	p_ZONE IN VARCHAR2
	) RETURN NUMBER;

FUNCTION SUM_PEAK_IMPORTS_PJM
	(
	p_CUT_BEGIN_DATE IN DATE,
	p_CUT_END_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CONTRACT_ID IN NUMBER
	) RETURN NUMBER;

FUNCTION RT_LOAD_FOR_MAAC
	(
    p_CUT_BEGIN_DATE IN DATE,
    p_CUT_END_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CONTRACT_ID IN NUMBER
	) RETURN NUMBER;

FUNCTION GET_PRIOR_RATE
	(
    p_DATE IN DATE,
    p_NAME IN VARCHAR2,
    p_CONTRACT IN NUMBER,
    p_ZONE_NAME IN VARCHAR2 := NULL
    ) RETURN NUMBER;

FUNCTION GET_RECONCILIATION_MWH
	(
    p_CONTRACT IN NUMBER,
    p_BEGIN_DATE IN DATE,
    p_SCHEDULE_TYPE IN NUMBER
    --p_ZONE IN VARCHAR2
    ) RETURN NUMBER;

FUNCTION GET_SPOT_RECONCIL_AMT
	(
    p_DATE IN DATE,
    p_TXN_IDENTIFIER IN VARCHAR2,
    p_SCHEDULE_TYPE IN NUMBER,
    p_CONTRACT_ID IN NUMBER,
    p_MKT_PRICE_TYPE IN VARCHAR2
    ) RETURN NUMBER;

FUNCTION GET_RECONCIL_AMT
	(
    p_DATE IN DATE,
    p_SCHEDULE_TYPE IN NUMBER,
    p_ZONE IN VARCHAR2,
    p_NAME IN VARCHAR2,
    p_CONTRACT_ID IN NUMBER
    ) RETURN NUMBER;

FUNCTION GET_LOSS_FACTOR
	(
    p_DATE IN DATE
    ) RETURN NUMBER;

FUNCTION GET_PRICE
	(
	p_EXTERNAL_ID IN VARCHAR2,
	p_PRICE_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_SCHEDULE
	(
	p_EXTERNAL_ID IN VARCHAR2,
	p_SCHEDULE_TYPE IN NUMBER,
	p_SCHEDULE_DATE IN DATE,
	p_CONTRACT_ID IN NUMBER := 0
	) RETURN NUMBER;

FUNCTION GET_LSR_LOAD
	(
	p_SCHEDULE_TYPE IN NUMBER,
	p_SCHEDULE_DATE IN DATE,
	p_CONTRACT_ID IN NUMBER
	) RETURN NUMBER;

FUNCTION GET_FTR_TRAIT
	(
	p_TRANSACTION_ID IN NUMBER,
	p_ATTRIBUTE IN VARCHAR2,
    p_DATE IN DATE := LOW_DATE
	) RETURN NUMBER;

FUNCTION GET_DA_MKT_VALUE
    (
    p_GEN_ID IN VARCHAR2,
    p_DATE IN DATE,
    p_CONTRACT_ID IN NUMBER,
    p_SCHEDULE_TYPE IN NUMBER,
		p_OWN_PERCENT IN NUMBER
    ) RETURN NUMBER;

FUNCTION GET_DA_OFFER_AMOUNT
    (
    p_GEN_ID IN VARCHAR2,
    p_DATE IN DATE,
    p_CONTRACT_ID IN NUMBER,
    p_SCHEDULE_TYPE IN NUMBER,
		p_OWN_PERCENT IN NUMBER
    ) RETURN NUMBER;

FUNCTION GET_DA_CREDIT
 (
    p_GEN_ID IN VARCHAR2,
    p_DATE IN DATE,
    p_CONTRACT_ID IN NUMBER,
    p_SCHEDULE_TYPE IN NUMBER
    ) RETURN NUMBER;

FUNCTION GET_BAL_CREDIT
 (
    p_GEN_ID IN VARCHAR2,
    p_DATE IN DATE,
    p_CONTRACT_ID IN NUMBER,
    p_SCHEDULE_TYPE IN NUMBER
    ) RETURN NUMBER;

FUNCTION GET_MWH_REDUCED
    (
    p_GEN_ID IN VARCHAR2,
    p_CONTRACT IN NUMBER,
    p_DATE IN DATE
    ) RETURN NUMBER;
FUNCTION GET_OFFER_AT_RT_MW
    (
    p_GEN_ID IN VARCHAR2,
    p_DATE IN DATE,
    p_CONTRACT_ID IN NUMBER,
    p_SCHEDULE_TYPE IN NUMBER
    ) RETURN NUMBER;
FUNCTION GET_OFFER_AT_DA_MW
    (
    p_GEN_ID IN VARCHAR2,
    p_CONTRACT IN NUMBER,
    p_DATE IN DATE,
    p_SCHEDULE_TYPE IN NUMBER
    ) RETURN NUMBER;
FUNCTION GET_ARR_RATE
    (
    p_CONTRACT_ID IN NUMBER,
    p_DATE IN DATE
    ) RETURN NUMBER;
FUNCTION GET_PEAK_LOAD
    (
    p_CONTRACT_ID IN NUMBER,
    p_DATE IN DATE,
    p_STATEMENT_TYPE IN NUMBER
    ) RETURN NUMBER;
FUNCTION GET_POSITIVE_RT_GEN
    (
    p_CONTRACT IN NUMBER,
    p_SCHED_DATE IN DATE,
    p_SCHEDULE_TYPE IN NUMBER,
		p_SERVICE_POINT IN VARCHAR2
    ) RETURN NUMBER;
FUNCTION GET_RT_LOAD_FROM_GEN
    (
    p_CONTRACT IN NUMBER,
    p_SCHED_DATE IN DATE,
    p_SCHEDULE_TYPE IN NUMBER,
		p_SERVICE_POINT IN VARCHAR2
    ) RETURN NUMBER;
FUNCTION GET_RT_LOAD_FROM_GEN_MNTH
    (
    p_CONTRACT IN NUMBER,
    p_SCHED_DATE IN DATE,
    p_SCHEDULE_TYPE IN NUMBER
    ) RETURN NUMBER;
FUNCTION GET_DISPATCH_VARIATION
    (
    p_DATE IN DATE,
    p_CONTRACT IN NUMBER,
    p_SCHEDULE_TYPE IN NUMBER
    ) RETURN NUMBER;
FUNCTION IS_REGULATION_HOUR
    (
    p_DATE IN DATE,
    p_GEN_ID IN VARCHAR2,
    p_SCHEDULE_TYPE IN NUMBER,
    p_CONTRACT_ID IN NUMBER
    ) RETURN NUMBER;
FUNCTION FOLLOWING_PJM_DISPATCH
    (
    p_DATE IN DATE,
    p_GEN_ID IN VARCHAR2,
    p_CONTRACT_ID IN NUMBER
    ) RETURN NUMBER;
FUNCTION GET_ECON_MAX
    (
    p_GEN_ID IN VARCHAR2,
    p_DATE IN DATE,
    p_CONTRACT_ID IN NUMBER
    ) RETURN NUMBER;
FUNCTION GET_ECON_MIN
    (
    p_GEN_ID IN VARCHAR2,
    p_DATE IN DATE,
    p_CONTRACT_ID IN NUMBER
    ) RETURN NUMBER;
FUNCTION GET_SPOT_CHARGE_AMT
    (
    p_COMPONENT_EXT_ID IN VARCHAR2,
    p_DATE IN DATE,
    p_CONTRACT_ID IN NUMBER
    ) RETURN NUMBER;
FUNCTION GET_CONGESTION_FLAG
    (
    p_DATE IN DATE,
    p_CONTRACT IN NUMBER,
    p_SCHEDULE_TYPE IN NUMBER
    ) RETURN NUMBER;
FUNCTION USE_RT_SALES
    (
    p_CONTRACT IN NUMBER
    ) RETURN NUMBER;
FUNCTION GET_RECONCILIATION_LAG
    (
    p_CONTRACT IN NUMBER
    ) RETURN NUMBER;
FUNCTION GET_DA_GEN_ALLOCATED
    (
    p_CONTRACT IN NUMBER,
    p_SCHED_DATE IN DATE,
    p_SCHEDULE_TYPE IN NUMBER
    ) RETURN NUMBER;
FUNCTION GET_INADVERENT_MW
	(
	p_CONTRACT_ID IN NUMBER,
	p_DATE IN DATE,
	p_SCHEDULE_TYPE IN NUMBER
	) RETURN NUMBER;
FUNCTION GET_ZONE
    (
    p_CONTRACT IN NUMBER
    ) RETURN VARCHAR2;

FUNCTION GET_EXTERNAL_CHG_AMOUNT
    (
    p_BILL_ENTITY IN NUMBER,
    p_COMPONENT_ID IN NUMBER,
    p_DATE IN DATE,
    p_STATEMENT_TYPE IN NUMBER
    ) RETURN NUMBER;

FUNCTION GET_REGULATION_AMOUNT
  (
  p_CONTRACT      IN NUMBER,
	p_CUT_DATE          IN DATE,
  p_STATEMENT_TYPE IN NUMBER
  ) RETURN NUMBER;
  
FUNCTION GET_SCHEDULE_AMOUNT
	(
	p_TRANS_TYPE IN VARCHAR2,
  p_COMMODITY IN VARCHAR2,
	p_SCHEDULE_TYPE IN NUMBER,
	p_SCHEDULE_DATE IN DATE,
	p_CONTRACT_ID IN NUMBER,
  p_INTERVAL IN VARCHAR2
	) RETURN NUMBER;

FUNCTION GET_OP_RES_CREDIT_AMT
    (
    p_CONTRACT_ID IN NUMBER,
    p_STATEMENT_DATE IN DATE,
    p_STATEMENT_TYPE_ID IN NUMBER,
    p_COMPONENT_IDENTIFIER IN VARCHAR2
    ) RETURN NUMBER;

FUNCTION GET_COMBO_CREDIT_AMT
    (
    p_CONTRACT_ID IN NUMBER,
    p_STATEMENT_DATE IN DATE,
    p_STATEMENT_TYPE_ID IN NUMBER,
    p_PARENT_COMPONENT_IDENT IN VARCHAR2,
    p_COMPONENT_IDENTIFIER IN VARCHAR2
    ) RETURN NUMBER;

END MM_PJM_SHADOW_BILL;
/