/* 
Run at implementation for PJM market participants. Creates all PJM zones, 
plus zone attributes required for calculation of Firm and Non-firm Point-to-point 
Transmission Service Charges.
*/
DECLARE
	TYPE t_ARRAY IS VARRAY(32) OF VARCHAR2(32);
	l_ZONES      t_ARRAY := t_ARRAY('AECO', 'APS', 'BGE', 'DPL', 'JCPL', 'METED',
									'PENELEC', 'PECO', 'PPL', 'PEPCO', 'PSEG');
	l_ATTRIBUTES t_ARRAY := t_ARRAY('Non-firm P2P Hourly On',
									'Non-firm P2P Hourly Off', 'Firm P2P Yearly',
									'Firm P2P Monthly', 'Firm P2P Weekly',
									'Firm P2P Daily On', 'Firm P2P Daily Off',
									'Non-firm P2P Daily Off',
									'Non-firm P2P Daily On', 'Non-firm P2P Weekly',
									'Non-firm P2P Monthly');

	TYPE t_ID IS TABLE OF NUMBER INDEX BY VARCHAR2(32);
	l_ATTRIBUTE_IDS t_ID;
	l_ZONE_IDS      t_ID;

	TYPE t_ATTRIBUTE_VALUE IS TABLE OF NUMBER INDEX BY VARCHAR2(32);
	l_FIRM_P2P_DAILY_ON      t_ATTRIBUTE_VALUE;
	l_FIRM_P2P_DAILY_OFF     t_ATTRIBUTE_VALUE;
	l_FIRM_P2P_MONTHLY       t_ATTRIBUTE_VALUE;
	l_FIRM_P2P_WEEKLY        t_ATTRIBUTE_VALUE;
	l_FIRM_P2P_YEARLY        t_ATTRIBUTE_VALUE;
	l_NONFIRM_P2P_HOURLY_ON  t_ATTRIBUTE_VALUE;
	l_NONFIRM_P2P_HOURLY_OFF t_ATTRIBUTE_VALUE;
	l_NONFIRM_P2P_DAILY_ON   t_ATTRIBUTE_VALUE;
	l_NONFIRM_P2P_DAILY_OFF  t_ATTRIBUTE_VALUE;
	l_NONFIRM_P2P_MONTHLY    t_ATTRIBUTE_VALUE;
	l_NONFIRM_P2P_WEEKLY     t_ATTRIBUTE_VALUE;

	l_SERVICE_ZONE_DOMAIN_ID NUMBER;

	FUNCTION ADD_ATTRIBUTE(p_ATTRIBUTE_NAME IN VARCHAR2,
						 p_DOMAIN_ID      IN NUMBER) RETURN NUMBER IS
	l_OID    NUMBER;
	l_STATUS NUMBER;
	BEGIN
	EM.PUT_ENTITY_ATTRIBUTE(p_ENTITY_DOMAIN_ID => p_DOMAIN_ID,
							p_ATTRIBUTE_NAME   => p_ATTRIBUTE_NAME,
							p_ATTRIBUTE_ID     => 0,
							p_ATTRIBUTE_TYPE   => 'Float',
							p_ATTRIBUTE_SHOW   => 1,
							p_STATUS           => l_STATUS);
	
	SELECT EA.ATTRIBUTE_ID
		INTO l_OID
		FROM ENTITY_ATTRIBUTE EA
	 WHERE EA.ENTITY_DOMAIN_ID = p_DOMAIN_ID
		 AND EA.ATTRIBUTE_NAME = p_ATTRIBUTE_NAME;
	
	RETURN l_OID;
	END ADD_ATTRIBUTE;

	FUNCTION ADD_ZONE(p_ZONE_NAME IN VARCHAR2) RETURN NUMBER IS
	l_OID NUMBER;
	BEGIN
	IO.PUT_SERVICE_ZONE(l_OID, p_ZONE_NAME, p_ZONE_NAME, p_ZONE_NAME, 0, 0);
	IF l_OID = -1 THEN
		-- already created; find it
		SELECT SZ.SERVICE_ZONE_ID
		INTO l_OID
		FROM SERVICE_ZONE SZ
		 WHERE SZ.SERVICE_ZONE_NAME = p_ZONE_NAME;
	END IF;
	RETURN l_OID;
	END ADD_ZONE;

	PROCEDURE ADD_ZONE_ATTRIBUTES(p_ENTITY_DOMAIN_ID IN NUMBER,
								p_ENTITY_ID        IN NUMBER,
								p_ATTRIBUTE_ID     IN NUMBER,
								p_ATTRIBUTE_VAL    IN NUMBER) IS
	l_STATUS NUMBER;
	BEGIN
    -- note that since all these attributes are in $/kW or $/kWh, we have
    -- to convert to MW before storing them
	EM.PUT_ENTITY_ATTRIBUTE_VALUE(p_ENTITY_DOMAIN_ID => p_ENTITY_DOMAIN_ID,
									p_OWNER_ENTITY_ID => p_ENTITY_ID,
									p_ATTRIBUTE_ID => p_ATTRIBUTE_ID,
									p_BEGIN_DATE => TO_DATE('01/01/2004',
															 'MM/DD/YYYY'),
									p_END_DATE => NULL,
									p_ATTRIBUTE_VAL => p_ATTRIBUTE_VAL/1000.0,
									p_OLD_OWNER_ENTITY_ID => p_ENTITY_ID,
									p_OLD_ATTRIBUTE_ID => p_ATTRIBUTE_ID,
									p_OLD_BEGIN_DATE => TO_DATE('01/01/2004',
															 'MM/DD/YYYY'), p_STATUS => l_STATUS);
	END ADD_ZONE_ATTRIBUTES;

BEGIN
	SELECT ED.ENTITY_DOMAIN_ID
	INTO l_SERVICE_ZONE_DOMAIN_ID
	FROM ENTITY_DOMAIN ED
	 WHERE ED.ENTITY_DOMAIN_ALIAS = 'Service Zone';
	FOR i IN 1..l_ATTRIBUTES.COUNT LOOP
	l_ATTRIBUTE_IDS(l_ATTRIBUTES(i)) := ADD_ATTRIBUTE(l_ATTRIBUTES(i),
														l_SERVICE_ZONE_DOMAIN_ID);
	END LOOP;

	FOR i IN 1..l_ZONES.COUNT LOOP
	l_ZONE_IDS(l_ZONES(i)) := ADD_ZONE(l_ZONES(i));
	END LOOP;

	-- fill in the attributes for each service zone
	l_FIRM_P2P_DAILY_OFF('AECO') := 0.065;
	l_FIRM_P2P_DAILY_OFF('APS') := 0.0573;
	l_FIRM_P2P_DAILY_OFF('BGE') := 0.043;
	l_FIRM_P2P_DAILY_OFF('DPL') := 0.053;
	l_FIRM_P2P_DAILY_OFF('JCPL') := 0.0414;
	l_FIRM_P2P_DAILY_OFF('METED') := 0.0414;
	l_FIRM_P2P_DAILY_OFF('PENELEC') := 0.0414;
	l_FIRM_P2P_DAILY_OFF('PECO') := 0.0722;
	l_FIRM_P2P_DAILY_OFF('PPL') := 0.0618;
	l_FIRM_P2P_DAILY_OFF('PEPCO') := 0.058;
	l_FIRM_P2P_DAILY_OFF('PSEG') := 0.0651;

	l_FIRM_P2P_DAILY_ON('AECO') := 0.092;
	l_FIRM_P2P_DAILY_ON('APS') := 0.0802;
	l_FIRM_P2P_DAILY_ON('BGE') := 0.06;
	l_FIRM_P2P_DAILY_ON('DPL') := 0.075;
	l_FIRM_P2P_DAILY_ON('JCPL') := 0.0581;
	l_FIRM_P2P_DAILY_ON('METED') := 0.0581;
	l_FIRM_P2P_DAILY_ON('PENELEC') := 0.0581;
	l_FIRM_P2P_DAILY_ON('PECO') := 0.101;
	l_FIRM_P2P_DAILY_ON('PPL') := 0.0866;
	l_FIRM_P2P_DAILY_ON('PEPCO') := 0.081;
	l_FIRM_P2P_DAILY_ON('PSEG') := 0.0911;

	l_FIRM_P2P_WEEKLY('AECO') := 0.485;
	l_FIRM_P2P_WEEKLY('APS') := 0.4009;
	l_FIRM_P2P_WEEKLY('BGE') := 0.301;
	l_FIRM_P2P_WEEKLY('DPL') := 0.373;
	l_FIRM_P2P_WEEKLY('JCPL') := 0.2906;
	l_FIRM_P2P_WEEKLY('METED') := 0.2906;
	l_FIRM_P2P_WEEKLY('PENELEC') := 0.2906;
	l_FIRM_P2P_WEEKLY('PECO') := 0.5051;
	l_FIRM_P2P_WEEKLY('PPL') := 0.4328;
	l_FIRM_P2P_WEEKLY('PEPCO') := 0.404;
	l_FIRM_P2P_WEEKLY('PSEG') := 0.4577;

	l_FIRM_P2P_MONTHLY('AECO') := 1.984;
	l_FIRM_P2P_MONTHLY('APS') := 1.737;
	l_FIRM_P2P_MONTHLY('BGE') := 1.306;
	l_FIRM_P2P_MONTHLY('DPL') := 1.615;
	l_FIRM_P2P_MONTHLY('JCPL') := 1.259;
	l_FIRM_P2P_MONTHLY('METED') := 1.259;
	l_FIRM_P2P_MONTHLY('PENELEC') := 1.259;
	l_FIRM_P2P_MONTHLY('PECO') := 02.189;
	l_FIRM_P2P_MONTHLY('PPL') := 1.876;
	l_FIRM_P2P_MONTHLY('PEPCO') := 1.75;
	l_FIRM_P2P_MONTHLY('PSEG') := 1.975;

	l_FIRM_P2P_YEARLY('AECO') := 23.809;
	l_FIRM_P2P_YEARLY('APS') := 20.847;
	l_FIRM_P2P_YEARLY('BGE') := 15.675;
	l_FIRM_P2P_YEARLY('DPL') := 19.3780;
	l_FIRM_P2P_YEARLY('JCPL') := 15.1120;
	l_FIRM_P2P_YEARLY('METED') := 15.1120;
	l_FIRM_P2P_YEARLY('PENELEC') := 15.1120;
	l_FIRM_P2P_YEARLY('PECO') := 26.2640;
	l_FIRM_P2P_YEARLY('PPL') := 22.5070;
	l_FIRM_P2P_YEARLY('PEPCO') := 20.9990;
	l_FIRM_P2P_YEARLY('PSEG') := 23.6960;

	l_NONFIRM_P2P_HOURLY_OFF('AECO') := 0.00272;
	l_NONFIRM_P2P_HOURLY_OFF('APS') := 0.00180;
	l_NONFIRM_P2P_HOURLY_OFF('BGE') := 0.00221;
	l_NONFIRM_P2P_HOURLY_OFF('DPL') := 0.00173;
	l_NONFIRM_P2P_HOURLY_OFF('JCPL') := 0.00173;
	l_NONFIRM_P2P_HOURLY_OFF('METED') := 0.00173;
	l_NONFIRM_P2P_HOURLY_OFF('PENELEC') := 0.00301;
	l_NONFIRM_P2P_HOURLY_OFF('PECO') := 0.00258;
	l_NONFIRM_P2P_HOURLY_OFF('PPL') := 0.00240;
	l_NONFIRM_P2P_HOURLY_OFF('PEPCO') := 0.00271;
	l_NONFIRM_P2P_HOURLY_OFF('PSEG') := 0.00239;

	l_NONFIRM_P2P_HOURLY_ON('AECO') := 0.0057;
	l_NONFIRM_P2P_HOURLY_ON('APS') := 0.005;
	l_NONFIRM_P2P_HOURLY_ON('BGE') := 0.0038;
	l_NONFIRM_P2P_HOURLY_ON('DPL') := 0.0046;
	l_NONFIRM_P2P_HOURLY_ON('JCPL') := 0.0036;
	l_NONFIRM_P2P_HOURLY_ON('METED') := 0.0036;
	l_NONFIRM_P2P_HOURLY_ON('PENELEC') := 0.0036;
	l_NONFIRM_P2P_HOURLY_ON('PECO') := 0.0063;
	l_NONFIRM_P2P_HOURLY_ON('PPL') := 0.0054;
	l_NONFIRM_P2P_HOURLY_ON('PEPCO') := 0.005;
	l_NONFIRM_P2P_HOURLY_ON('PSEG') := 0.0057;

	l_NONFIRM_P2P_DAILY_OFF('AECO') := 0.065;
	l_NONFIRM_P2P_DAILY_OFF('APS') := 0.0573;
	l_NONFIRM_P2P_DAILY_OFF('BGE') := 0.043;
	l_NONFIRM_P2P_DAILY_OFF('DPL') := 0.053;
	l_NONFIRM_P2P_DAILY_OFF('JCPL') := 0.0414;
	l_NONFIRM_P2P_DAILY_OFF('METED') := 0.0414;
	l_NONFIRM_P2P_DAILY_OFF('PENELEC') := 0.0414;
	l_NONFIRM_P2P_DAILY_OFF('PECO') := 0.0722;
	l_NONFIRM_P2P_DAILY_OFF('PPL') := 0.0618;
	l_NONFIRM_P2P_DAILY_OFF('PEPCO') := 0.058;
	l_NONFIRM_P2P_DAILY_OFF('PSEG') := 0.0651;

	l_NONFIRM_P2P_DAILY_ON('AECO') := 0.0920;
	l_NONFIRM_P2P_DAILY_ON('APS') := 0.0600;
	l_NONFIRM_P2P_DAILY_ON('BGE') := 0.0750;
	l_NONFIRM_P2P_DAILY_ON('DPL') := 0.0581;
	l_NONFIRM_P2P_DAILY_ON('JCPL') := 0.0581;
	l_NONFIRM_P2P_DAILY_ON('METED') := 0.0581;
	l_NONFIRM_P2P_DAILY_ON('PENELEC') := 0.1010;
	l_NONFIRM_P2P_DAILY_ON('PECO') := 0.0866;
	l_NONFIRM_P2P_DAILY_ON('PPL') := 0.0810;
	l_NONFIRM_P2P_DAILY_ON('PEPCO') := 0.0911;
	l_NONFIRM_P2P_DAILY_ON('PSEG') := 0.0802;

	l_NONFIRM_P2P_WEEKLY('AECO') := 0.485;
	l_NONFIRM_P2P_WEEKLY('APS') := 0.4009;
	l_NONFIRM_P2P_WEEKLY('BGE') := 0.301;
	l_NONFIRM_P2P_WEEKLY('DPL') := 0.373;
	l_NONFIRM_P2P_WEEKLY('JCPL') := 0.2906;
	l_NONFIRM_P2P_WEEKLY('METED') := 0.2906;
	l_NONFIRM_P2P_WEEKLY('PENELEC') := 0.2906;
	l_NONFIRM_P2P_WEEKLY('PECO') := 0.5051;
	l_NONFIRM_P2P_WEEKLY('PPL') := 0.4328;
	l_NONFIRM_P2P_WEEKLY('PEPCO') := 0.404;
	l_NONFIRM_P2P_WEEKLY('PSEG') := 0.4577;

	l_NONFIRM_P2P_MONTHLY('AECO') := 1.984;
	l_NONFIRM_P2P_MONTHLY('APS') := 1.737;
	l_NONFIRM_P2P_MONTHLY('BGE') := 1.306;
	l_NONFIRM_P2P_MONTHLY('DPL') := 1.615;
	l_NONFIRM_P2P_MONTHLY('JCPL') := 1.259;
	l_NONFIRM_P2P_MONTHLY('METED') := 1.259;
	l_NONFIRM_P2P_MONTHLY('PENELEC') := 1.259;
	l_NONFIRM_P2P_MONTHLY('PECO') := 02.189;
	l_NONFIRM_P2P_MONTHLY('PPL') := 1.876;
	l_NONFIRM_P2P_MONTHLY('PEPCO') := 1.75;
	l_NONFIRM_P2P_MONTHLY('PSEG') := 1.975;

	FOR i IN 1 .. l_ZONES.COUNT LOOP
	ADD_ZONE_ATTRIBUTES(l_SERVICE_ZONE_DOMAIN_ID, l_ZONE_IDS(l_ZONES(i)), l_ATTRIBUTE_IDS('Firm P2P Daily On'),
						l_FIRM_P2P_DAILY_ON(l_ZONES(i)));
	ADD_ZONE_ATTRIBUTES(l_SERVICE_ZONE_DOMAIN_ID, l_ZONE_IDS(l_ZONES(i)), l_ATTRIBUTE_IDS('Firm P2P Daily Off'),
						l_FIRM_P2P_DAILY_OFF(l_ZONES(i)));
	ADD_ZONE_ATTRIBUTES(l_SERVICE_ZONE_DOMAIN_ID, l_ZONE_IDS(l_ZONES(i)), l_ATTRIBUTE_IDS('Firm P2P Monthly'),
						l_FIRM_P2P_MONTHLY(l_ZONES(i)));
	ADD_ZONE_ATTRIBUTES(l_SERVICE_ZONE_DOMAIN_ID, l_ZONE_IDS(l_ZONES(i)), l_ATTRIBUTE_IDS('Firm P2P Weekly'),
						l_FIRM_P2P_WEEKLY(l_ZONES(i)));
	ADD_ZONE_ATTRIBUTES(l_SERVICE_ZONE_DOMAIN_ID, l_ZONE_IDS(l_ZONES(i)), l_ATTRIBUTE_IDS('Firm P2P Yearly'),
						l_FIRM_P2P_YEARLY(l_ZONES(i)));
	ADD_ZONE_ATTRIBUTES(l_SERVICE_ZONE_DOMAIN_ID, l_ZONE_IDS(l_ZONES(i)), l_ATTRIBUTE_IDS('Non-firm P2P Hourly On'),
						l_NONFIRM_P2P_HOURLY_ON(l_ZONES(i)));
	ADD_ZONE_ATTRIBUTES(l_SERVICE_ZONE_DOMAIN_ID, l_ZONE_IDS(l_ZONES(i)), l_ATTRIBUTE_IDS('Non-firm P2P Hourly Off'),
						l_NONFIRM_P2P_HOURLY_OFF(l_ZONES(i)));
	ADD_ZONE_ATTRIBUTES(l_SERVICE_ZONE_DOMAIN_ID, l_ZONE_IDS(l_ZONES(i)), l_ATTRIBUTE_IDS('Non-firm P2P Daily On'),
						l_NONFIRM_P2P_DAILY_ON(l_ZONES(i)));
	ADD_ZONE_ATTRIBUTES(l_SERVICE_ZONE_DOMAIN_ID, l_ZONE_IDS(l_ZONES(i)), l_ATTRIBUTE_IDS('Non-firm P2P Daily Off'),
						l_NONFIRM_P2P_DAILY_OFF(l_ZONES(i)));
	ADD_ZONE_ATTRIBUTES(l_SERVICE_ZONE_DOMAIN_ID, l_ZONE_IDS(l_ZONES(i)), l_ATTRIBUTE_IDS('Non-firm P2P Monthly'),
						l_NONFIRM_P2P_MONTHLY(l_ZONES(i)));
	ADD_ZONE_ATTRIBUTES(l_SERVICE_ZONE_DOMAIN_ID, l_ZONE_IDS(l_ZONES(i)), l_ATTRIBUTE_IDS('Non-firm P2P Weekly'),
						l_NONFIRM_P2P_WEEKLY(l_ZONES(i)));
	END LOOP;
	COMMIT;
END;
/