CREATE OR REPLACE PACKAGE MM_OASIS_UTIL IS
-- $Revision: 1.16 $
  TYPE REF_CURSOR IS REF CURSOR;

g_TG_OFFER_PRICE CONSTANT NUMBER(9) := 601;
g_TG_CAP_REQUESTED CONSTANT NUMBER(9) := 602;
g_TG_CAP_GRANTED CONSTANT NUMBER(9) := 603;
g_TG_PRECONFIRMED CONSTANT NUMBER(9) := 604;
g_TG_CUST_COMMENTS CONSTANT NUMBER(9) := 605;
g_TG_STATUS_COMMENTS CONSTANT NUMBER(9) := 606;
g_TG_SELLER_COMMENTS CONSTANT NUMBER(9) := 607;
g_TG_PROVIDER_COMMENTS CONSTANT NUMBER(9) := 608;

g_EA_TS_CLASS CONSTANT VARCHAR2(16) := 'TS CLASS';
g_EA_TS_TYPE CONSTANT VARCHAR2(16) := 'TS TYPE';
g_EA_TS_PERIOD CONSTANT VARCHAR2(16) := 'TS PERIOD';
g_EA_TS_WINDOW CONSTANT VARCHAR2(16) := 'TS WINDOW';
g_EA_TS_SUBCLASS CONSTANT VARCHAR2(16) := 'TS SUBCLASS';
g_EA_RELATED_REF CONSTANT VARCHAR2(16) := 'RELATED REF';

g_MEX_MARKET CONSTANT VARCHAR2(32) := 'oasis';
g_MEX_ACTION_QUERY VARCHAR2(32) := 'query';
g_MEX_ACTION_SUBMIT VARCHAR2(32) := 'submit';

-- Are we simply testing the queries?
g_LOG_ONLY BOOLEAN := FALSE;

FUNCTION WHAT_VERSION RETURN VARCHAR2;

PROCEDURE GET_ID_FOR_ENTITY_ATTRIBUTE
	(
	p_ATTRIBUTE_NAME IN VARCHAR2,
	p_ATTRIBUTE_ID IN OUT NUMBER
	);


PROCEDURE PUT_ENTITY_ATTRIBUTES(p_TRANSACTION_ID IN NUMBER,
								p_ATTRIBUTE_ID   IN NUMBER,
								p_ATTRIBUTE_VAL  IN VARCHAR2,
								p_START_DATE     IN DATE,
								p_STATUS         OUT NUMBER);

FUNCTION ID_FOR_PSE_IDENT(p_PSE_IDENT           IN VARCHAR2,
						  p_CREATE_IF_NOT_FOUND IN BOOLEAN) RETURN NUMBER;

FUNCTION GENERATE_DEAL_REF(p_CUST_ALIAS IN VARCHAR2) RETURN VARCHAR2;

FUNCTION BUILD_TXN_NAME(p_TP_ID     IN NUMBER,
						p_POR       IN VARCHAR2,
						p_POD       IN VARCHAR2,
						p_TS_TYPE   IN VARCHAR2,
						p_INCREMENT IN VARCHAR2) RETURN VARCHAR2;

FUNCTION GET_SELLER_ID_FOR_TP
	(
	p_TP_ID IN NUMBER
	) RETURN NUMBER;


END MM_OASIS_UTIL;
/