BEGIN CDI_DROP_OBJECT('CDI_TYPICAL_DAY_RUN_ACCOUNT', 'TABLE'); END;
/

CREATE GLOBAL TEMPORARY TABLE CDI_TYPICAL_DAY_RUN_ACCOUNT(ACCOUNT_ID NUMBER(9), CONSTRAINT PK_TYPICAL_DAY_RUN_ACCOUNT PRIMARY KEY (ACCOUNT_ID))
ON COMMIT PRESERVE ROWS;
