CREATE OR REPLACE SYNONYM CDI_REPORT FOR ROMO_CUSTOM.CDI_REPORT;
CREATE OR REPLACE SYNONYM CDI_PJM FOR ROMO_CUSTOM.CDI_PJM;
CREATE OR REPLACE SYNONYM CDI_PJM_INSCHEDULE FOR ROMO_CUSTOM.CDI_PJM_INSCHEDULE;
CREATE OR REPLACE SYNONYM CDI_MULTI_ACCOUNT_REPORTS FOR ROMO_CUSTOM.CDI_MULTI_ACCOUNT_REPORTS;
CREATE OR REPLACE SYNONYM CDI_PJM_SHORT_NAME FOR ROMO_CUSTOM.CDI_PJM_SHORT_NAME;
CREATE OR REPLACE SYNONYM CDI_PJM_SHORT_NAME_TEMP FOR ROMO_CUSTOM.CDI_PJM_SHORT_NAME_TEMP;

