CREATE OR REPLACE FUNCTION SCHEDULE_AS_OF_DATE
	(
	p_TRANSACTION_ID IN NUMBER,
	p_SCHEDULE_TYPE IN NUMBER,
	p_SCHEDULE_STATE IN NUMBER,
	p_SCHEDULE_DATE IN DATE,
	p_AS_OF_DATE IN DATE
	) RETURN DATE IS
--Revision: $Revision: 1.18 $

-- Answer the maximun as of date that is less than or equal to the argument as of date.

v_AS_OF_DATE DATE := LOW_DATE;

BEGIN

	IF GA.VERSION_SCHEDULE THEN
		SELECT MAX(AS_OF_DATE)
		INTO v_AS_OF_DATE
		FROM IT_SCHEDULE
		WHERE TRANSACTION_ID = p_TRANSACTION_ID
			AND SCHEDULE_TYPE = p_SCHEDULE_TYPE
			AND SCHEDULE_STATE = p_SCHEDULE_STATE
			AND SCHEDULE_DATE = p_SCHEDULE_DATE
			AND AS_OF_DATE <= p_AS_OF_DATE;
	END IF;

	RETURN v_AS_OF_DATE;

	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			RETURN v_AS_OF_DATE;
		WHEN OTHERS THEN
			RAISE;

END SCHEDULE_AS_OF_DATE;
/

