CREATE OR REPLACE VIEW TDIE_GEN_UNITS AS
SELECT /*+ ordered use_nl(asl) use_nl(slm) */ ASL.ACCOUNT_ID,
    EI.GET_ENTITY_IDENTIFIER_EXTSYS(-170, -- EC.ED_ACCOUNT
                            ASL.ACCOUNT_ID,
                            1500, -- EC.ES_TDIE
                            'Default',
                            1) AS MPRN,
    SU_IDENT.EXTERNAL_IDENTIFIER AS SUPPLIER_UNIT,
    AESP.ESP_ID,
    SU_IDENT.ENTITY_ID AS SU_SP_ID,
    GEN_IDENT.EXTERNAL_IDENTIFIER AS GENERATOR_UNIT,
    GEN_SP.SERVICE_POINT_ID AS GEN_SP_ID,
    GREATEST(AESP.BEGIN_DATE, SLM.BEGIN_DATE, ASL.BEGIN_DATE, MSG.BEGIN_DATE) AS BEGIN_DATE,
    LEAST(NVL(AESP.END_DATE, HIGH_DATE), NVL(SLM.END_DATE, HIGH_DATE), NVL(ASL.END_DATE, HIGH_DATE),
        NVL(MSG.END_DATE, HIGH_DATE)) AS END_DATE,
    MP.PSE_ID,
    MP.JURISDICTION AS JURISDICTION
FROM EXTERNAL_SYSTEM_IDENTIFIER GEN_IDENT,
    SERVICE_POINT GEN_SP,
    SCHEDULE_GROUP SG,
    METER_SCHEDULE_GROUP MSG,
    SERVICE_LOCATION_METER SLM,
       ACCOUNT_SERVICE_LOCATION ASL,
    ACCOUNT_ESP AESP,
    EXTERNAL_SYSTEM_IDENTIFIER ESP_IDENT,
    EXTERNAL_SYSTEM_IDENTIFIER SU_IDENT,
    SEM_MP_UNITS MP
WHERE SG.SCHEDULE_GROUP_ID = MSG.SCHEDULE_GROUP_ID
    AND GEN_SP.SERVICE_POINT_ID = SG.SERVICE_POINT_ID
    AND GEN_IDENT.EXTERNAL_SYSTEM_ID = 1500 -- EC.ES_TDIE
    AND GEN_IDENT.ENTITY_DOMAIN_ID = -210 -- EC.ED_SERVICE_POINT
    AND GEN_IDENT.IDENTIFIER_TYPE = 'Default'
    AND GEN_IDENT.ENTITY_ID = GEN_SP.SERVICE_POINT_ID
    AND SLM.METER_ID = MSG.METER_ID
    AND SLM.BEGIN_DATE <= NVL(MSG.END_DATE, HIGH_DATE)
    AND NVL(SLM.END_DATE, HIGH_DATE) >= MSG.BEGIN_DATE
    AND ASL.SERVICE_LOCATION_ID = SLM.SERVICE_LOCATION_ID
    AND ASL.BEGIN_DATE <= NVL(LEAST(NVL(MSG.END_DATE, HIGH_DATE), NVL(SLM.END_DATE, HIGH_DATE)), HIGH_DATE)
    AND NVL(ASL.END_DATE, HIGH_DATE) >= GREATEST(MSG.BEGIN_DATE, SLM.BEGIN_DATE)
    AND AESP.ACCOUNT_ID = ASL.ACCOUNT_ID
    AND AESP.BEGIN_DATE <= NVL(LEAST(NVL(MSG.END_DATE, HIGH_DATE), NVL(SLM.END_DATE, HIGH_DATE),
        NVL(ASL.END_DATE, HIGH_DATE)), HIGH_DATE)
    AND NVL(AESP.END_DATE, HIGH_DATE) >= GREATEST(MSG.BEGIN_DATE, SLM.BEGIN_DATE, ASL.BEGIN_DATE)
    AND ESP_IDENT.EXTERNAL_SYSTEM_ID = 1000 -- EC.ES_SEM
    AND ESP_IDENT.ENTITY_DOMAIN_ID = -110 -- EC.ED_ESP
    AND ESP_IDENT.IDENTIFIER_TYPE = 'Default'
    AND ESP_IDENT.ENTITY_ID = AESP.ESP_ID
    AND SU_IDENT.EXTERNAL_SYSTEM_ID = 1000 -- EC.ES_SEM
    AND SU_IDENT.ENTITY_DOMAIN_ID = -210 -- EC.ED_ESP
    AND SU_IDENT.IDENTIFIER_TYPE = 'Default'
    AND SU_IDENT.EXTERNAL_IDENTIFIER = ESP_IDENT.EXTERNAL_IDENTIFIER
    AND MP.POD_ID = SU_IDENT.ENTITY_ID;
