CREATE OR REPLACE PACKAGE MEX_NYISO IS
-- $Revision: 1.15 $

  TYPE PARAMETER_MAP IS TABLE OF VARCHAR2(512) INDEX BY VARCHAR2(512);

  -- CONSTANTS ---
  g_INTERFACE_SN CONSTANT VARCHAR2(8) := 'NYISO';
  g_NYISO_TIME_ZONE CONSTANT CHAR(3) := 'EDT';
  g_DATE_TIME_FMT CONSTANT VARCHAR2(21) := 'MM/DD/YYYY HH24:MI:SS';
  g_BASE_URL  VARCHAR2(40) := 'http://mis.nyiso.com/public/csv/';
  
  -- TYPES OF REQUESTS
  g_MEX_MARKET CONSTANT VARCHAR2(32) := 'nyiso';
  g_MEX_ACTION_BID_QUERY CONSTANT VARCHAR2(32) := 'QUERY';
  g_MEX_ACTION_BID_SUBMIT CONSTANT VARCHAR2(32) := 'SUBMIT';
  
  -- LBMP constants
  -- DAY AHEAD (DA)
  g_DA_LBMP_ZONAL CONSTANT VARCHAR2(64) := 'Zonal DA';
  g_DA_LBMP_GEN   CONSTANT VARCHAR2(64) := 'Generator DA';
  g_DA_LBMP_BUS   CONSTANT VARCHAR2(64) := 'Reference Bus DA';
  -- INTEGRATED REAL-TIME (IRT)
  g_INTEGRATED_RT_LBMP_ZONAL CONSTANT VARCHAR2(64) := 'Zonal RTI';
  g_INTEGRATED_RT_LBMP_GEN   CONSTANT VARCHAR2(64) := 'Generator RTI';
  g_INTEGRATED_RT_LBMP_BUS CONSTANT VARCHAR2(64) := 'Reference Bus RTI';
  -- BALANCING HOUR AHEAD (BHA)
  g_BHA_LBMP_ZONAL CONSTANT VARCHAR2(64) := 'Zonal BHA';
  g_BHA_LBMP_GEN   CONSTANT VARCHAR2(64) := 'Generator BHA';
  g_BHA_LBMP_BUS CONSTANT VARCHAR2(64) := 'Reference Bus BHA';
  -- LOAD constants
  g_ISO_LOAD CONSTANT VARCHAR2(64) := 'ISO Load';
  g_RT_ACTUAL_LOAD CONSTANT VARCHAR2(64) := 'Real Time Load';
  g_INTEGRATED_RT_ACTUAL_LOAD CONSTANT VARCHAR2(64) := 'Integrated Real Time Load';	
  -- TC constants
  g_ATC_TTC CONSTANT VARCHAR2(64) := 'ATC TTC';

FUNCTION WHAT_VERSION RETURN VARCHAR2;

	FUNCTION FROM_CUT_TO_STRING
  	(
  	p_DATE        IN DATE,
  	p_TIME_ZONE   IN VARCHAR2,
    p_DATE_FORMAT IN VARCHAR2,
	p_INTERVAL_MINUTES IN NUMBER := 60
  	)
  	RETURN VARCHAR2;

    FUNCTION TO_CUT_FROM_STRING
  	(
  	p_DATE        IN VARCHAR2,
  	p_TIME_ZONE   IN VARCHAR2,
    p_DATE_FORMAT IN VARCHAR2,
	p_INTERVAL_MINUTES IN NUMBER := 60
  	)
  	RETURN DATE;

	PROCEDURE BUILD_PUBLIC_URL
	(
    p_DATE         IN DATE,
    p_IS_ZIP_FILE  IN BOOLEAN,
    p_REQUEST_TYPE IN VARCHAR2,
    p_REQUEST_URL  OUT VARCHAR2,
    p_STATUS       OUT NUMBER,
    p_LOGGER       IN OUT NOCOPY mm_logger_adapter
	);

END MEX_NYISO;
/