CREATE OR REPLACE TYPE ACCOUNT_CALENDAR_SYNC_TYPE AS OBJECT
(
--Revision: $Revision: 1.16 $
  ACCOUNT_IDENTIFIER VARCHAR2(64),
  CALENDAR_NAME VARCHAR2(32),
  CALENDAR_TYPE VARCHAR2(16),
  BEGIN_DATE DATE,
  END_DATE DATE
);
/

CREATE OR REPLACE TYPE ACCOUNT_CALENDAR_SYNC_TABLE IS TABLE OF ACCOUNT_CALENDAR_SYNC_TYPE;
/
