CREATE OR REPLACE TYPE CAPACITY_RELEASE_TYPE AS OBJECT
	(
--Revision: $Revision: 1.12 $
	CITY_GATE_NAME VARCHAR(32),
	CITY_GATE_ID NUMBER(9),
	BEGIN_DATE DATE,
	END_DATE DATE,
	POD_CAPACITY NUMBER(14,3),
	POR_CAPACITY NUMBER(14,3)
	);
/

CREATE OR REPLACE TYPE CAPACITY_RELEASE_TABLE IS TABLE OF CAPACITY_RELEASE_TYPE;
/
