CREATE OR REPLACE TYPE CHARGE_COMPONENT_TYPE AS OBJECT 
	( 
--Revision: $Revision: 1.26 $
	PRODUCT_ID NUMBER(9), 
	COMPONENT_ID NUMBER(9), 
	ACCOUNT_SERVICE_ID NUMBER(9), 
	CUSTOMER_ID NUMBER(9), 
	PERIOD_ID NUMBER(9), 
	CHARGE_TYPE CHAR(1), 
	BEGIN_DATE DATE, 
	END_DATE DATE,
	BILL_CYCLE_MONTH DATE,
	QUANTITY NUMBER(14,4), 
	RATE NUMBER(18,6), 
	AMOUNT NUMBER(14,4), 
	FACTOR NUMBER(14,4),
	PLANNED NUMBER(14,4),
	ACTUAL NUMBER(14,4),
	BAND_NUMBER NUMBER(2),
	BILL_CODE CHAR(1)
	);
/

CREATE OR REPLACE TYPE CHARGE_COMPONENT_TABLE IS TABLE OF CHARGE_COMPONENT_TYPE;
/
