CREATE OR REPLACE TYPE DETERMINANT_TYPE AS OBJECT
(
--Revision: $Revision: 1.30 $
  PERIOD_ID NUMBER(9),
  BEGIN_DATE DATE,
  END_DATE DATE,
  BILL_CYCLE_MONTH DATE,
  DETERMINANT_1 NUMBER(16,4),
  DETERMINANT_2 NUMBER(16,4),
  ENROLLMENT NUMBER(8),
  BILL_CODE CHAR(1),
  ACCOUNT_SERVICE_ID NUMBER(9),
  CONSUMPTION_ID NUMBER(9),
  CUSTOMER_ID NUMBER(9),
  MEMBER FUNCTION DAY_DATE RETURN DATE,
  MEMBER FUNCTION ADQ RETURN NUMBER,
  MEMBER FUNCTION ENERGY RETURN NUMBER,
  MEMBER FUNCTION DEMAND RETURN NUMBER,
  MEMBER FUNCTION CONSUMPTION RETURN NUMBER,
  MEMBER FUNCTION IMBALANCE RETURN NUMBER,
  MEMBER FUNCTION ACTUAL RETURN NUMBER,
  MEMBER FUNCTION PLAN RETURN NUMBER,
  MEMBER FUNCTION EQUAL(p_DETERMINANT IN DETERMINANT_TYPE) RETURN BOOLEAN,
  MEMBER PROCEDURE COERCE_TO_MONTHLY_CONSUMPTION,
  MEMBER PROCEDURE COERCE_TO_MONTH,
  MEMBER PROCEDURE ENERGY (p_ENERGY IN NUMBER),
  MEMBER PROCEDURE DEMAND (p_DEMAND IN NUMBER),
  MEMBER PROCEDURE PLAN (p_PLAN IN NUMBER),
  MEMBER PROCEDURE ACTUAL (p_ACTUAL IN NUMBER)
);
/

CREATE OR REPLACE TYPE BODY DETERMINANT_TYPE AS
MEMBER FUNCTION DAY_DATE RETURN DATE IS
BEGIN
	RETURN BEGIN_DATE;
END DAY_DATE;
MEMBER FUNCTION ADQ RETURN NUMBER IS
v_DAYS NUMBER(8);
BEGIN
	v_DAYS := END_DATE - BEGIN_DATE + 1;
	IF v_DAYS <= 0 THEN
		v_DAYS := 1;
	END IF;
	RETURN DETERMINANT_1 / v_DAYS;
END ADQ;
MEMBER FUNCTION ENERGY RETURN NUMBER IS
BEGIN
	RETURN DETERMINANT_1;
END ENERGY;
MEMBER FUNCTION DEMAND RETURN NUMBER IS
BEGIN
	RETURN DETERMINANT_2;
END DEMAND;
MEMBER FUNCTION CONSUMPTION RETURN NUMBER IS
BEGIN
	RETURN DETERMINANT_1;
END CONSUMPTION ;
MEMBER FUNCTION IMBALANCE RETURN NUMBER IS
BEGIN
	RETURN DETERMINANT_2 - DETERMINANT_1;
END IMBALANCE;
MEMBER FUNCTION ACTUAL RETURN NUMBER IS
BEGIN
	RETURN DETERMINANT_1;
END ACTUAL;
MEMBER FUNCTION PLAN RETURN NUMBER IS
BEGIN
	RETURN DETERMINANT_2;
END PLAN;
MEMBER FUNCTION EQUAL(p_DETERMINANT IN DETERMINANT_TYPE) RETURN BOOLEAN IS
BEGIN
	RETURN PERIOD_ID = p_DETERMINANT.PERIOD_ID AND BEGIN_DATE = p_DETERMINANT.BEGIN_DATE AND END_DATE = p_DETERMINANT.END_DATE AND ACCOUNT_SERVICE_ID = p_DETERMINANT.ACCOUNT_SERVICE_ID;
END EQUAL;
MEMBER PROCEDURE COERCE_TO_MONTHLY_CONSUMPTION AS
v_DAYS NUMBER(8);
v_ADQ NUMBER;
BEGIN
	v_DAYS := END_DATE - BEGIN_DATE + 1;
	IF v_DAYS <= 0 THEN
		v_DAYS := 1;
	END IF;
	v_ADQ := DETERMINANT_1 / v_DAYS;
	BEGIN_DATE := TRUNC(END_DATE,'MONTH');
	END_DATE := LAST_DAY(END_DATE);
	DETERMINANT_1 := v_ADQ * (END_DATE - BEGIN_DATE + 1);
	DETERMINANT_2 := DETERMINANT_1;
END COERCE_TO_MONTHLY_CONSUMPTION;
MEMBER PROCEDURE COERCE_TO_MONTH AS
BEGIN
	BEGIN_DATE := TRUNC(END_DATE,'MONTH');
	END_DATE := LAST_DAY(END_DATE);
END COERCE_TO_MONTH;
MEMBER PROCEDURE ENERGY (p_ENERGY IN NUMBER) AS
BEGIN
	DETERMINANT_1 := p_ENERGY;
END ENERGY;
MEMBER PROCEDURE DEMAND (p_DEMAND IN NUMBER) AS
BEGIN
	DETERMINANT_2 := p_DEMAND;
END DEMAND;
MEMBER PROCEDURE PLAN (p_PLAN IN NUMBER) AS
BEGIN
	DETERMINANT_2 := p_PLAN;
END PLAN;
MEMBER PROCEDURE ACTUAL (p_ACTUAL IN NUMBER) AS
BEGIN
	DETERMINANT_1 := p_ACTUAL;
END ACTUAL;
END;
/

CREATE OR REPLACE TYPE DETERMINANT_TABLE IS TABLE OF DETERMINANT_TYPE;
/
