CREATE OR REPLACE TYPE LOSS_FACTOR_PATTERN_TYPE AS OBJECT
	(
--Revision: $Revision: 1.13 $
	PATTERN_ID NUMBER(9),
	PATTERN_DATE DATE,
	PATTERN_VAL NUMBER(8,6)
	);
/

CREATE OR REPLACE TYPE LOSS_FACTOR_PATTERN_TABLE IS TABLE OF LOSS_FACTOR_PATTERN_TYPE;
/
