CREATE OR REPLACE TYPE MM_LOGGER_ADAPTER UNDER MEX_LOGGER
(
	EXTERNAL_SYSTEM_ID		NUMBER(9),
	EXTERNAL_SYSTEM_NAME	VARCHAR2(64),
	EXTERNAL_ACCOUNT_NAME	VARCHAR2(64),
	PROCESS_NAME			VARCHAR2(64),
	EXCHANGE_NAME			VARCHAR2(64),
	TRACE_ON				NUMBER(1),
	LOG_TYPE				NUMBER(1),
	EXCHANGE_IS_ACTIVE		NUMBER(1),
	MEX_MARKET				VARCHAR2(64),
	MEX_ACTION				VARCHAR2(64),
	LAST_EVENT_ID		    NUMBER(18),
	PROCESS_STARTED			NUMBER(1),
	FINISH_MESSAGE			VARCHAR2(4000),
-- functions for examining the LOG_TYPE field
MEMBER FUNCTION IS_LOGGING RETURN BOOLEAN,
MEMBER FUNCTION IS_LOGGING_EVENTS RETURN BOOLEAN,
MEMBER FUNCTION IS_LOGGING_EXCHANGES RETURN BOOLEAN,
-- Override all methods to actually perform logging.
MEMBER PROCEDURE LOG_START,
OVERRIDING MEMBER PROCEDURE LOG_START ( p_MARKET IN VARCHAR2, p_ACTION IN VARCHAR2 ),
OVERRIDING MEMBER PROCEDURE LOG_ERROR ( p_MESSAGE IN VARCHAR2 ),
OVERRIDING MEMBER PROCEDURE LOG_WARN ( p_MESSAGE IN VARCHAR2 ),
OVERRIDING MEMBER PROCEDURE LOG_INFO ( p_MESSAGE IN VARCHAR2 ),
OVERRIDING MEMBER PROCEDURE LOG_REQUEST ( p_REQUEST_HEADERS IN CLOB ,
										  p_REQUEST_BODY IN CLOB ,
										  p_BODY_CONTENT_TYPE IN VARCHAR2 ),
OVERRIDING MEMBER PROCEDURE LOG_RESPONSE ( p_RESPONSE_HEADERS IN CLOB ,
										   p_RESPONSE_BODY IN CLOB ,
										   p_BODY_CONTENT_TYPE IN VARCHAR2 ),
OVERRIDING MEMBER PROCEDURE LOG_ATTACHMENT ( p_DESCRIPTION IN VARCHAR2,
                                             p_ATTACHMENT_TYPE IN VARCHAR2,
                                             p_ATTACHMENT IN CLOB ),
OVERRIDING MEMBER PROCEDURE LOG_DEBUG ( p_MESSAGE IN VARCHAR2 ),
OVERRIDING MEMBER PROCEDURE LOG_STOP ( p_RESULT IN MEX_RESULT ),
MEMBER PROCEDURE LOG_STOP ( p_STATUS IN NUMBER, p_MESSAGE IN VARCHAR2 ),
MEMBER FUNCTION GET_END_MESSAGE RETURN VARCHAR2,
MEMBER PROCEDURE LOG_EXCHANGE_ERROR (p_EXCHANGE_ERROR IN VARCHAR2),
MEMBER PROCEDURE LOG_EXCHANGE_IDENTIFIER (p_EXCHANGE_IDENTIFIER IN VARCHAR2),
-- constructor
CONSTRUCTOR FUNCTION MM_LOGGER_ADAPTER ( p_EXTERNAL_SYSTEM_ID IN NUMBER,
										 p_EXTERNAL_ACCOUNT_NAME IN VARCHAR2,
										 p_PROCESS_NAME IN VARCHAR2,
										 p_EXCHANGE_NAME IN VARCHAR2,
										 p_LOG_TYPE IN NUMBER := 3,
										 p_TRACE_ON IN NUMBER := 0
									   ) RETURN SELF AS RESULT
)
NOT FINAL;
/
