CREATE OR REPLACE TYPE PRICE_QUANTITY_SUMMARY_TYPE AS OBJECT 
( 
--Revision: $Revision: 1.13 $
  PRICE NUMBER, 
  SCHEDULE_DATE DATE, 
  QUANTITY NUMBER 
);
/

CREATE OR REPLACE TYPE PRICE_QUANTITY_SUMMARY_TABLE IS TABLE OF PRICE_QUANTITY_SUMMARY_TYPE;
/
