CREATE OR REPLACE TYPE SERVICE_SYNC_TYPE AS OBJECT
(
--Revision: $Revision: 1.17 $
  ACCOUNT_IDENTIFIER VARCHAR2(64),
  ESP_IDENTIFIER VARCHAR2(64),
  BEGIN_DATE DATE,
  END_DATE DATE,
  SERVICE_ACCOUNTS NUMBER(8),
  USAGE_FACTOR NUMBER(12,6)
);
/

CREATE OR REPLACE TYPE SERVICE_SYNC_TABLE IS TABLE OF SERVICE_SYNC_TYPE;
/
