CREATE OR REPLACE TYPE SERVICE_OBLIGATION_TYPE AS OBJECT
(
--Revision: $Revision: 1.13 $
  PROVIDER_SERVICE_ID NUMBER(9),
  SERVICE_DELIVERY_ID NUMBER(9),
  SERVICE_OBLIGATION_ID NUMBER(9)
);
/

CREATE OR REPLACE TYPE SERVICE_OBLIGATION_TABLE IS TABLE OF SERVICE_OBLIGATION_TYPE;
/
