CREATE OR REPLACE TYPE STATION_PARAMETER_SYNC_TYPE AS OBJECT
(
--Revision: $Revision: 1.15 $
  STATION_NAME VARCHAR(32),
  PARAMETER_NAME VARCHAR(32),
  PARAMETER_CODE CHAR(1),
  PARAMETER_DATE DATE,
  PARAMETER_VAL NUMBER
);
/

CREATE OR REPLACE TYPE STATION_PARAMETER_SYNC_TABLE IS TABLE OF STATION_PARAMETER_SYNC_TYPE;
/
