CREATE OR REPLACE TYPE STORED_PROC_PARAMETER_TYPE AS OBJECT
(
--Revision: $Revision: 1.2 $
	PARAMETER_NAME VARCHAR2(30),
	PARAMETER_DIRECTION VARCHAR2(9),
	PARAMETER_TYPE VARCHAR2(30),
	PARAMETER_SUB_TYPE VARCHAR2(30),
	POSITION NUMBER
);
/
CREATE OR REPLACE TYPE STORED_PROC_PARAMETER_TABLE IS TABLE OF STORED_PROC_PARAMETER_TYPE;
/
