CREATE OR REPLACE TYPE TIERED_RATE_TYPE AS OBJECT
(
--Revision: $Revision: 1.16 $
  BLOCK_MIN NUMBER(14,4),
  BLOCK_MAX NUMBER(14,4),
  CHARGE_MIN NUMBER(14,4),
  RATE NUMBER(16,6)
);
/

CREATE OR REPLACE TYPE TIERED_RATE_TABLE IS TABLE OF TIERED_RATE_TYPE;
/
