CREATE OR REPLACE TYPE WRF_SEASON_BREAKPOINT_TYPE AS OBJECT
	(
--Revision: $Revision: 1.15 $
	TEMPLATE_NAME VARCHAR(32),
	TEMPLATE_ID NUMBER(9),
	SEASON_ID NUMBER(9),
	BREAKPOINT_ID NUMBER(9),
	PARAMETER_ID NUMBER(9),
	SEASON_BEGIN_DATE DATE,
	SEASON_END_DATE DATE,
	BREAKPOINT_HOUR NUMBER(2),
	BREAKPOINT_1 NUMBER(8,2),
	BREAKPOINT_2 NUMBER(8,2),
	BREAKPOINT_3 NUMBER(8,2),
	BREAKPOINT_4 NUMBER(8,2),
	LINE_SEGMENTS NUMBER(1)
	);
/

CREATE OR REPLACE TYPE WRF_SEASON_BREAKPOINT_TABLE IS TABLE OF WRF_SEASON_BREAKPOINT_TYPE;
/
