CREATE OR REPLACE PACKAGE MM_NYISO_BIDPOST IS
-- $Revision: 1.27 $

  -- Author  : VGODYN
  -- Created : 11/9/2005 2:48:54 PM
  -- Purpose : Submit and Query Bids

FUNCTION WHAT_VERSION RETURN VARCHAR2;

PROCEDURE MARKET_EXCHANGE
	(
	p_BEGIN_DATE     IN DATE,
	p_END_DATE       IN DATE,
	p_EXCHANGE_TYPE  IN VARCHAR2,
	p_LOG_TYPE 		 IN NUMBER,
	p_TRACE_ON 		 IN NUMBER,
	p_STATUS         OUT NUMBER,
	p_MESSAGE        OUT VARCHAR2);

PROCEDURE MARKET_SUBMIT
	(
	   p_BEGIN_DATE      IN DATE,
       p_END_DATE        IN DATE,
       p_EXCHANGE_TYPE   IN VARCHAR2,
       p_ENTITY_LIST 	 IN VARCHAR2,
       p_ENTITY_LIST_DELIMITER IN CHAR,
       p_SUBMIT_HOURS    IN VARCHAR2,
       p_TIME_ZONE       IN VARCHAR2,
	   p_LOG_TYPE		 IN NUMBER,
	   p_TRACE_ON		 IN NUMBER,
       p_STATUS          OUT NUMBER,
       p_MESSAGE         OUT VARCHAR2);

PROCEDURE GET_TRAITS_FOR_TRANSACTION
(
	p_TRANSACTION_ID IN NUMBER,
	p_REPORT_TYPE IN VARCHAR2,
	p_TRAIT_GROUP_FILTER IN VARCHAR2,
	p_INTERVAL IN VARCHAR2,
	p_WORK_ID OUT NUMBER
);

END MM_NYISO_BIDPOST;
/