DECLARE
	v_USER_ROLE_ID  NUMBER(9);
	v_PUSER_ROLE_ID NUMBER (9);

	PROCEDURE INSERT_SYSTEM_ACTION
		(
		p_MKT_APP IN VARCHAR2,          -- 'LBMP'
		p_IS_BID_OFFER IN BOOLEAN,      --  FALSE for Data Exchange / TRUE for Bid Offer     
		p_ACTION_NAME IN VARCHAR2,      -- 'Query Price Nodes'
		p_EXCHANGE_TYPE IN VARCHAR2,    -- 'MM_NYISO_LBMP.MARKET_EXCHANGE;EXCHANGE_TYPE="Query Price Nodes"'
		p_ENTITY_LIST IN VARCHAR2 := NULL
		) AS

	v_MODULE 		VARCHAR2(64) := 'Scheduling';
	v_DISPLAY_NAME 	VARCHAR2(256);
	v_SYS_ACTION_NAME VARCHAR2(256);
	v_ID 			NUMBER;
	v_ACTION_TYPE 	VARCHAR2(32);
	v_ENTITY_LIST 	VARCHAR2(256);
	v_DO_SECURITY 	NUMBER := 0;
	v_STATUS		NUMBER;

	BEGIN    
		-- Display Name
		IF p_MKT_APP IS NULL THEN
			v_DISPLAY_NAME := 'NY:'||p_ACTION_NAME;			
		ELSE
			v_DISPLAY_NAME := 'NY:'||p_MKT_APP||':'||p_ACTION_NAME;
		END IF;
		v_SYS_ACTION_NAME := 'Sched:' || v_DISPLAY_NAME;
		
		-- Action Type
		IF p_IS_BID_OFFER THEN
		  v_ACTION_TYPE := 'Bid Offer';
		ELSE
		  v_ACTION_TYPE := 'Data Exchange';
		END IF;

				
		v_ID := ID.ID_FOR_SYSTEM_ACTION(v_DISPLAY_NAME);
		v_DO_SECURITY := 0;
		IF v_ID <= 0 THEN 
			v_ID := 0;  
			v_DO_SECURITY := 1;
		END IF;
        
		--add the system action
		IO.PUT_SYSTEM_ACTION(v_ID, v_SYS_ACTION_NAME, SUBSTR(v_SYS_ACTION_NAME,1,32), v_SYS_ACTION_NAME, v_ID, NULL, v_MODULE, v_ACTION_TYPE,
					         v_DISPLAY_NAME, NULL, NULL, p_EXCHANGE_TYPE, NULL, NULL, NULL, p_ENTITY_LIST);
                
		--add the 'User' and 'Power-User' roles to it
		IF v_DO_SECURITY = 1 THEN
			EM.PUT_SYSTEM_ACTION_ROLE(v_ID, v_USER_ROLE_ID, 1, 0, 0, 0, 0, v_STATUS);
			EM.PUT_SYSTEM_ACTION_ROLE(v_ID, v_PUSER_ROLE_ID, 1, 0, 0, 0, 0, v_STATUS);
		END IF;

        
	END INSERT_SYSTEM_ACTION;
BEGIN
    SELECT ROLE_ID INTO v_USER_ROLE_ID FROM APPLICATION_ROLE WHERE ROLE_NAME = 'User';
    SELECT ROLE_ID INTO v_PUSER_ROLE_ID FROM APPLICATION_ROLE WHERE ROLE_NAME = 'Power-User';

	-- Price Nodes
	INSERT_SYSTEM_ACTION('LBMP', FALSE,'Query Price Nodes','MM_NYISO_LBMP.MARKET_EXCHANGE;EXCHANGE_TYPE="Query Price Nodes"',NULL);

	-- LMPs
	INSERT_SYSTEM_ACTION('LBMP', FALSE,'Query DA','MM_NYISO_LBMP.MARKET_EXCHANGE;EXCHANGE_TYPE="Query DA LBMP"',NULL);	
	INSERT_SYSTEM_ACTION('LBMP', FALSE,'Query RT','MM_NYISO_LBMP.MARKET_EXCHANGE;EXCHANGE_TYPE="Query RT LBMP"',NULL);
	INSERT_SYSTEM_ACTION('LBMP', FALSE,'Query RTI','MM_NYISO_LBMP.MARKET_EXCHANGE;EXCHANGE_TYPE="Query RTI LBMP"',NULL);
	INSERT_SYSTEM_ACTION('LBMP', FALSE,'Query Archive LBMP','MM_NYISO_LBMP.MARKET_EXCHANGE;EXCHANGE_TYPE="Query Archive LBMP"','MM_NYISO_LBMP.GET_ENTITY_LIST_FOR_LBMP');
	INSERT_SYSTEM_ACTION('TC', FALSE,'QUERY ATC TTC','MM_NYISO_TC.MARKET_EXCHANGE;EXCHANGE_TYPE="QUERY ATC TTC"',NULL);

	-- Load
	INSERT_SYSTEM_ACTION('LOAD', FALSE,'ISO Load','MM_NYISO_LOAD.MARKET_EXCHANGE;EXCHANGE_TYPE="ISO Load"',NULL);
	INSERT_SYSTEM_ACTION('LOAD', FALSE,'Real Time Load','MM_NYISO_LOAD.MARKET_EXCHANGE;EXCHANGE_TYPE="Real Time Load"',NULL);
	INSERT_SYSTEM_ACTION('LOAD', FALSE,'Integrated Real Time Load','MM_NYISO_LOAD.MARKET_EXCHANGE;EXCHANGE_TYPE="Integrated Real Time Load"',NULL);
END;
/
