DECLARE
	PROCEDURE ADD_STATUS
		(
		p_STATUS_NAME IN VARCHAR2,
		p_IS_ACTIVE IN NUMBER
		) AS
	BEGIN
		INSERT INTO INTERCHANGE_TRANSACTION_STATUS (TRANSACTION_STATUS_NAME,TRANSACTION_IS_ACTIVE) 
		VALUES (p_STATUS_NAME, p_IS_ACTIVE);
	EXCEPTION WHEN OTHERS THEN 
		NULL;
	END ADD_STATUS;
BEGIN
	ADD_STATUS('Active',1);
	ADD_STATUS('Inactive',0);
	ADD_STATUS('Pending',1);
	ADD_STATUS('Approved',1);
	ADD_STATUS('Rejected',0);	
	COMMIT;
END;
/
