CREATE OR REPLACE PACKAGE MM_MISO_SETTLEMENT AS

-- MISO-specific Market Manager Settlement procedures

TYPE REF_CURSOR IS REF CURSOR;

FUNCTION WHAT_VERSION RETURN VARCHAR;

FUNCTION GET_SP_ID
	(
    p_SERVICE_POINT_ID IN NUMBER,
    p_SERVICE_POINT_XID IN VARCHAR2
    ) RETURN NUMBER;

PROCEDURE PUT_SETTLEMENT_STATEMENT
	(
	p_ISO_SOURCE IN VARCHAR2,
	p_STATEMENT_NAME IN VARCHAR2,
	p_MARKET_ABBR IN VARCHAR2,
	p_STATEMENT_XML IN XMLTYPE,
	p_TRACE_ON IN NUMBER,
	p_ERROR_MESSAGE OUT VARCHAR2
	);

PROCEDURE DUMP_DETS_TO_WORK
	(
	p_WORK_ID IN NUMBER,
	p_STATEMENT IN XMLTYPE
	);

PROCEDURE IMPORT_STATEMENT_CLOB
	(
	p_FILE_PATH IN VARCHAR2,
	p_IMPORT_FILE IN OUT NOCOPY CLOB,
	p_LOG_TYPE IN NUMBER,
	p_TRACE_ON IN NUMBER,
	p_STATUS OUT NUMBER,
	p_MESSAGE OUT VARCHAR2
	);

g_DATE_FORMAT CONSTANT VARCHAR2(16) := 'MM/DD/YYYY';

g_MISO_NAMESPACE CONSTANT VARCHAR2(64) := NULL;
g_MISO_NAMESPACE_NAME CONSTANT VARCHAR2(64) := 'http://markets.midwestiso.org/dart/xml';
g_MISO_TIMEZONE CONSTANT CHAR(3) := 'EST';

g_NOT_ASSIGNED CONSTANT NUMBER(1) := 0;

g_AO_DET VARCHAR2(8) := 'AO';
g_AO_INTERVAL_DET VARCHAR2(8) := 'AOI';
g_ASSET_DET VARCHAR2(8) := 'AS';
g_ASSET_INTERVAL_DET VARCHAR2(8) := 'ASI';
g_MKT_DET VARCHAR2(8) := 'MKT';
g_MKT_INTERVAL_DET VARCHAR2(8) := 'MKTI';

g_AO_OR_ASSET VARCHAR2(8) := 'A_I';

END MM_MISO_SETTLEMENT;
/