CREATE OR REPLACE PROCEDURE BEGIN_END_START_STOP_RANGE
	(
	p_OLD_BEGIN_DATE IN DATE,
	p_NEW_BEGIN_DATE IN DATE,
	p_OLD_END_DATE IN DATE,
	p_NEW_END_DATE IN DATE,
	p_BEGIN_START_DATE IN OUT DATE,
	p_BEGIN_STOP_DATE IN OUT DATE,
	p_END_START_DATE IN OUT DATE,
	p_END_STOP_DATE IN OUT DATE
	) AS
--Revision: $Revision: 1.14 $

-- Determine the Begin and End Date Start and Stop Ranges reflecting the Specified date modifications.

BEGIN

	IF p_NEW_BEGIN_DATE > p_OLD_BEGIN_DATE THEN
		p_BEGIN_START_DATE := p_OLD_BEGIN_DATE;
		p_BEGIN_STOP_DATE  := p_NEW_BEGIN_DATE - 1;
	ELSE
		p_BEGIN_START_DATE := p_NEW_BEGIN_DATE;
		p_BEGIN_STOP_DATE  := p_OLD_BEGIN_DATE - 1;
	END IF;

	IF NVL(p_NEW_END_DATE,HIGH_DATE) < NVL(p_OLD_END_DATE,HIGH_DATE) THEN
		p_END_START_DATE := NVL(p_NEW_END_DATE + 1, HIGH_DATE);
		p_END_STOP_DATE := NVL(p_OLD_END_DATE, HIGH_DATE);
	ELSE
		p_END_START_DATE := NVL(p_OLD_END_DATE + 1, HIGH_DATE);
		p_END_STOP_DATE := NVL(p_NEW_END_DATE, HIGH_DATE);
	END IF;

END BEGIN_END_START_STOP_RANGE;
/

