CREATE OR REPLACE PROCEDURE NUM_DAY_TYPES_IN_MONTH
	(
	p_MONTH IN DATE,
	p_WEEKDAY_DAYS OUT NUMBER,
	p_WEEKEND_DAYS OUT NUMBER
	) AS
--Revision: $Revision: 1.7 $

v_DATE DATE := TRUNC(p_MONTH,'MM');
BEGIN

	p_WEEKDAY_DAYS := WEEK_DAYS_IN_RANGE(v_DATE, LAST_DAY(v_DATE));
	p_WEEKEND_DAYS := LAST_DAY(v_DATE) - v_DATE - p_WEEKDAY_DAYS + 1;

	EXCEPTION
		WHEN OTHERS THEN
			RAISE;

END NUM_DAY_TYPES_IN_MONTH;
/

