CREATE OR REPLACE PACKAGE MM_ERCOT_LMP IS
-- $Revision: 1.9 $

  -- Author  : LDUMITRIU
  -- Created : 5/2/2006 4:25:30 PM
  -- Purpose :

FUNCTION WHAT_VERSION RETURN VARCHAR2;

PROCEDURE MARKET_EXCHANGE
	(
	p_BEGIN_DATE            	IN DATE,
	p_END_DATE              	IN DATE,
	p_EXCHANGE_TYPE  			IN VARCHAR2,
	p_ENTITY_LIST           	IN VARCHAR2,
	p_ENTITY_LIST_DELIMITER 	IN CHAR,
	p_LOG_ONLY					IN NUMBER :=0,
	p_LOG_TYPE 					IN NUMBER,
	p_TRACE_ON 					IN NUMBER,
	p_STATUS                	OUT NUMBER,
	p_MESSAGE               	OUT VARCHAR2);

g_ET_QUERY_MRKT_CLRING_PRICES  CONSTANT VARCHAR2(60) := 'Query Market Clearing Prices';
g_ET_QUERY_ANC_SERVICE_PRICES  CONSTANT VARCHAR2(60) := 'Query Ancillary Service Prices';

END MM_ERCOT_LMP;
/