CREATE OR REPLACE VIEW ACCOUNT_SERVICE_LOCATION_INFO ( ACCOUNT_ID, 
SERVICE_LOCATION_ID, BEGIN_DATE, END_DATE, EDC_IDENTIFIER, 
ESP_IDENTIFIER, ENTRY_DATE, SERVICE_LOCATION_NAME ) AS SELECT A.ACCOUNT_ID, A.SERVICE_LOCATION_ID, A.BEGIN_DATE, A.END_DATE, 
A.EDC_IDENTIFIER, A.ESP_IDENTIFIER, A.ENTRY_DATE, S.SERVICE_LOCATION_NAME 
FROM ACCOUNT_SERVICE_LOCATION A, SERVICE_LOCATION S 
WHERE A.SERVICE_LOCATION_ID = S.SERVICE_LOCATION_ID;

