CREATE OR REPLACE VIEW ACCOUNT_ANCILLARY_SERVICE_INFO ( ACCOUNT_ID, 
ANCILLARY_SERVICE_ID, BEGIN_DATE, END_DATE, SERVICE_VAL, 
ENTRY_DATE, ANCILLARY_SERVICE_NAME ) AS 
SELECT M.ACCOUNT_ID, M.ANCILLARY_SERVICE_ID, M.BEGIN_DATE, M.END_DATE,
	M.SERVICE_VAL, M.ENTRY_DATE, A.ANCILLARY_SERVICE_NAME
FROM ACCOUNT_ANCILLARY_SERVICE M, ANCILLARY_SERVICE A
WHERE M.ANCILLARY_SERVICE_ID = A.ANCILLARY_SERVICE_ID;
