CREATE OR REPLACE VIEW ACCOUNT_SERVICE_PROVIDER ( ACCOUNT_SERVICE_ID, 
	EDC_ID, EDC_BEGIN_DATE, EDC_END_DATE, ESP_ID, 
	POOL_ID, ESP_BEGIN_DATE, ESP_END_DATE, PSE_ID, 
	PSE_BEGIN_DATE, PSE_END_DATE, PROVIDER_SERVICE_ID ) AS
SELECT A.ACCOUNT_SERVICE_ID "ACCOUNT_SERVICE_ID",
		B.EDC_ID "EDC_ID",
		B.BEGIN_DATE "EDC_BEGIN_DATE",
		B.END_DATE "EDC_END_DATE",
		C.ESP_ID "ESP_ID",
		C.POOL_ID "POOL_ID",
		C.BEGIN_DATE "ESP_BEGIN_DATE",
		C.END_DATE "ESP_END_DATE",
		D.PSE_ID "PSE_ID",
		D.BEGIN_DATE "PSE_BEGIN_DATE",
		D.END_DATE "PSE_END_DATE",
		E.PROVIDER_SERVICE_ID "PROVIDER_SERVICE_ID"
	FROM ACCOUNT_SERVICE A,
		ACCOUNT_EDC B,
		ACCOUNT_ESP C,
		PSE_ESP D,
		PROVIDER_SERVICE E
	WHERE A.AGGREGATE_ID = 0
		AND B.ACCOUNT_ID = A.ACCOUNT_ID
		AND C.ACCOUNT_ID = A.ACCOUNT_ID
		AND D.ESP_ID = C.ESP_ID
		AND E.EDC_ID = B.EDC_ID
		AND E.ESP_ID = C.ESP_ID
		AND E.PSE_ID = D.PSE_ID
	UNION SELECT A.ACCOUNT_SERVICE_ID "ACCOUNT_SERVICE_ID",
		B.EDC_ID "EDC_ID",
		B.BEGIN_DATE "EDC_BEGIN_DATE",
		B.END_DATE "EDC_END_DATE",
		C.ESP_ID "ESP_ID",
		C.POOL_ID "POOL_ID",
		C.BEGIN_DATE "ESP_BEGIN_DATE",
		C.END_DATE "ESP_END_DATE",
		D.PSE_ID "PSE_ID",
		D.BEGIN_DATE "PSE_BEGIN_DATE",
		D.END_DATE "PSE_END_DATE",
		E.PROVIDER_SERVICE_ID "PROVIDER_SERVICE_ID"
	FROM ACCOUNT_SERVICE A,
		ACCOUNT_EDC B,
		AGGREGATE_ACCOUNT_ESP C,
		PSE_ESP D,
		PROVIDER_SERVICE E
	WHERE NOT A.AGGREGATE_ID = 0
		AND B.ACCOUNT_ID = A.ACCOUNT_ID
		AND C.ACCOUNT_ID = A.ACCOUNT_ID
		AND D.ESP_ID = C.ESP_ID
		AND E.EDC_ID = B.EDC_ID
		AND E.ESP_ID = C.ESP_ID
		AND E.PSE_ID = D.PSE_ID;
/
