CREATE OR REPLACE VIEW ACCOUNT_METER_BILLED_USAGE ( ACCOUNT, 
ACCOUNT_ID, SERVICE_LOCATION, SERVICE_LOCATION_ID, METER, 
METER_ID, METER_STATUS, METER_TYPE, BEGIN_DATE, 
END_DATE, BILLED_USAGE, METERED_USAGE, DELTA, 
ENTRY_DATE ) AS 
SELECT A.ACCOUNT_NAME "ACCOUNT",
	A.ACCOUNT_ID,
	C.SERVICE_LOCATION_NAME "SERVICE_LOCATION",
	C.SERVICE_LOCATION_ID,
	E.METER_NAME "METER",
	E.METER_ID,
	E.METER_STATUS,
	E.METER_TYPE,
	F.BEGIN_DATE,
	F.END_DATE,
	F.BILLED_USAGE,
	NVL(F.METERED_USAGE,0) "METERED_USAGE",
	NVL(F.BILLED_USAGE-F.METERED_USAGE,0) "DELTA",
	F.ENTRY_DATE
FROM RETAIL_ACCOUNT A,
	ACCOUNT_SERVICE_LOCATION B,
	SERVICE_LOCATION C,
	SERVICE_LOCATION_METER D,
	METER E,
	METER_BILLED_USAGE F
WHERE A.ACCOUNT_ID = B.ACCOUNT_ID
	AND B.SERVICE_LOCATION_ID = C.SERVICE_LOCATION_ID
	AND C.SERVICE_LOCATION_ID = D.SERVICE_LOCATION_ID
	AND D.METER_ID = E.METER_ID
	AND E.METER_ID = F.METER_ID;

