CREATE OR REPLACE VIEW ADDRESS_INFO
(entity_domain_id, owner_entity_id, category_id, category_name, street, street2, city, state_code, postal_code, country_code, entry_date)
AS
SELECT E.ENTITY_DOMAIN_ID,
	E.OWNER_ENTITY_ID,
	E.CATEGORY_ID,
	C.CATEGORY_NAME,
	E.STREET,
	E.STREET2,
    (SELECT NVL(DISPLAY_NAME,GEOGRAPHY_NAME)
    FROM GEOGRAPHY
    WHERE UPPER(GEOGRAPHY_TYPE) = 'CITY'
	    AND ROWNUM = 1
    START WITH GEOGRAPHY_ID = E.GEOGRAPHY_ID
    CONNECT BY PRIOR PARENT_GEOGRAPHY_ID = GEOGRAPHY_ID),
    (SELECT NVL(ABBREVIATION,NVL(DISPLAY_NAME,GEOGRAPHY_NAME))
    FROM GEOGRAPHY
    WHERE UPPER(GEOGRAPHY_TYPE) = 'STATE/PROVINCE'
	    AND ROWNUM = 1
    START WITH GEOGRAPHY_ID = E.GEOGRAPHY_ID
    CONNECT BY PRIOR PARENT_GEOGRAPHY_ID = GEOGRAPHY_ID),
    (SELECT NVL(DISPLAY_NAME,GEOGRAPHY_NAME)
    FROM GEOGRAPHY
    WHERE UPPER(GEOGRAPHY_TYPE) = 'POSTAL CODE'
	    AND ROWNUM = 1
    START WITH GEOGRAPHY_ID = E.GEOGRAPHY_ID
    CONNECT BY PRIOR PARENT_GEOGRAPHY_ID = GEOGRAPHY_ID),
    (SELECT NVL(ABBREVIATION,NVL(DISPLAY_NAME,GEOGRAPHY_NAME))
    FROM GEOGRAPHY
    WHERE UPPER(GEOGRAPHY_TYPE) = 'COUNTRY'
	    AND ROWNUM = 1
    START WITH GEOGRAPHY_ID = E.GEOGRAPHY_ID
    CONNECT BY PRIOR PARENT_GEOGRAPHY_ID = GEOGRAPHY_ID),
    E.ENTRY_DATE
FROM ENTITY_DOMAIN_ADDRESS E,
    CATEGORY C
WHERE C.CATEGORY_ID = E.CATEGORY_ID;
