CREATE OR REPLACE VIEW EDC_METER_FORECAST ( EDC_ID, 
SCENARIO_ID, FORECAST_DATE, FORECAST_ENERGY ) AS 
SELECT C.EDC_ID,
	B.SCENARIO_ID,
	B.FORECAST_DATE,
	SUM(B.FORECAST_VAL) "FORECAST_ENERGY"
FROM ACCOUNT_SERVICE_LOCATION_METER A,
	METER_FORECAST B,
	ACCOUNT_EDC C
WHERE A.METER_ID = B.METER_ID
	AND A.ACCOUNT_ID = C.ACCOUNT_ID
	AND B.FORECAST_DATE BETWEEN C.BEGIN_DATE AND NVL(C.END_DATE,B.FORECAST_DATE)
GROUP BY C.EDC_ID,
	B.SCENARIO_ID,
	B.FORECAST_DATE;

