-- Revision: $Revision: 1.63 $
CREATE OR REPLACE VIEW ACCOUNT_ENTITY AS
SELECT ACCOUNT_NAME "ENTITY_NAME",
       ACCOUNT_ALIAS "ENTITY_ALIAS",
       ACCOUNT_ID "ENTITY_ID"
FROM ACCOUNT
WHERE ACCOUNT_ID > 0;

CREATE OR REPLACE VIEW ACCOUNT_GROUP_ENTITY AS
SELECT ACCOUNT_GROUP_NAME "ENTITY_NAME",
       ACCOUNT_GROUP_ALIAS "ENTITY_ALIAS",
       ACCOUNT_GROUP_ID "ENTITY_ID"
FROM ACCOUNT_GROUP
WHERE ACCOUNT_GROUP_ID > 0;

CREATE OR REPLACE VIEW ANCILLARY_SERVICE_ENTITY AS
SELECT ANCILLARY_SERVICE_NAME "ENTITY_NAME",
       ANCILLARY_SERVICE_ALIAS "ENTITY_ALIAS",
       ANCILLARY_SERVICE_ID "ENTITY_ID"
FROM ANCILLARY_SERVICE
WHERE ANCILLARY_SERVICE_ID > 0;

CREATE OR REPLACE VIEW AREA_ENTITY AS
SELECT AREA_NAME "ENTITY_NAME",
       AREA_ALIAS "ENTITY_ALIAS",
       AREA_ID "ENTITY_ID"
FROM AREA
WHERE AREA_ID > 0;

CREATE OR REPLACE VIEW BILL_CYCLE_ENTITY AS
SELECT BILL_CYCLE_NAME "ENTITY_NAME",
       BILL_CYCLE_ALIAS "ENTITY_ALIAS",
       BILL_CYCLE_ID "ENTITY_ID"
FROM BILL_CYCLE
WHERE BILL_CYCLE_ID > 0;

CREATE OR REPLACE VIEW BILL_PARTY_ENTITY AS
SELECT BILL_PARTY_NAME "ENTITY_NAME",
       BILL_PARTY_ALIAS "ENTITY_ALIAS",
       BILL_PARTY_ID "ENTITY_ID"
FROM BILL_PARTY
WHERE BILL_PARTY_ID > 0
  AND UPPER(TRIM(BILL_PARTY_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW BREAKPOINT_ENTITY AS
SELECT BREAKPOINT_NAME "ENTITY_NAME",
       BREAKPOINT_ALIAS "ENTITY_ALIAS",
       BREAKPOINT_ID "ENTITY_ID"
FROM BREAKPOINT
WHERE BREAKPOINT_ID > 0;

CREATE OR REPLACE VIEW CA_ENTITY AS
SELECT CA_NAME "ENTITY_NAME",
       CA_ALIAS "ENTITY_ALIAS",
       CA_ID "ENTITY_ID"
FROM CONTROL_AREA
WHERE CA_ID > 0
  AND UPPER(TRIM(CA_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW CALC_PROCESS_ENTITY AS
SELECT CALC_PROCESS_NAME "ENTITY_NAME",
       CALC_PROCESS_ALIAS "ENTITY_ALIAS",
       CALC_PROCESS_ID "ENTITY_ID"
FROM CALCULATION_PROCESS
WHERE CALC_PROCESS_ID > 0;

CREATE OR REPLACE VIEW CALENDAR_ENTITY AS
SELECT CALENDAR_NAME "ENTITY_NAME",
       CALENDAR_ALIAS "ENTITY_ALIAS",
       CALENDAR_ID "ENTITY_ID"
FROM CALENDAR
WHERE CALENDAR_ID > 0;

CREATE OR REPLACE VIEW CASE_LABEL_ENTITY AS
SELECT CASE_NAME "ENTITY_NAME",
       CASE_ALIAS "ENTITY_ALIAS",
       CASE_ID "ENTITY_ID"
FROM CASE_LABEL
WHERE CASE_ID > 0;

CREATE OR REPLACE VIEW CATEGORY_ENTITY AS
SELECT CATEGORY_NAME "ENTITY_NAME",
       CATEGORY_ALIAS "ENTITY_ALIAS",
       CATEGORY_ID "ENTITY_ID"
FROM CATEGORY
WHERE CATEGORY_ID > 0;

CREATE OR REPLACE VIEW COMPONENT_ENTITY AS
SELECT COMPONENT_NAME "ENTITY_NAME",
       COMPONENT_ALIAS "ENTITY_ALIAS",
       COMPONENT_ID "ENTITY_ID"
FROM COMPONENT
WHERE COMPONENT_ID > 0;

CREATE OR REPLACE VIEW CONDITIONAL_FORMAT_ENTITY AS
SELECT CONDITIONAL_FORMAT_NAME "ENTITY_NAME",
       CONDITIONAL_FORMAT_ALIAS "ENTITY_ALIAS",
       CONDITIONAL_FORMAT_ID "ENTITY_ID"
FROM CONDITIONAL_FORMAT
WHERE CONDITIONAL_FORMAT_ID > 0;

CREATE OR REPLACE VIEW CONTACT_ENTITY AS
SELECT CONTACT_NAME "ENTITY_NAME",
       CONTACT_ALIAS "ENTITY_ALIAS",
       CONTACT_ID "ENTITY_ID"
FROM CONTACT
WHERE CONTACT_ID > 0
  AND UPPER(TRIM(CONTACT_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW CONTRACT_ENTITY AS
SELECT CONTRACT_NAME "ENTITY_NAME",
       CONTRACT_ALIAS "ENTITY_ALIAS",
       CONTRACT_ID "ENTITY_ID"
FROM SERVICE_CONTRACT
WHERE CONTRACT_ID > 0;

CREATE OR REPLACE VIEW CONTRACT_LIMIT_ENTITY AS
SELECT LIMIT_NAME "ENTITY_NAME",
       LIMIT_ALIAS "ENTITY_ALIAS",
       LIMIT_ID "ENTITY_ID"
FROM CONTRACT_LIMIT
WHERE LIMIT_ID > 0;

CREATE OR REPLACE VIEW CUSTOMER_ENTITY AS
SELECT CUSTOMER_NAME "ENTITY_NAME",
       CUSTOMER_ALIAS "ENTITY_ALIAS",
       CUSTOMER_ID "ENTITY_ID"
FROM CUSTOMER
WHERE CUSTOMER_ID > 0
  AND UPPER(TRIM(CUSTOMER_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW DATA_LOCK_GROUP_ENTITY AS
SELECT DATA_LOCK_GROUP_NAME "ENTITY_NAME",
       DATA_LOCK_GROUP_ALIAS "ENTITY_ALIAS",
       DATA_LOCK_GROUP_ID "ENTITY_ID"
FROM DATA_LOCK_GROUP
WHERE DATA_LOCK_GROUP_ID > 0;

CREATE OR REPLACE VIEW DER_ENTITY AS
SELECT DER_NAME "ENTITY_NAME",
       DER_ALIAS "ENTITY_ALIAS",
       DER_ID "ENTITY_ID"
FROM DISTRIBUTED_ENERGY_RESOURCE
WHERE DER_ID > 0;

CREATE OR REPLACE VIEW DER_TYPE_ENTITY AS
SELECT DER_TYPE_NAME "ENTITY_NAME",
       DER_TYPE_ALIAS "ENTITY_ALIAS",
       DER_TYPE_ID "ENTITY_ID"
FROM DER_TYPE
WHERE DER_TYPE_ID > 0;

CREATE OR REPLACE VIEW DR_EVENT_ENTITY AS
SELECT EVENT_NAME "ENTITY_NAME",
       EVENT_ALIAS "ENTITY_ALIAS",
       EVENT_ID "ENTITY_ID"
FROM DR_EVENT
WHERE EVENT_ID > 0
  AND UPPER(TRIM(EVENT_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW EDC_ENTITY AS
SELECT EDC_NAME "ENTITY_NAME",
       EDC_ALIAS "ENTITY_ALIAS",
       EDC_ID "ENTITY_ID"
FROM ENERGY_DISTRIBUTION_COMPANY
WHERE EDC_ID > 0
  AND UPPER(TRIM(EDC_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW ENTITY_DOMAIN_ENTITY AS
SELECT ENTITY_DOMAIN_NAME "ENTITY_NAME",
       ENTITY_DOMAIN_ALIAS "ENTITY_ALIAS",
       ENTITY_DOMAIN_ID "ENTITY_ID"
FROM ENTITY_DOMAIN
WHERE ENTITY_DOMAIN_ID > 0;

CREATE OR REPLACE VIEW ENTITY_GROUP_ENTITY AS
SELECT ENTITY_GROUP_NAME "ENTITY_NAME",
       ENTITY_GROUP_ALIAS "ENTITY_ALIAS",
       ENTITY_GROUP_ID "ENTITY_ID"
FROM ENTITY_GROUP
WHERE ENTITY_GROUP_ID > 0;

CREATE OR REPLACE VIEW ESP_ENTITY AS
SELECT ESP_NAME "ENTITY_NAME",
       ESP_ALIAS "ENTITY_ALIAS",
       ESP_ID "ENTITY_ID"
FROM ENERGY_SERVICE_PROVIDER
WHERE ESP_ID > 0
  AND UPPER(TRIM(ESP_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW ETAG_ENTITY AS
SELECT ETAG_NAME "ENTITY_NAME",
       ETAG_ALIAS "ENTITY_ALIAS",
       ETAG_ID "ENTITY_ID"
FROM ETAG
WHERE ETAG_ID > 0
  AND UPPER(TRIM(ETAG_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW EXTERNAL_SYSTEM_ENTITY AS
SELECT EXTERNAL_SYSTEM_NAME "ENTITY_NAME",
       EXTERNAL_SYSTEM_ALIAS "ENTITY_ALIAS",
       EXTERNAL_SYSTEM_ID "ENTITY_ID"
FROM EXTERNAL_SYSTEM
WHERE EXTERNAL_SYSTEM_ID > 0;

CREATE OR REPLACE VIEW EXTERNAL_TRANSACTION_ENTITY AS
SELECT TRANSACTION_NAME "ENTITY_NAME",
       TRANSACTION_ALIAS "ENTITY_ALIAS",
       TRANSACTION_ID "ENTITY_ID"
FROM INTERCHANGE_TRANSACTION_EXT
WHERE TRANSACTION_ID > 0;

CREATE OR REPLACE VIEW GEOGRAPHY_ENTITY AS
SELECT GEOGRAPHY_NAME "ENTITY_NAME",
       GEOGRAPHY_ALIAS "ENTITY_ALIAS",
       GEOGRAPHY_ID "ENTITY_ID"
FROM GEOGRAPHY
WHERE GEOGRAPHY_ID > 0;

CREATE OR REPLACE VIEW GROWTH_PATTERN_ENTITY AS
SELECT PATTERN_NAME "ENTITY_NAME",
       PATTERN_ALIAS "ENTITY_ALIAS",
       PATTERN_ID "ENTITY_ID"
FROM GROWTH_PATTERN
WHERE PATTERN_ID > 0;

CREATE OR REPLACE VIEW HEAT_RATE_CURVE_ENTITY AS
SELECT HEAT_RATE_CURVE_NAME "ENTITY_NAME",
       HEAT_RATE_CURVE_ALIAS "ENTITY_ALIAS",
       HEAT_RATE_CURVE_ID "ENTITY_ID"
FROM HEAT_RATE_CURVE
WHERE HEAT_RATE_CURVE_ID > 0;

CREATE OR REPLACE VIEW HOLIDAY_ENTITY AS
SELECT HOLIDAY_NAME "ENTITY_NAME",
       HOLIDAY_ALIAS "ENTITY_ALIAS",
       HOLIDAY_ID "ENTITY_ID"
FROM HOLIDAY
WHERE HOLIDAY_ID > 0;

CREATE OR REPLACE VIEW HOLIDAY_SET_ENTITY AS
SELECT HOLIDAY_SET_NAME "ENTITY_NAME",
       HOLIDAY_SET_ALIAS "ENTITY_ALIAS",
       HOLIDAY_SET_ID "ENTITY_ID"
FROM HOLIDAY_SET
WHERE HOLIDAY_SET_ID > 0;

CREATE OR REPLACE VIEW INTERCHANGE_CONTRACT_ENTITY AS
SELECT CONTRACT_NAME "ENTITY_NAME",
       CONTRACT_ALIAS "ENTITY_ALIAS",
       CONTRACT_ID "ENTITY_ID"
FROM INTERCHANGE_CONTRACT
WHERE CONTRACT_ID > 0
  AND UPPER(TRIM(CONTRACT_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW INVOICE_GROUP_ENTITY AS
SELECT INVOICE_GROUP_NAME "ENTITY_NAME",
       INVOICE_GROUP_ALIAS "ENTITY_ALIAS",
       INVOICE_GROUP_ID "ENTITY_ID"
FROM INVOICE_GROUP
WHERE INVOICE_GROUP_ID > 0;

CREATE OR REPLACE VIEW IT_COMMODITY_ENTITY AS
SELECT COMMODITY_NAME "ENTITY_NAME",
       COMMODITY_ALIAS "ENTITY_ALIAS",
       COMMODITY_ID "ENTITY_ID"
FROM IT_COMMODITY
WHERE COMMODITY_ID > 0;

CREATE OR REPLACE VIEW JOB_THREAD_ENTITY AS
SELECT JOB_THREAD_NAME "ENTITY_NAME",
       JOB_THREAD_ALIAS "ENTITY_ALIAS",
       JOB_THREAD_ID "ENTITY_ID"
FROM JOB_THREAD
WHERE JOB_THREAD_ID > 0;

CREATE OR REPLACE VIEW LOAD_PROFILE_ENTITY AS
SELECT PROFILE_NAME "ENTITY_NAME",
       PROFILE_ALIAS "ENTITY_ALIAS",
       PROFILE_ID "ENTITY_ID"
FROM LOAD_PROFILE
WHERE PROFILE_ID > 0;

CREATE OR REPLACE VIEW LOAD_PROFILE_LIBRARY_ENTITY AS
SELECT PROFILE_LIBRARY_NAME "ENTITY_NAME",
       PROFILE_LIBRARY_ALIAS "ENTITY_ALIAS",
       PROFILE_LIBRARY_ID "ENTITY_ID"
FROM LOAD_PROFILE_LIBRARY
WHERE PROFILE_LIBRARY_ID > 0;

CREATE OR REPLACE VIEW LOAD_PROFILE_SET_ENTITY AS
SELECT PROFILE_SET_NAME "ENTITY_NAME",
       PROFILE_SET_ALIAS "ENTITY_ALIAS",
       PROFILE_SET_ID "ENTITY_ID"
FROM LOAD_PROFILE_SET
WHERE PROFILE_SET_ID > 0;

CREATE OR REPLACE VIEW LOSS_FACTOR_ENTITY AS
SELECT LOSS_FACTOR_NAME "ENTITY_NAME",
       LOSS_FACTOR_ALIAS "ENTITY_ALIAS",
       LOSS_FACTOR_ID "ENTITY_ID"
FROM LOSS_FACTOR
WHERE LOSS_FACTOR_ID > 0;

CREATE OR REPLACE VIEW MARKET_PRICE_ENTITY AS
SELECT MARKET_PRICE_NAME "ENTITY_NAME",
       MARKET_PRICE_ALIAS "ENTITY_ALIAS",
       MARKET_PRICE_ID "ENTITY_ID"
FROM MARKET_PRICE
WHERE MARKET_PRICE_ID > 0;

CREATE OR REPLACE VIEW MEASUREMENT_SOURCE_ENTITY AS
SELECT MEASUREMENT_SOURCE_NAME "ENTITY_NAME",
       MEASUREMENT_SOURCE_ALIAS "ENTITY_ALIAS",
       MEASUREMENT_SOURCE_ID "ENTITY_ID"
FROM MEASUREMENT_SOURCE
WHERE MEASUREMENT_SOURCE_ID > 0;

CREATE OR REPLACE VIEW METER_ENTITY AS
SELECT METER_NAME "ENTITY_NAME",
       METER_ALIAS "ENTITY_ALIAS",
       METER_ID "ENTITY_ID"
FROM METER
WHERE METER_ID > 0
  AND UPPER(TRIM(METER_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW MRSP_ENTITY AS
SELECT MRSP_NAME "ENTITY_NAME",
       MRSP_ALIAS "ENTITY_ALIAS",
       MRSP_ID "ENTITY_ID"
FROM METER_READING_SERVICE_PROVIDER
WHERE MRSP_ID > 0
  AND UPPER(TRIM(MRSP_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW OASIS_NODE_ENTITY AS
SELECT OASIS_NODE_NAME "ENTITY_NAME",
       OASIS_NODE_ALIAS "ENTITY_ALIAS",
       OASIS_NODE_ID "ENTITY_ID"
FROM OASIS_NODE
WHERE OASIS_NODE_ID > 0;

CREATE OR REPLACE VIEW PATH_ENTITY AS
SELECT PATH_NAME "ENTITY_NAME",
       PATH_ALIAS "ENTITY_ALIAS",
       PATH_ID "ENTITY_ID"
FROM TX_PATH
WHERE PATH_ID > 0;

CREATE OR REPLACE VIEW PERIOD_ENTITY AS
SELECT PERIOD_NAME "ENTITY_NAME",
       PERIOD_ALIAS "ENTITY_ALIAS",
       PERIOD_ID "ENTITY_ID"
FROM PERIOD
WHERE PERIOD_ID > 0;

CREATE OR REPLACE VIEW PIPELINE_ENTITY AS
SELECT PIPELINE_NAME "ENTITY_NAME",
       PIPELINE_ALIAS "ENTITY_ALIAS",
       PIPELINE_ID "ENTITY_ID"
FROM PIPELINE
WHERE PIPELINE_ID > 0
  AND UPPER(TRIM(PIPELINE_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW POOL_ENTITY AS
SELECT POOL_NAME "ENTITY_NAME",
       POOL_ALIAS "ENTITY_ALIAS",
       POOL_ID "ENTITY_ID"
FROM POOL
WHERE POOL_ID > 0
  AND UPPER(TRIM(POOL_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW PORTFOLIO_ENTITY AS
SELECT PORTFOLIO_NAME "ENTITY_NAME",
       PORTFOLIO_ALIAS "ENTITY_ALIAS",
       PORTFOLIO_ID "ENTITY_ID"
FROM PORTFOLIO
WHERE PORTFOLIO_ID > 0;

CREATE OR REPLACE VIEW POSITION_EVALUATION_ENTITY AS
SELECT EVALUATION_NAME "ENTITY_NAME",
       EVALUATION_ALIAS "ENTITY_ALIAS",
       EVALUATION_ID "ENTITY_ID"
FROM POSITION_ANALYSIS_EVALUATION
WHERE EVALUATION_ID > 0;

CREATE OR REPLACE VIEW PRODUCT_ENTITY AS
SELECT PRODUCT_NAME "ENTITY_NAME",
       PRODUCT_ALIAS "ENTITY_ALIAS",
       PRODUCT_ID "ENTITY_ID"
FROM PRODUCT
WHERE PRODUCT_ID > 0;

CREATE OR REPLACE VIEW PROGRAM_ENTITY AS
SELECT PROGRAM_NAME "ENTITY_NAME",
       PROGRAM_ALIAS "ENTITY_ALIAS",
       PROGRAM_ID "ENTITY_ID"
FROM PROGRAM
WHERE PROGRAM_ID > 0;

CREATE OR REPLACE VIEW PROSPECT_SCREEN_ENTITY AS
SELECT SCREEN_NAME "ENTITY_NAME",
       SCREEN_ALIAS "ENTITY_ALIAS",
       SCREEN_ID "ENTITY_ID"
FROM PROSPECT_SCREEN
WHERE SCREEN_ID > 0;

CREATE OR REPLACE VIEW PROXY_DAY_METHOD_ENTITY AS
SELECT PROXY_DAY_METHOD_NAME "ENTITY_NAME",
       PROXY_DAY_METHOD_ALIAS "ENTITY_ALIAS",
       PROXY_DAY_METHOD_ID "ENTITY_ID"
FROM PROXY_DAY_METHOD
WHERE PROXY_DAY_METHOD_ID > 0;

CREATE OR REPLACE VIEW PSE_ENTITY AS
SELECT PSE_NAME "ENTITY_NAME",
       PSE_ALIAS "ENTITY_ALIAS",
       PSE_ID "ENTITY_ID"
FROM PURCHASING_SELLING_ENTITY
WHERE PSE_ID > 0
  AND UPPER(TRIM(PSE_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW QUOTE_REQUEST_ENTITY AS
SELECT QUOTE_NAME "ENTITY_NAME",
       QUOTE_ALIAS "ENTITY_ALIAS",
       QUOTE_ID "ENTITY_ID"
FROM QUOTE_REQUEST
WHERE QUOTE_ID > 0
  AND UPPER(TRIM(QUOTE_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW REACTOR_PROCEDURE_ENTITY AS
SELECT REACTOR_PROCEDURE_NAME "ENTITY_NAME",
       REACTOR_PROCEDURE_ALIAS "ENTITY_ALIAS",
       REACTOR_PROCEDURE_ID "ENTITY_ID"
FROM REACTOR_PROCEDURE
WHERE REACTOR_PROCEDURE_ID > 0;

CREATE OR REPLACE VIEW RESOURCE_GROUP_ENTITY AS
SELECT RESOURCE_GROUP_NAME "ENTITY_NAME",
       RESOURCE_GROUP_ALIAS "ENTITY_ALIAS",
       RESOURCE_GROUP_ID "ENTITY_ID"
FROM SUPPLY_RESOURCE_GROUP
WHERE RESOURCE_GROUP_ID > 0;

CREATE OR REPLACE VIEW ROLLUP_ENTITY AS
SELECT ROLLUP_NAME "ENTITY_NAME",
       ROLLUP_ALIAS "ENTITY_ALIAS",
       ROLLUP_ID "ENTITY_ID"
FROM RTO_ROLLUP
WHERE ROLLUP_ID > 0;

CREATE OR REPLACE VIEW SC_ENTITY AS
SELECT SC_NAME "ENTITY_NAME",
       SC_ALIAS "ENTITY_ALIAS",
       SC_ID "ENTITY_ID"
FROM SCHEDULE_COORDINATOR
WHERE SC_ID > 0
  AND UPPER(TRIM(SC_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW SCENARIO_ENTITY AS
SELECT SCENARIO_NAME "ENTITY_NAME",
       SCENARIO_ALIAS "ENTITY_ALIAS",
       SCENARIO_ID "ENTITY_ID"
FROM SCENARIO
WHERE SCENARIO_ID > 0;

CREATE OR REPLACE VIEW SCHEDULE_GROUP_ENTITY AS
SELECT SCHEDULE_GROUP_NAME "ENTITY_NAME",
       SCHEDULE_GROUP_ALIAS "ENTITY_ALIAS",
       SCHEDULE_GROUP_ID "ENTITY_ID"
FROM SCHEDULE_GROUP
WHERE SCHEDULE_GROUP_ID > 0;

CREATE OR REPLACE VIEW SEASON_ENTITY AS
SELECT SEASON_NAME "ENTITY_NAME",
       SEASON_ALIAS "ENTITY_ALIAS",
       SEASON_ID "ENTITY_ID"
FROM SEASON
WHERE SEASON_ID > 0;

CREATE OR REPLACE VIEW SEGMENT_ENTITY AS
SELECT SEGMENT_NAME "ENTITY_NAME",
       SEGMENT_ALIAS "ENTITY_ALIAS",
       SEGMENT_ID "ENTITY_ID"
FROM TX_SEGMENT
WHERE SEGMENT_ID > 0;

CREATE OR REPLACE VIEW SERVICE_AREA_ENTITY AS
SELECT SERVICE_AREA_NAME "ENTITY_NAME",
       SERVICE_AREA_ALIAS "ENTITY_ALIAS",
       SERVICE_AREA_ID "ENTITY_ID"
FROM SERVICE_AREA
WHERE SERVICE_AREA_ID > 0;

CREATE OR REPLACE VIEW SERVICE_LOCATION_ENTITY AS
SELECT SERVICE_LOCATION_NAME "ENTITY_NAME",
       SERVICE_LOCATION_ALIAS "ENTITY_ALIAS",
       SERVICE_LOCATION_ID "ENTITY_ID"
FROM SERVICE_LOCATION
WHERE SERVICE_LOCATION_ID > 0;

CREATE OR REPLACE VIEW SERVICE_POINT_ENTITY AS
SELECT SERVICE_POINT_NAME "ENTITY_NAME",
       SERVICE_POINT_ALIAS "ENTITY_ALIAS",
       SERVICE_POINT_ID "ENTITY_ID"
FROM SERVICE_POINT
WHERE SERVICE_POINT_ID > 0;

CREATE OR REPLACE VIEW SERVICE_REGION_ENTITY AS
SELECT SERVICE_REGION_NAME "ENTITY_NAME",
       SERVICE_REGION_ALIAS "ENTITY_ALIAS",
       SERVICE_REGION_ID "ENTITY_ID"
FROM SERVICE_REGION
WHERE SERVICE_REGION_ID > 0;

CREATE OR REPLACE VIEW SERVICE_TYPE_ENTITY AS
SELECT SERVICE_TYPE_NAME "ENTITY_NAME",
       SERVICE_TYPE_ALIAS "ENTITY_ALIAS",
       SERVICE_TYPE_ID "ENTITY_ID"
FROM TX_SERVICE_TYPE
WHERE SERVICE_TYPE_ID > 0;

CREATE OR REPLACE VIEW SERVICE_ZONE_ENTITY AS
SELECT SERVICE_ZONE_NAME "ENTITY_NAME",
       SERVICE_ZONE_ALIAS "ENTITY_ALIAS",
       SERVICE_ZONE_ID "ENTITY_ID"
FROM SERVICE_ZONE
WHERE SERVICE_ZONE_ID > 0;

CREATE OR REPLACE VIEW SETTLEMENT_TYPE_ENTITY AS
SELECT SETTLEMENT_TYPE_NAME "ENTITY_NAME",
       SETTLEMENT_TYPE_ALIAS "ENTITY_ALIAS",
       SETTLEMENT_TYPE_ID "ENTITY_ID"
FROM SETTLEMENT_TYPE
WHERE SETTLEMENT_TYPE_ID > 0;

CREATE OR REPLACE VIEW STATEMENT_TYPE_ENTITY AS
SELECT STATEMENT_TYPE_NAME "ENTITY_NAME",
       STATEMENT_TYPE_ALIAS "ENTITY_ALIAS",
       STATEMENT_TYPE_ID "ENTITY_ID"
FROM STATEMENT_TYPE
WHERE STATEMENT_TYPE_ID > 0;

CREATE OR REPLACE VIEW SUB_STATION_ENTITY AS
SELECT SUB_STATION_NAME "ENTITY_NAME",
       SUB_STATION_ALIAS "ENTITY_ALIAS",
       SUB_STATION_ID "ENTITY_ID"
FROM TX_SUB_STATION
WHERE SUB_STATION_ID > 0;

CREATE OR REPLACE VIEW SUB_STATION_METER_ENTITY AS
SELECT METER_NAME "ENTITY_NAME",
       METER_ALIAS "ENTITY_ALIAS",
       METER_ID "ENTITY_ID"
FROM TX_SUB_STATION_METER
WHERE METER_ID > 0;

CREATE OR REPLACE VIEW SUB_STATION_METER_POINT_ENTITY AS
SELECT METER_POINT_NAME "ENTITY_NAME",
       METER_POINT_ALIAS "ENTITY_ALIAS",
       METER_POINT_ID "ENTITY_ID"
FROM TX_SUB_STATION_METER_POINT
WHERE METER_POINT_ID > 0;

CREATE OR REPLACE VIEW SUPPLY_RESOURCE_ENTITY AS
SELECT RESOURCE_NAME "ENTITY_NAME",
       RESOURCE_ALIAS "ENTITY_ALIAS",
       RESOURCE_ID "ENTITY_ID"
FROM SUPPLY_RESOURCE
WHERE RESOURCE_ID > 0;

CREATE OR REPLACE VIEW SYSTEM_ACTION_ENTITY AS
SELECT ACTION_NAME "ENTITY_NAME",
       ACTION_ALIAS "ENTITY_ALIAS",
       ACTION_ID "ENTITY_ID"
FROM SYSTEM_ACTION
WHERE ACTION_ID > 0;

CREATE OR REPLACE VIEW SYSTEM_ALERT_ENTITY AS
SELECT ALERT_NAME "ENTITY_NAME",
       ALERT_ALIAS "ENTITY_ALIAS",
       ALERT_ID "ENTITY_ID"
FROM SYSTEM_ALERT
WHERE ALERT_ID > 0;

CREATE OR REPLACE VIEW SYSTEM_EVENT_ENTITY AS
SELECT EVENT_NAME "ENTITY_NAME",
       EVENT_ALIAS "ENTITY_ALIAS",
       EVENT_ID "ENTITY_ID"
FROM SYSTEM_EVENT
WHERE EVENT_ID > 0;

CREATE OR REPLACE VIEW SYSTEM_LOAD_ENTITY AS
SELECT SYSTEM_LOAD_NAME "ENTITY_NAME",
       SYSTEM_LOAD_ALIAS "ENTITY_ALIAS",
       SYSTEM_LOAD_ID "ENTITY_ID"
FROM SYSTEM_LOAD
WHERE SYSTEM_LOAD_ID > 0;

CREATE OR REPLACE VIEW SYSTEM_TABLE_ENTITY AS
SELECT TABLE_NAME "ENTITY_NAME",
       TABLE_ALIAS "ENTITY_ALIAS",
       TABLE_ID "ENTITY_ID"
FROM SYSTEM_TABLE
WHERE TABLE_ID > 0;

CREATE OR REPLACE VIEW TEMPLATE_ENTITY AS
SELECT TEMPLATE_NAME "ENTITY_NAME",
       TEMPLATE_ALIAS "ENTITY_ALIAS",
       TEMPLATE_ID "ENTITY_ID"
FROM TEMPLATE
WHERE TEMPLATE_ID > 0;

CREATE OR REPLACE VIEW TP_ENTITY AS
SELECT TP_NAME "ENTITY_NAME",
       TP_ALIAS "ENTITY_ALIAS",
       TP_ID "ENTITY_ID"
FROM TRANSMISSION_PROVIDER
WHERE TP_ID > 0
  AND UPPER(TRIM(TP_STATUS)) = 'ACTIVE';

CREATE OR REPLACE VIEW TRANSACTION_ENTITY AS
SELECT TRANSACTION_NAME "ENTITY_NAME",
       TRANSACTION_ALIAS "ENTITY_ALIAS",
       TRANSACTION_ID "ENTITY_ID"
FROM INTERCHANGE_TRANSACTION
WHERE TRANSACTION_ID > 0;

CREATE OR REPLACE VIEW TRANSACTION_TRAIT_GROUP_ENTITY AS
SELECT TRAIT_GROUP_NAME "ENTITY_NAME",
       TRAIT_GROUP_ALIAS "ENTITY_ALIAS",
       TRAIT_GROUP_ID "ENTITY_ID"
FROM TRANSACTION_TRAIT_GROUP
WHERE TRAIT_GROUP_ID > 0;

CREATE OR REPLACE VIEW TX_FEEDER_ENTITY AS
SELECT FEEDER_NAME "ENTITY_NAME",
       FEEDER_ALIAS "ENTITY_ALIAS",
       FEEDER_ID "ENTITY_ID"
FROM TX_FEEDER
WHERE FEEDER_ID > 0;

CREATE OR REPLACE VIEW TX_FEEDER_SEGMENT_ENTITY AS
SELECT FEEDER_SEGMENT_NAME "ENTITY_NAME",
       FEEDER_SEGMENT_ALIAS "ENTITY_ALIAS",
       FEEDER_SEGMENT_ID "ENTITY_ID"
FROM TX_FEEDER_SEGMENT
WHERE FEEDER_SEGMENT_ID > 0;

CREATE OR REPLACE VIEW USAGE_WRF_ENTITY AS
SELECT WRF_NAME "ENTITY_NAME",
       WRF_ALIAS "ENTITY_ALIAS",
       WRF_ID "ENTITY_ID"
FROM USAGE_WRF
WHERE WRF_ID > 0;

CREATE OR REPLACE VIEW VPP_ENTITY AS
SELECT VPP_NAME "ENTITY_NAME",
       VPP_ALIAS "ENTITY_ALIAS",
       VPP_ID "ENTITY_ID"
FROM VIRTUAL_POWER_PLANT
WHERE VPP_ID > 0;

CREATE OR REPLACE VIEW WEATHER_PARAMETER_ENTITY AS
SELECT PARAMETER_NAME "ENTITY_NAME",
       PARAMETER_ALIAS "ENTITY_ALIAS",
       PARAMETER_ID "ENTITY_ID"
FROM WEATHER_PARAMETER
WHERE PARAMETER_ID > 0;

CREATE OR REPLACE VIEW WEATHER_STATION_ENTITY AS
SELECT STATION_NAME "ENTITY_NAME",
       STATION_ALIAS "ENTITY_ALIAS",
       STATION_ID "ENTITY_ID"
FROM WEATHER_STATION
WHERE STATION_ID > 0;

