CREATE OR REPLACE VIEW EXTERNAL_ACCOUNT_ENTITY ( ENTITY_NAME, 
ENTITY_ALIAS, ENTITY_ID ) AS SELECT 
	A.ACCOUNT_NAME "ENTITY_NAME", 
	A.ACCOUNT_ALIAS "ENTITY_ALIAS", 
	A.ACCOUNT_ID "ENTITY_ID" 
FROM ACCOUNT A, ACCOUNT_STATUS B, ACCOUNT_STATUS_NAME C
WHERE A.IS_EXTERNAL_INTERVAL_USAGE = 1
	AND B.ACCOUNT_ID = A.ACCOUNT_ID
	AND TRUNC(SYSDATE) BETWEEN B.BEGIN_DATE AND NVL(B.END_DATE, HIGH_DATE)
	AND C.STATUS_NAME = B.STATUS_NAME
	AND C.IS_ACTIVE = 1; 
