CREATE OR REPLACE VIEW METER_CALENDAR_INFO ( METER_ID, 
CALENDAR_TYPE, BEGIN_DATE, END_DATE, CALENDAR_ID, 
ENTRY_DATE, CALENDAR_NAME, CASE_NAME ) AS 
SELECT M.METER_ID,
    M.CALENDAR_TYPE,
    M.BEGIN_DATE,
    M.END_DATE,
    M.CALENDAR_ID,
    M.ENTRY_DATE,
    C.CALENDAR_NAME,
    CL.CASE_NAME
  FROM METER_CALENDAR M,
    CALENDAR C,
    CASE_LABEL CL
  WHERE (M.CALENDAR_ID = C.CALENDAR_ID
  AND M.CASE_ID        = CL.CASE_ID)
  OR M.CALENDAR_ID     = 0;
