CREATE OR REPLACE VIEW NON_AGGREGATE_ACCOUNTS ( ACCOUNT_NAME, 
ACCOUNT_ID, EDC_ID, EDC_BEGIN_DATE, EDC_END_DATE, 
ESP_ID, POOL_ID, ESP_BEGIN_DATE, ESP_END_DATE, 
PSE_ID, PSE_BEGIN_DATE, PSE_END_DATE, ESP_TYPE, ESP_NAME
 ) AS
SELECT A.ACCOUNT_NAME, 
	A.ACCOUNT_ID, 
	C.EDC_ID, 
	C.BEGIN_DATE "EDC_BEGIN_DATE", 
	C.END_DATE "EDC_END_DATE", 
	D.ESP_ID, 
	D.POOL_ID, 
	D.BEGIN_DATE "ESP_BEGIN_DATE", 
	D.END_DATE "ESP_END_DATE", 
	E.PSE_ID, 
	E.BEGIN_DATE "PSE_BEGIN_DATE", 
	E.END_DATE "PSE_END_DATE", 
	F.ESP_TYPE,
	F.ESP_NAME 
FROM ACCOUNT A,
	ACCOUNT_STATUS B,
	ACCOUNT_STATUS_NAME STATUS_NAME,
	ACCOUNT_EDC C,
	ACCOUNT_ESP D,
	PSE_ESP E,
	ENERGY_SERVICE_PROVIDER F
WHERE  A.IS_AGGREGATE_ACCOUNT = 0
	AND A.IS_SUB_AGGREGATE = 0
	AND B.ACCOUNT_ID = A.ACCOUNT_ID
	AND TRUNC(SYSDATE) BETWEEN B.BEGIN_DATE AND NVL(B.END_DATE, HIGH_DATE)
	AND B.STATUS_NAME = STATUS_NAME.STATUS_NAME
	AND STATUS_NAME.IS_ACTIVE = 1   
	AND C.ACCOUNT_ID = B.ACCOUNT_ID 
	AND D.ACCOUNT_ID = C.ACCOUNT_ID 
	AND E.ESP_ID = D.ESP_ID 
	AND F.ESP_ID = E.ESP_ID;
