CREATE OR REPLACE VIEW OVERVIEW_INFO ( ACCOUNT_ID, 
ACCOUNT_ESP, ACCOUNT_EDC, SERVICE_LOCATION_ID, ACCOUNT_NAME, 
SERVICE_LOCATION_NAME, SERVICE_LOCATION_ESP, SERVICE_LOCATION_EDC, METER_ID, 
METER_NAME, METER_ESP, METER_EDC, ACCOUNT_GROUP_NAME
 ) AS SELECT A.ACCOUNT_ID, 
	 G.ESP_ACCOUNT_NUMBER "ACCOUNT_ESP", 
 	 F.EDC_ACCOUNT_NUMBER "ACCOUNT_EDC", 
	 A.SERVICE_LOCATION_ID, 
	 B.ACCOUNT_NAME, 
	 C.SERVICE_LOCATION_NAME, 
	 A.ESP_IDENTIFIER "SERVICE_LOCATION_ESP", 
	 A.EDC_IDENTIFIER "SERVICE_LOCATION_EDC", 
	 D.METER_ID, 
	 E.METER_NAME, 
	 D.ESP_IDENTIFIER "METER_ESP", 
	 D.EDC_IDENTIFIER "METER_EDC",
	 H.ACCOUNT_GROUP_NAME
FROM ACCOUNT_SERVICE_LOCATION A, ACCOUNT B, SERVICE_LOCATION C, SERVICE_LOCATION_METER D, METER E, 
ACCOUNT_EDC F, ACCOUNT_ESP G, ACCOUNT_GROUP H, ACCOUNT_GROUP_ASSIGNMENT I 
WHERE A.ACCOUNT_ID(+) = B.ACCOUNT_ID 
	AND A.SERVICE_LOCATION_ID = C.SERVICE_LOCATION_ID 
	AND D.SERVICE_LOCATION_ID(+) = A.SERVICE_LOCATION_ID 
	AND D.METER_ID = E.METER_ID 
	AND B.ACCOUNT_ID = F.ACCOUNT_ID(+) 
	AND B.ACCOUNT_ID = G.ACCOUNT_ID(+)
	AND B.ACCOUNT_ID = I.ACCOUNT_ID(+)
	AND H.ACCOUNT_GROUP_ID(+) = I.ACCOUNT_GROUP_ID;

