CREATE OR REPLACE VIEW PHYSICAL_POSITION_PURCHASER ( NAME, 
ID, SCHEDULE_TYPE, SCHEDULE_DATE ) AS SELECT DISTINCT C.PSE_NAME "NAME", 
		C.PSE_ID "ID", 
		B.SCHEDULE_TYPE, 
		TRUNC(B.SCHEDULE_DATE) "SCHEDULE_DATE" 
	FROM INTERCHANGE_TRANSACTION A, 
		IT_SCHEDULE B, 
		PURCHASING_SELLING_ENTITY C 
	WHERE A.TRANSACTION_ID = B.TRANSACTION_ID 
		AND A.PURCHASER_ID > 0 
		AND A.PURCHASER_ID = C.PSE_ID;

