CREATE OR REPLACE VIEW RETAIL_ACCOUNT_EDC_INFO ( ACCOUNT_NAME, 
		ACCOUNT_ID, ACCOUNT_MODEL_OPTION, ACCOUNT_IS_ACTIVE,
		IS_AGGREGATE_ACCOUNT, EDC_ID ) AS
SELECT A.ACCOUNT_NAME, A.ACCOUNT_ID, A.ACCOUNT_MODEL_OPTION,
	D.IS_ACTIVE, A.IS_AGGREGATE_ACCOUNT, C.EDC_ID
FROM ACCOUNT A, ACCOUNT_STATUS B, ACCOUNT_EDC C, ACCOUNT_STATUS_NAME D
WHERE B.ACCOUNT_ID = A.ACCOUNT_ID
	AND TRUNC(SYSDATE) BETWEEN B.BEGIN_DATE AND NVL(B.END_DATE, HIGH_DATE)
	AND C.ACCOUNT_ID = B.ACCOUNT_ID
	AND D.STATUS_NAME = B.STATUS_NAME;
