CREATE OR REPLACE VIEW TRANSACTION_COMMODITY_SCHEDULE ( ID, 
NAME, ALIAS, TYPE, INTERVAL, MARKET, FIRM, PURCHASER, SELLER, POR, POD, COMMODITY, 
COMMODITY_TYPE, COMMODITY_UNIT, COMMODITY_UNIT_FORMAT, COMMODITY_PRICE_UNIT, 
COMMODITY_PRICE_FORMAT, SCHEDULE_TYPE, SCHEDULE_DATE, AMOUNT, 
PRICE, COST, AS_OF_DATE ) AS 
SELECT A.TRANSACTION_ID "Id",
	A.TRANSACTION_NAME "Name",
	A.TRANSACTION_ALIAS "Alias",
	A.TRANSACTION_TYPE "Type",
	A.TRANSACTION_INTERVAL "Interval",
	DECODE(A.TRANSACTION_TYPE,'Retail Schedule','Retail','Wholesale') "Market",
	DECODE(A.IS_FIRM,'1','Yes','No') "Firm",
	B.PSE_NAME "Purchaser",
	C.PSE_NAME "Seller",
	D.SERVICE_POINT_NAME "POR",
	E.SERVICE_POINT_NAME "POD",
	F.COMMODITY_NAME "Commodity",
	F.COMMODITY_TYPE,
	F.COMMODITY_UNIT,
	F.COMMODITY_UNIT_FORMAT,
	F.COMMODITY_PRICE_UNIT,
	F.COMMODITY_PRICE_FORMAT,
	G.SCHEDULE_TYPE,
	G.SCHEDULE_DATE,
	G.AS_OF_DATE,
	G.AMOUNT,
	G.PRICE,
	G.AMOUNT * (G.PRICE * DECODE (F.COMMODITY_PRICE_UNIT,'Cents',0.01,1.0)) "Cost"
FROM INTERCHANGE_TRANSACTION A,
	PURCHASING_SELLING_ENTITY B,
	PURCHASING_SELLING_ENTITY C,
	SERVICE_POINT D,
	SERVICE_POINT E,
	IT_COMMODITY F,
	IT_SCHEDULE G
WHERE A.PURCHASER_ID = B.PSE_ID
	AND A.SELLER_ID = C.PSE_ID
	AND A.POR_ID = D.SERVICE_POINT_ID
	AND A.POD_ID = E.SERVICE_POINT_ID
	AND A.COMMODITY_ID = F.COMMODITY_ID
	AND A.TRANSACTION_ID = G.TRANSACTION_ID;
