CREATE OR REPLACE PROCEDURE CDI_STORE_FILE_CONTENT(p_FILE_NAME IN VARCHAR2, p_FILE_CONTENT IN CLOB) AS
BEGIN
   DELETE CLOB_STAGING WHERE CLOB_IDENT = p_FILE_NAME;
   INSERT INTO CLOB_STAGING(CLOB_IDENT, CLOB_VAL)
   VALUES(p_FILE_NAME, p_FILE_CONTENT);
   COMMIT;
END CDI_STORE_FILE_CONTENT;
/
