CREATE OR REPLACE VIEW CDI_AGGREGATE_ACCOUNT$ AS
SELECT X.RTO_ACCOUNT_ID "ACCOUNT_IDENTIFIER", X.SUPPLIER "ESP_IDENTIFIER", X.RTO_POOL_ID "POOL_IDENTIFIER", X.BEGIN_DATE, X.END_DATE, X.CUSTOMER_COUNT "SERVICE_ACCOUNTS", X.USAGE_FACTOR, A.ACCOUNT_ID, E.ESP_ID, P.POOL_ID, G.AGGREGATE_ID
FROM CDI_AGGREGATE_ACCOUNTS          X
   LEFT JOIN ACCOUNT                 A ON A.ACCOUNT_EXTERNAL_IDENTIFIER = X.RTO_ACCOUNT_ID
   LEFT JOIN ENERGY_SERVICE_PROVIDER E ON E.ESP_EXTERNAL_IDENTIFIER = X.SUPPLIER
   LEFT JOIN POOL                    P ON P.POOL_EXTERNAL_IDENTIFIER = X.RTO_POOL_ID
   LEFT JOIN AGGREGATE_ACCOUNT_ESP   G ON G.ACCOUNT_ID = A.ACCOUNT_ID AND G.ESP_ID = E.ESP_ID AND G.POOL_ID = P.POOL_ID;