-- Revision: $Revision: 1.2 $
-- NOTE: This script is AUTO-GENERATED
-- The script is call ED_IDX.sql and is stored in Database/MAIN/System
-- It is called to create indexes on the ENTRY_DATE column of every entity,
-- excluding those that have IDs = 0 and DATA_LOCK)GROUP as it does not have
-- a ENTRY_DATE column

CREATE INDEX ACCOUNT_IX_ED ON
              ACCOUNT(ENTRY_DATE);
CREATE INDEX ACCOUNT_GROUP_IX_ED ON
              ACCOUNT_GROUP(ENTRY_DATE);
CREATE INDEX ANCILLARY_SERVICE_IX_ED ON
              ANCILLARY_SERVICE(ENTRY_DATE);
CREATE INDEX AREA_IX_ED ON
              AREA(ENTRY_DATE);
CREATE INDEX BILL_CYCLE_IX_ED ON
              BILL_CYCLE(ENTRY_DATE);
CREATE INDEX BILL_PARTY_IX_ED ON
              BILL_PARTY(ENTRY_DATE);
CREATE INDEX CONTROL_AREA_IX_ED ON
              CONTROL_AREA(ENTRY_DATE);
CREATE INDEX CALCULATION_PROCESS_IX_ED ON
              CALCULATION_PROCESS(ENTRY_DATE);
CREATE INDEX CALENDAR_IX_ED ON
              CALENDAR(ENTRY_DATE);
CREATE INDEX CASE_LABEL_IX_ED ON
              CASE_LABEL(ENTRY_DATE);
CREATE INDEX CATEGORY_IX_ED ON
              CATEGORY(ENTRY_DATE);
CREATE INDEX COMPONENT_IX_ED ON
              COMPONENT(ENTRY_DATE);
CREATE INDEX CONDITIONAL_FORMAT_IX_ED ON
              CONDITIONAL_FORMAT(ENTRY_DATE);
CREATE INDEX CONTACT_IX_ED ON
              CONTACT(ENTRY_DATE);
CREATE INDEX SERVICE_CONTRACT_IX_ED ON
              SERVICE_CONTRACT(ENTRY_DATE);
CREATE INDEX CONTRACT_LIMIT_IX_ED ON
              CONTRACT_LIMIT(ENTRY_DATE);
CREATE INDEX CUSTOMER_IX_ED ON
              CUSTOMER(ENTRY_DATE);
CREATE INDEX DISTRIBUTED_ENERGY_RESOU_IX_ED ON
              DISTRIBUTED_ENERGY_RESOURCE(ENTRY_DATE);
CREATE INDEX DER_TYPE_IX_ED ON
              DER_TYPE(ENTRY_DATE);
CREATE INDEX DR_EVENT_IX_ED ON
              DR_EVENT(ENTRY_DATE);
CREATE INDEX ENERGY_DISTRIBUTION_COMP_IX_ED ON
              ENERGY_DISTRIBUTION_COMPANY(ENTRY_DATE);
CREATE INDEX ENTITY_DOMAIN_IX_ED ON
              ENTITY_DOMAIN(ENTRY_DATE);
CREATE INDEX ENTITY_GROUP_IX_ED ON
              ENTITY_GROUP(ENTRY_DATE);
CREATE INDEX ENERGY_SERVICE_PROVIDER_IX_ED ON
              ENERGY_SERVICE_PROVIDER(ENTRY_DATE);
CREATE INDEX ETAG_IX_ED ON
              ETAG(ENTRY_DATE);
CREATE INDEX EXTERNAL_SYSTEM_IX_ED ON
              EXTERNAL_SYSTEM(ENTRY_DATE);
CREATE INDEX INTERCHANGE_TRANSACTION__IX_ED ON
              INTERCHANGE_TRANSACTION_EXT(ENTRY_DATE);
CREATE INDEX GEOGRAPHY_IX_ED ON
              GEOGRAPHY(ENTRY_DATE);
CREATE INDEX GROWTH_PATTERN_IX_ED ON
              GROWTH_PATTERN(ENTRY_DATE);
CREATE INDEX HEAT_RATE_CURVE_IX_ED ON
              HEAT_RATE_CURVE(ENTRY_DATE);
CREATE INDEX HOLIDAY_IX_ED ON
              HOLIDAY(ENTRY_DATE);
CREATE INDEX HOLIDAY_SET_IX_ED ON
              HOLIDAY_SET(ENTRY_DATE);
CREATE INDEX INTERCHANGE_CONTRACT_IX_ED ON
              INTERCHANGE_CONTRACT(ENTRY_DATE);
CREATE INDEX INVOICE_GROUP_IX_ED ON
              INVOICE_GROUP(ENTRY_DATE);
CREATE INDEX IT_COMMODITY_IX_ED ON
              IT_COMMODITY(ENTRY_DATE);
CREATE INDEX JOB_THREAD_IX_ED ON
              JOB_THREAD(ENTRY_DATE);
CREATE INDEX LOAD_PROFILE_IX_ED ON
              LOAD_PROFILE(ENTRY_DATE);
CREATE INDEX LOAD_PROFILE_LIBRARY_IX_ED ON
              LOAD_PROFILE_LIBRARY(ENTRY_DATE);
CREATE INDEX LOSS_FACTOR_IX_ED ON
              LOSS_FACTOR(ENTRY_DATE);
CREATE INDEX MARKET_PRICE_IX_ED ON
              MARKET_PRICE(ENTRY_DATE);
CREATE INDEX MEASUREMENT_SOURCE_IX_ED ON
              MEASUREMENT_SOURCE(ENTRY_DATE);
CREATE INDEX METER_IX_ED ON
              METER(ENTRY_DATE);
CREATE INDEX METER_READING_SERVICE_PR_IX_ED ON
              METER_READING_SERVICE_PROVIDER(ENTRY_DATE);
CREATE INDEX OASIS_NODE_IX_ED ON
              OASIS_NODE(ENTRY_DATE);
CREATE INDEX TX_PATH_IX_ED ON
              TX_PATH(ENTRY_DATE);
CREATE INDEX PERIOD_IX_ED ON
              PERIOD(ENTRY_DATE);
CREATE INDEX PIPELINE_IX_ED ON
              PIPELINE(ENTRY_DATE);
CREATE INDEX POOL_IX_ED ON
              POOL(ENTRY_DATE);
CREATE INDEX PORTFOLIO_IX_ED ON
              PORTFOLIO(ENTRY_DATE);
CREATE INDEX PRODUCT_IX_ED ON
              PRODUCT(ENTRY_DATE);
CREATE INDEX PROGRAM_IX_ED ON
              PROGRAM(ENTRY_DATE);
CREATE INDEX PROXY_DAY_METHOD_IX_ED ON
              PROXY_DAY_METHOD(ENTRY_DATE);
CREATE INDEX PURCHASING_SELLING_ENTIT_IX_ED ON
              PURCHASING_SELLING_ENTITY(ENTRY_DATE);
CREATE INDEX QUOTE_REQUEST_IX_ED ON
              QUOTE_REQUEST(ENTRY_DATE);
CREATE INDEX REACTOR_PROCEDURE_IX_ED ON
              REACTOR_PROCEDURE(ENTRY_DATE);
CREATE INDEX SUPPLY_RESOURCE_GROUP_IX_ED ON
              SUPPLY_RESOURCE_GROUP(ENTRY_DATE);
CREATE INDEX SCHEDULE_COORDINATOR_IX_ED ON
              SCHEDULE_COORDINATOR(ENTRY_DATE);
CREATE INDEX SCENARIO_IX_ED ON
              SCENARIO(ENTRY_DATE);
CREATE INDEX SCHEDULE_GROUP_IX_ED ON
              SCHEDULE_GROUP(ENTRY_DATE);
CREATE INDEX SEASON_IX_ED ON
              SEASON(ENTRY_DATE);
CREATE INDEX TX_SEGMENT_IX_ED ON
              TX_SEGMENT(ENTRY_DATE);
CREATE INDEX SERVICE_AREA_IX_ED ON
              SERVICE_AREA(ENTRY_DATE);
CREATE INDEX SERVICE_LOCATION_IX_ED ON
              SERVICE_LOCATION(ENTRY_DATE);
CREATE INDEX SERVICE_POINT_IX_ED ON
              SERVICE_POINT(ENTRY_DATE);
CREATE INDEX SERVICE_REGION_IX_ED ON
              SERVICE_REGION(ENTRY_DATE);
CREATE INDEX TX_SERVICE_TYPE_IX_ED ON
              TX_SERVICE_TYPE(ENTRY_DATE);
CREATE INDEX SERVICE_ZONE_IX_ED ON
              SERVICE_ZONE(ENTRY_DATE);
CREATE INDEX SETTLEMENT_TYPE_IX_ED ON
              SETTLEMENT_TYPE(ENTRY_DATE);
CREATE INDEX STATEMENT_TYPE_IX_ED ON
              STATEMENT_TYPE(ENTRY_DATE);
CREATE INDEX TX_SUB_STATION_IX_ED ON
              TX_SUB_STATION(ENTRY_DATE);
CREATE INDEX TX_SUB_STATION_METER_IX_ED ON
              TX_SUB_STATION_METER(ENTRY_DATE);
CREATE INDEX TX_SUB_STATION_METER_POI_IX_ED ON
              TX_SUB_STATION_METER_POINT(ENTRY_DATE);
CREATE INDEX SUPPLY_RESOURCE_IX_ED ON
              SUPPLY_RESOURCE(ENTRY_DATE);
CREATE INDEX SYSTEM_ACTION_IX_ED ON
              SYSTEM_ACTION(ENTRY_DATE);
CREATE INDEX SYSTEM_ALERT_IX_ED ON
              SYSTEM_ALERT(ENTRY_DATE);
CREATE INDEX SYSTEM_EVENT_IX_ED ON
              SYSTEM_EVENT(ENTRY_DATE);
CREATE INDEX SYSTEM_LOAD_IX_ED ON
              SYSTEM_LOAD(ENTRY_DATE);
CREATE INDEX SYSTEM_REALM_IX_ED ON
              SYSTEM_REALM(ENTRY_DATE);
CREATE INDEX SYSTEM_TABLE_IX_ED ON
              SYSTEM_TABLE(ENTRY_DATE);
CREATE INDEX TEMPLATE_IX_ED ON
              TEMPLATE(ENTRY_DATE);
CREATE INDEX TRANSMISSION_PROVIDER_IX_ED ON
              TRANSMISSION_PROVIDER(ENTRY_DATE);
CREATE INDEX INTERCHANGE_TRANSACTION_IX_ED ON
              INTERCHANGE_TRANSACTION(ENTRY_DATE);
CREATE INDEX TRANSACTION_TRAIT_GROUP_IX_ED ON
              TRANSACTION_TRAIT_GROUP(ENTRY_DATE);
CREATE INDEX TX_FEEDER_IX_ED ON
              TX_FEEDER(ENTRY_DATE);
CREATE INDEX TX_FEEDER_SEGMENT_IX_ED ON
              TX_FEEDER_SEGMENT(ENTRY_DATE);
CREATE INDEX VIRTUAL_POWER_PLANT_IX_ED ON
              VIRTUAL_POWER_PLANT(ENTRY_DATE);
CREATE INDEX WEATHER_PARAMETER_IX_ED ON
              WEATHER_PARAMETER(ENTRY_DATE);
CREATE INDEX WEATHER_STATION_IX_ED ON
              WEATHER_STATION(ENTRY_DATE);


