-- CVS Revision: $Revision: 1.9 $

--TRUNCATE TABLE EXTERNAL_SYSTEM;

set define off

DECLARE
	PROCEDURE INSERT_INTO_EXTERNAL_SYSTEM
		(
		p_EXTERNAL_SYSTEM_ID IN NUMBER,
		p_EXTERNAL_SYSTEM_NAME IN VARCHAR2,
		p_EXTERNAL_SYSTEM_TYPE IN VARCHAR2,
		p_IS_ENABLED IN NUMBER,
		p_HAS_UNAME_PWD_CREDENTIALS IN NUMBER,
		p_NUMBER_OF_CERTIFICATES IN NUMBER,
		p_EXTERNAL_ACCOUNT_DOMAIN_ID IN NUMBER := EC.ED_INTERCHANGE_CONTRACT,
		p_EXTERNAL_SYSTEM_ALIAS IN VARCHAR2 := NULL,
		p_EXTERNAL_SYSTEM_DESC IN VARCHAR2 := NULL,
		p_EXTERNAL_SYSTEM_DISPLAY_NAME IN VARCHAR2 := NULL
		) AS
	BEGIN
		INSERT INTO EXTERNAL_SYSTEM
			(EXTERNAL_SYSTEM_ID, EXTERNAL_SYSTEM_NAME, EXTERNAL_SYSTEM_ALIAS, EXTERNAL_SYSTEM_DESC, 
			EXTERNAL_SYSTEM_TYPE, EXTERNAL_SYSTEM_DISPLAY_NAME, IS_ENABLED, EXTERNAL_ACCOUNT_DOMAIN_ID,
			HAS_UNAME_PWD_CREDENTIALS, NUMBER_OF_CERTIFICATES, ENTRY_DATE)
		VALUES
			(p_EXTERNAL_SYSTEM_ID, p_EXTERNAL_SYSTEM_NAME, p_EXTERNAL_SYSTEM_ALIAS, p_EXTERNAL_SYSTEM_DESC, 
			p_EXTERNAL_SYSTEM_TYPE, NVL(p_EXTERNAL_SYSTEM_DISPLAY_NAME, p_EXTERNAL_SYSTEM_NAME), p_IS_ENABLED, p_EXTERNAL_ACCOUNT_DOMAIN_ID,
			p_HAS_UNAME_PWD_CREDENTIALS, p_NUMBER_OF_CERTIFICATES, 
			SYSDATE);
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX
			THEN NULL; --Do not bother with updates.  Just do inserts.
	END;
BEGIN
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_IMO, 'IMO', 'ISO', 0, 0, 1); 	
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_MISO, 'MISO', 'ISO', 0, 0, 1); 
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_NYISO, 'NYISO', 'ISO', 0, 1, 1); 
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_PJM, 'PJM', 'ISO', 0, 1, 1); 
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_OASIS, 'OASIS', 'ISO', 0, 0, 1, EC.ED_OASIS_NODE); 
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_ISONE, 'ISONE', 'ISO', 0, 1, 0); 
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_ERCOT, 'ERCOT', 'ISO', 0, 1, 0); 
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_MEX_SWITCHBOARD, 'MEX Switchboard', 'Other', 0, 1, 0, 0);
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_SMTP, 'SMTP Server', 'Other', 0, 1, 0, 0);
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_SEM, 'SEM', 'ISO', 0, 1, 1);
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_TDIE, 'Irish T&D', 'ISO', 0, 0, 0, 0);
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_TSIN, 'TSIN', 'ISO', 0, 0, 0);
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_MONACO, 'Monaco', 'Other', 0, 0, 0, 0);
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_NYISO_DSS, 'NYISO-DSS', 'ISO', 0, 1, 1);
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_SMART_GRID, 'Smart Grid', 'DERMS', 0, 1, 0, 0);
	INSERT_INTO_EXTERNAL_SYSTEM(EC.ES_SCHEDULE_MANAGEMENT, 'Schedule Management', 'Other', 0, 0, 0, 0);
END;
/

COMMIT;

set define on