-- Packages that should *not* be granted to user schemas
---------------------------------------------------------
BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'GA');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'EI');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'ID');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'ML');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'SECURITY_CONTROLS');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'MM_UTIL');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'MM_%_UTIL');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'MEX_%');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'RO');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'Z%');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'ALERTS');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'LOGS');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'ERRS');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'MUTEX');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'JOB_PROGRAMS');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'REACTOR');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'DATA_LOCK');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'ENTITY_UTIL');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'DEMAND_RESPONSE_UTIL');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'PROGRAM_BILLING');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'LOG_UTIL');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'SCHEDULE_MANAGEMENT_SYNC');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'SCHEDULE_MANAGEMENT_REACTOR');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PACKAGE', 'MESSAGES');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

-- Procedures that should *not* be granted to user schemas
---------------------------------------------------------
BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PROCEDURE', 'RECOMPILE_INVALID_OBJECTS');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PROCEDURE', 'PERFORM_GRANTS');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PROCEDURE', 'POST_APP_EVENT');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PROCEDURE', 'POST_TO_APP_EVENT_LOG');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PROCEDURE', 'PUT_DICTIONARY_VALUE');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PROCEDURE', 'PUT_MODEL_VALUE_AT_KEY');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PROCEDURE', 'PUT_VALUE_AT_KEY');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PROCEDURE', 'PUT_VALUE_AT_KEY_3');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PROCEDURE', 'ASSERT');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PROCEDURE', 'SET_SYSTEM_STATE');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('PROCEDURE', 'ZRE_%');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

-- Functions that should *not* be granted to user schemas
---------------------------------------------------------
BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('FUNCTION', 'LIST_EXECUTE_GRANTS');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('FUNCTION', 'LIST_OBJECT_GRANTS');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('FUNCTION', 'LIST_REVOKES');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO GRANT_EXECUTE_EXCLUSIONS(OBJECT_TYPE, OBJECT_NAME)
	VALUES ('FUNCTION', 'GET_SYSTEM_STATE_%');
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

