prompt SEQUENCE
@@SEQUENCE.sql
prompt NOT_ASSIGNED
@@NOT_ASSIGNED.sql
prompt ANYTIME_TEMPLATE
@@ANYTIME_TEMPLATE.sql
prompt DOMAIN
@@ENTITY_DOMAIN.sql
prompt NERO_TABLE_PROPERTY_INDEX
@@NERO_TABLE_PROPERTY_INDEX.sql
prompt NERO_TABLE_PROPERTY_INDEX
@@NERO_TABLE_PROPERTY_INDEX.dat
prompt RTO_WORK
@@RTO_WORK.sql
prompt TRACE
@@TRACE.sql
prompt ALTERNATE_KEY_INDEX
@@ALTERNATE_KEY_INDEX.sql
prompt STATUS_NAMES
@@STATUS_NAMES.sql
prompt EDC_SETTLEMENT_AGENT
@@EDC_SETTLEMENT_AGENT.sql
prompt SYSTEM_DICTIONARY
@@SYSTEM_DICTIONARY.sql
prompt SYSTEM_LABEL
@@SYSTEM_LABEL.sql
prompt SYNONYMS
@@SYNONYMS.sql
prompt SETUP
@@SETUP.sql
prompt RTO_VERSION
@@RTO_VERSION.sql
prompt VIEWS
@@VIEWS.sql
