-- JOB THREADS
BEGIN
	INSERT INTO JOB_THREAD (JOB_THREAD_ID, JOB_THREAD_NAME, JOB_THREAD_ALIAS, JOB_THREAD_DESC, JOB_CLASS, IS_SNOOZED, ENTRY_DATE)
	VALUES (1, 'Default', 'Default', 'Default', '', 0, SYSDATE);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        NULL;
END;
/

-- Reactor Information for Schedule Management
DECLARE
	v_TABLE_ID NUMBER(9);
BEGIN
	-- Get the System Table ID for Schedule Data 
	SELECT TABLE_ID INTO v_TABLE_ID
	FROM SYSTEM_TABLE
	WHERE TABLE_NAME = 'Schedule Data';

	-- Reactor Procedures
	BEGIN
		INSERT INTO REACTOR_PROCEDURE (REACTOR_PROCEDURE_ID, REACTOR_PROCEDURE_NAME, REACTOR_PROCEDURE_ALIAS, REACTOR_PROCEDURE_DESC, TABLE_ID, PROCEDURE_NAME, JOB_THREAD_ID, JOB_COMMENTS, CALL_ORDER, SKIP_WHEN_FORMULA, TIME_ZONE, IS_IMMEDIATE, IS_ENABLED, ENTRY_DATE)
		VALUES (1, 'Schedule Management Init', '?', '?', v_TABLE_ID, 'SCHEDULE_MANAGEMENT_REACTOR.RESET', 1, '', 0, 'NOT UT.BOOLEAN_FROM_NUMBER(GUI_UTIL.IS_EXTERNAL_SYSTEM_ENABLED(EC.ES_SCHEDULE_MANAGEMENT))', '', 1, 1, SYSDATE);
	EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;
	
	BEGIN
		INSERT INTO REACTOR_PROCEDURE (REACTOR_PROCEDURE_ID, REACTOR_PROCEDURE_NAME, REACTOR_PROCEDURE_ALIAS, REACTOR_PROCEDURE_DESC, TABLE_ID, PROCEDURE_NAME, JOB_THREAD_ID, JOB_COMMENTS, CALL_ORDER, SKIP_WHEN_FORMULA, TIME_ZONE, IS_IMMEDIATE, IS_ENABLED, ENTRY_DATE)
		VALUES (2, 'Schedule Management Queue', '?', '?', v_TABLE_ID, 'SCHEDULE_MANAGEMENT_REACTOR.QUEUE_RECORD', 1, '', 1, 'NOT UT.BOOLEAN_FROM_NUMBER(GUI_UTIL.IS_EXTERNAL_SYSTEM_ENABLED(EC.ES_SCHEDULE_MANAGEMENT))', '', 1, 1, SYSDATE);
	EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;
	
	BEGIN
		INSERT INTO REACTOR_PROCEDURE (REACTOR_PROCEDURE_ID, REACTOR_PROCEDURE_NAME, REACTOR_PROCEDURE_ALIAS, REACTOR_PROCEDURE_DESC, TABLE_ID, PROCEDURE_NAME, JOB_THREAD_ID, JOB_COMMENTS, CALL_ORDER, SKIP_WHEN_FORMULA, TIME_ZONE, IS_IMMEDIATE, IS_ENABLED, ENTRY_DATE)
		VALUES (3, 'Schedule Management Process', '?', '?', v_TABLE_ID, 'SCHEDULE_MANAGEMENT_REACTOR.PROCESS_QUEUE', 1, '', 2, 'NOT UT.BOOLEAN_FROM_NUMBER(GUI_UTIL.IS_EXTERNAL_SYSTEM_ENABLED(EC.ES_SCHEDULE_MANAGEMENT))', '', 1, 1, SYSDATE);
	EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;
	
	BEGIN
		INSERT INTO REACTOR_PROCEDURE (REACTOR_PROCEDURE_ID, REACTOR_PROCEDURE_NAME, REACTOR_PROCEDURE_ALIAS, REACTOR_PROCEDURE_DESC, TABLE_ID, PROCEDURE_NAME, JOB_THREAD_ID, JOB_COMMENTS, CALL_ORDER, SKIP_WHEN_FORMULA, TIME_ZONE, IS_IMMEDIATE, IS_ENABLED, ENTRY_DATE)
		VALUES (4, 'Schedule Management Submit', '?', '?', v_TABLE_ID, 'SCHEDULE_MANAGEMENT_REACTOR.SUBMIT', 1, '', 3, 'NOT UT.BOOLEAN_FROM_NUMBER(GUI_UTIL.IS_EXTERNAL_SYSTEM_ENABLED(EC.ES_SCHEDULE_MANAGEMENT))', '', 0, 1, SYSDATE);
	EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;
	
	-- Reactor Procedure Input
	BEGIN
		INSERT INTO REACTOR_PROCEDURE_INPUT (REACTOR_PROCEDURE_ID, ENTITY_DOMAIN_ID, ENTITY_TYPE, ENTITY_ID, BEGIN_DATE, END_DATE)
		VALUES (1, EC.ED_TRANSACTION, 'R', 1, LOW_DATE, null);
	EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;
	
	BEGIN
		INSERT INTO REACTOR_PROCEDURE_INPUT (REACTOR_PROCEDURE_ID, ENTITY_DOMAIN_ID, ENTITY_TYPE, ENTITY_ID, BEGIN_DATE, END_DATE)
		VALUES (2, EC.ED_TRANSACTION, 'R', 1, LOW_DATE, null);
	EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;
	
	BEGIN
		INSERT INTO REACTOR_PROCEDURE_INPUT (REACTOR_PROCEDURE_ID, ENTITY_DOMAIN_ID, ENTITY_TYPE, ENTITY_ID, BEGIN_DATE, END_DATE)
		VALUES (3, EC.ED_TRANSACTION, 'R', 1, LOW_DATE, null);
	EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;
	
	BEGIN
		INSERT INTO REACTOR_PROCEDURE_INPUT (REACTOR_PROCEDURE_ID, ENTITY_DOMAIN_ID, ENTITY_TYPE, ENTITY_ID, BEGIN_DATE, END_DATE)
		VALUES (4, EC.ED_TRANSACTION, 'R', 1, LOW_DATE, null);
	EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;
	
	-- Reactor Procedure Parameter for 'Schedule Management Queue'
	BEGIN	
		INSERT INTO REACTOR_PROCEDURE_PARAMETER (REACTOR_PROCEDURE_ID, PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_FORMULA, PARAMETER_ORDER)
		VALUES (2, 'P_TRANSACTION_ID', 'Key', 'TRANSACTION_ID', 1);
		EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;

	BEGIN
		INSERT INTO REACTOR_PROCEDURE_PARAMETER (REACTOR_PROCEDURE_ID, PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_FORMULA, PARAMETER_ORDER)
		VALUES (2, 'P_STATEMENT_TYPE_ID', 'Key', 'SCHEDULE_TYPE', 2);
		EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;

	BEGIN
		INSERT INTO REACTOR_PROCEDURE_PARAMETER (REACTOR_PROCEDURE_ID, PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_FORMULA, PARAMETER_ORDER)
		VALUES (2, 'P_SCHEDULE_STATE', 'Key', 'SCHEDULE_STATE', 3);
		EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;

	BEGIN
		INSERT INTO REACTOR_PROCEDURE_PARAMETER (REACTOR_PROCEDURE_ID, PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_FORMULA, PARAMETER_ORDER)
		VALUES (2, 'P_SCHEDULE_DATE', 'Key', 'SCHEDULE_DATE', 4);
		EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;
	
	-- Reactor Procedure Parameter for 'Schedule Management Submit'
	BEGIN
		INSERT INTO REACTOR_PROCEDURE_PARAMETER (REACTOR_PROCEDURE_ID, PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_FORMULA, PARAMETER_ORDER)
		VALUES (4, 'P_BG_LOB_ID', 'Lazy', 'SCHEDULE_MANAGEMENT_REACTOR.GET_BG_LOB_ID', 1);
		EXCEPTION
			WHEN DUP_VAL_ON_INDEX THEN
					NULL;
	END;
END;
/
