CREATE USER RTO_ADMIN IDENTIFIED BY RTO_ADMIN;
ALTER USER RTO_ADMIN TEMPORARY TABLESPACE TEMP_DATA;
ALTER USER RTO_ADMIN DEFAULT TABLESPACE NERO_DATA;
GRANT CONNECT, RESOURCE, CREATE USER, DROP USER TO RTO_ADMIN WITH ADMIN OPTION;
GRANT SELECT ON SYS.V_$SESSION TO RTO_ADMIN;

