-- jcooper, 21-nov-2005: fix for bz 9742, we shouldn't change existing records in INTERCHANGE_TRANSACTION_STATUS

--TRUNCATE TABLE ACCOUNT_STATUS_NAME;
BEGIN
INSERT INTO ACCOUNT_STATUS_NAME (STATUS_NAME,IS_ACTIVE) VALUES ('Inactive',0);
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
INSERT INTO ACCOUNT_STATUS_NAME (STATUS_NAME,IS_ACTIVE) VALUES ('Active',1);
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

--TRUNCATE TABLE INTERCHANGE_TRANSACTION_STATUS;
BEGIN
INSERT INTO INTERCHANGE_TRANSACTION_STATUS (TRANSACTION_STATUS_NAME,TRANSACTION_IS_ACTIVE) VALUES ('Active',1);
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
INSERT INTO INTERCHANGE_TRANSACTION_STATUS (TRANSACTION_STATUS_NAME,TRANSACTION_IS_ACTIVE) VALUES ('Inactive',0);
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
