-- create from the sys account
CREATE USER CDI_ADMIN
  IDENTIFIED BY CDI_ADMIN
  DEFAULT TABLESPACE NERO_DATA
  TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO CDI_ADMIN;
GRANT DEBUG CONNECT SESSION TO CDI_ADMIN;
GRANT CREATE TABLE TO CDI_ADMIN;
GRANT CREATE TRIGGER TO CDI_ADMIN;
GRANT CREATE VIEW TO CDI_ADMIN;
GRANT CREATE SEQUENCE TO CDI_ADMIN;
GRANT CREATE TYPE TO CDI_ADMIN;
GRANT CREATE SYNONYM TO CDI_ADMIN;
GRANT CREATE PROCEDURE TO CDI_ADMIN;
GRANT CREATE JOB TO CDI_ADMIN;
GRANT CREATE DIRECTORY TO CDI_ADMIN;

GRANT SELECT ON SYS.V$LOCK TO CDI_ADMIN;
GRANT SELECT ON SYS.V$PX_PROCESS TO CDI_ADMIN;
GRANT SELECT ON SYS.V$SESSION TO CDI_ADMIN;

GRANT EXECUTE ON SYS.DBMS_LOCK TO CDI_ADMIN;

GRANT UNLIMITED TABLESPACE TO CDI_ADMIN;
GRANT JAVAUSERPRIV TO CDI_ADMIN;
GRANT JAVASYSPRIV TO CDI_ADMIN;

ALTER USER CDI_ADMIN QUOTA UNLIMITED ON NERO_DATA;
ALTER USER CDI_ADMIN QUOTA UNLIMITED ON NERO_INDEX;
ALTER USER CDI_ADMIN QUOTA UNLIMITED ON NERO_LARGE_DATA;
ALTER USER CDI_ADMIN QUOTA UNLIMITED ON NERO_LARGE_INDEX;

GRANT SELECT ANY DICTIONARY TO CDI_ADMIN;
