BEGIN
	INSERT INTO SEASON(SEASON_ID,SEASON_NAME,SEASON_ALIAS,SEASON_DESC,BEGIN_DATE,END_DATE,ENTRY_DATE)
	VALUES(1,'Anytime','Anytime','Anytime',DATE '1900-01-01',DATE '1900-12-31',SYSDATE);
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO PERIOD(PERIOD_ID,PERIOD_NAME,PERIOD_ALIAS,PERIOD_DESC,PERIOD_COLOR,ENTRY_DATE) VALUES(1,'Anytime','Anytime','Anytime',8454143,SYSDATE);
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO TEMPLATE(TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_ALIAS, TEMPLATE_DESC,
	IS_DAY_TYPE, IS_DST_OBSERVANT, ENTRY_DATE) VALUES(1,'Anytime','Anytime','Anytime',1, 0, SYSDATE);
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

BEGIN
	INSERT INTO TEMPLATE(TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_ALIAS, TEMPLATE_DESC,
	IS_DAY_TYPE, IS_DST_OBSERVANT, ENTRY_DATE) VALUES(5,'Anytime TOU Template','Anytime TOU Template','Anytime TOU Template',0, 1, SYSDATE);
EXCEPTION
	WHEN DUP_VAL_ON_INDEX THEN
		NULL;
END;
/

DELETE TEMPLATE_SEASON_DAY_NAME WHERE TEMPLATE_ID = 1;
INSERT INTO TEMPLATE_SEASON_DAY_NAME (TEMPLATE_ID, SEASON_ID, DAY_NAME, ENTRY_DATE) VALUES (1, 1, 'Mon', SYSDATE);
INSERT INTO TEMPLATE_SEASON_DAY_NAME (TEMPLATE_ID, SEASON_ID, DAY_NAME, ENTRY_DATE) VALUES (1, 1, 'Tue', SYSDATE);
INSERT INTO TEMPLATE_SEASON_DAY_NAME (TEMPLATE_ID, SEASON_ID, DAY_NAME, ENTRY_DATE) VALUES (1, 1, 'Wed', SYSDATE);
INSERT INTO TEMPLATE_SEASON_DAY_NAME (TEMPLATE_ID, SEASON_ID, DAY_NAME, ENTRY_DATE) VALUES (1, 1, 'Thu', SYSDATE);
INSERT INTO TEMPLATE_SEASON_DAY_NAME (TEMPLATE_ID, SEASON_ID, DAY_NAME, ENTRY_DATE) VALUES (1, 1, 'Fri', SYSDATE);
INSERT INTO TEMPLATE_SEASON_DAY_NAME (TEMPLATE_ID, SEASON_ID, DAY_NAME, ENTRY_DATE) VALUES (1, 1, 'Sat', SYSDATE);
INSERT INTO TEMPLATE_SEASON_DAY_NAME (TEMPLATE_ID, SEASON_ID, DAY_NAME, ENTRY_DATE) VALUES (1, 1, 'Sun', SYSDATE);
INSERT INTO TEMPLATE_SEASON_DAY_NAME (TEMPLATE_ID, SEASON_ID, DAY_NAME, ENTRY_DATE) VALUES (1, 1, 'Hol', SYSDATE);

DELETE SEASON_TEMPLATE WHERE TEMPLATE_ID = 5;
INSERT INTO SEASON_TEMPLATE (TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES (5, 1, 'Mon', '00:00:01', '24:00:00', 1, SYSDATE);
INSERT INTO SEASON_TEMPLATE (TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES (5, 1, 'Tue', '00:00:01', '24:00:00', 1, SYSDATE);
INSERT INTO SEASON_TEMPLATE (TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES (5, 1, 'Wed', '00:00:01', '24:00:00', 1, SYSDATE);
INSERT INTO SEASON_TEMPLATE (TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES (5, 1, 'Thu', '00:00:01', '24:00:00', 1, SYSDATE);
INSERT INTO SEASON_TEMPLATE (TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES (5, 1, 'Fri', '00:00:01', '24:00:00', 1, SYSDATE);
INSERT INTO SEASON_TEMPLATE (TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES (5, 1, 'Sat', '00:00:01', '24:00:00', 1, SYSDATE);
INSERT INTO SEASON_TEMPLATE (TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES (5, 1, 'Sun', '00:00:01', '24:00:00', 1, SYSDATE);
INSERT INTO SEASON_TEMPLATE (TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES (5, 1, 'Hol', '00:00:01', '24:00:00', 1, SYSDATE);

DECLARE
	v_MESSAGE VARCHAR2(2000);
BEGIN
	EM.VALIDATE_TOU_TEMPLATE(5, v_MESSAGE);
EXCEPTION
	WHEN OTHERS THEN
		NULL;
END;
/
