DELETE SYSTEM_DICTIONARY WHERE MODEL_ID = 0 AND MODULE = '?' AND KEY1 = '?' AND KEY2 = '?' AND KEY3 = '?' AND SETTING_NAME = 'RTO_VERSION';
INSERT INTO SYSTEM_DICTIONARY (MODEL_ID, MODULE, KEY1, KEY2, KEY3, SETTING_NAME, VALUE) VALUES(0, '?', '?', '?', '?', 'RTO_VERSION', '5.7.0.0');
                                                            
