DEFINE RTO_STAGING_SCHEMA = RTO_STAGING
DEFINE RTO_ADMIN_SCHEMA = RTO_ADMIN

-- Connect As DBA --
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..STUDYID_EXCEPTION_LOOKUP TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..PBS_CUSTOMER_LOOKUP_VIEW TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..CIS_CCB_CONVERSION TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..CIS_CCB_CONVERSION_TYPE TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..BANKRUPTCY_CROSSREF TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..CUSTOMER_INFO_STAGING TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..MONTHLY_ENERGY_STAGING TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..ALM_EVENTS_DETAILS TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..PLC_ICAP_INT_VALUE TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..PLC_TX_INT_VALUE TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..AMI_USAGE TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..BGE_CI_STAGING TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..SYSTEM_LOAD_ID_LOOKUP TO &&RTO_ADMIN_SCHEMA;
GRANT SELECT, INSERT, UPDATE, DELETE ON &&RTO_STAGING_SCHEMA..COMM_SOLAR_GEN TO &&RTO_ADMIN_SCHEMA;

DEFINE RTO_STAGING_SCHEMA = RTO_STAGING
DEFINE RTO_ADMIN_SCHEMA = RTO_ADMIN

CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..STUDYID_EXCEPTION_LOOKUP FOR &&RTO_STAGING_SCHEMA..STUDYID_EXCEPTION_LOOKUP;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..PBS_CUSTOMER_LOOKUP_VIEW FOR &&RTO_STAGING_SCHEMA..PBS_CUSTOMER_LOOKUP_VIEW;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..CIS_CCB_CONVERSION FOR &&RTO_STAGING_SCHEMA..CIS_CCB_CONVERSION;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..CIS_CCB_CONVERSION_TYPE FOR &&RTO_STAGING_SCHEMA..CIS_CCB_CONVERSION_TYPE;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..BANKRUPTCY_CROSSREF FOR &&RTO_STAGING_SCHEMA..BANKRUPTCY_CROSSREF;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..CUSTOMER_INFO_STAGING FOR &&RTO_STAGING_SCHEMA..CUSTOMER_INFO_STAGING;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..MONTHLY_ENERGY_STAGING FOR &&RTO_STAGING_SCHEMA..MONTHLY_ENERGY_STAGING;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..ALM_EVENTS_DETAILS FOR &&RTO_STAGING_SCHEMA..ALM_EVENTS_DETAILS;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..PLC_ICAP_INT_VALUE FOR &&RTO_STAGING_SCHEMA..PLC_ICAP_INT_VALUE;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..PLC_TX_INT_VALUE FOR &&RTO_STAGING_SCHEMA..PLC_TX_INT_VALUE;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..AMI_USAGE FOR &&RTO_STAGING_SCHEMA..AMI_USAGE;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..BGE_CI_STAGING FOR &&RTO_STAGING_SCHEMA..BGE_CI_STAGING;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..SYSTEM_LOAD_ID_LOOKUP FOR &&RTO_STAGING_SCHEMA..SYSTEM_LOAD_ID_LOOKUP;
CREATE OR REPLACE SYNONYM &&RTO_ADMIN_SCHEMA..COMM_SOLAR_GEN FOR &&RTO_STAGING_SCHEMA..COMM_SOLAR_GEN;
