Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('1649', '1650011', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('1649', '1650021', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('1650', '1649031', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8001011', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002010', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002011', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002012', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002013', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002014', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003011', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003012', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003013', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003014', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8004011', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8004021', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8004031', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8006011', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008010', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008011', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008012', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008013', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008014', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8006021', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002021', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008031', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008041', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008042', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002031', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002032', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002041', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002042', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003031', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003032', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003041', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003042', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002033', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002034', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002043', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8002044', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003033', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003034', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003043', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8003044', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008033', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008034', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008043', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008044', '1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008021', '-1');
Insert into STUDYID_EXCEPTION_LOOKUP
   (SEGMENT, STUDY_ID, WEIGHT)
 Values
   ('BSXX', '8008032', '-1');
COMMIT;
