SET DEFINE OFF      
prompt Market: SEM
prompt =================
prompt compiling SEM package specs
prompt =================

prompt OBJECTS  	
@@SEM_Objects.sql

prompt SEQUENCE
@@SEM_Sequences.sql

prompt SEM_MP_UNITS
@@SEM_MP_UNITS.sql

prompt MM_SEM_UTIL
@@MM_SEM_UTIL.sql
		
prompt MM_SEM_OFFER.sql
@@MM_SEM_OFFER.sql

prompt MM_SEM_OFFER_UTIL
@@MM_SEM_OFFER_UTIL.sql

prompt MM_SEM
@@MM_SEM.sql

prompt MM_SEM_GEN_OFFER
@@MM_SEM_GEN_OFFER.sql

prompt MM_SEM_IC_OFFER
@@MM_SEM_IC_OFFER.sql

prompt MM_SEM_LOAD_OFFER
@@MM_SEM_LOAD_OFFER.sql

prompt MM_SEM_REPORTS
@@MM_SEM_REPORTS.sql

prompt MM_SEM_SHADOW_BILL
@@MM_SEM_SHADOW_BILL.sql

prompt MM_SEM_SETTLEMENT_PARSE
@@MM_SEM_SETTLEMENT_PARSE.sql

prompt MM_SEM_SETTLEMENT
@@MM_SEM_SETTLEMENT.sql

prompt MM_SEM_SRA_OFFER
@@MM_SEM_SRA_OFFER.sql

prompt SEM_REPORTS	
@@SEM_REPORTS.sql

prompt SEM_REPORTS_UTIL
@@SEM_REPORTS_UTIL.sql

prompt MM_SEM_CREDIT_SHADOW
@@MM_SEM_CREDIT_SHADOW.sql

prompt SEM_CREDIT_REPORTS
@@SEM_CREDIT_REPORTS.sql

prompt MM_SEM_CFD_UTIL.sql
@@MM_SEM_CFD_UTIL.sql

prompt MM_SEM_CFD_CALC.sql
@@MM_SEM_CFD_CALC.sql

prompt MM_SEM_CFD_UI.sql
@@MM_SEM_CFD_UI.sql

prompt MM_SEM_CFD_CREDIT.sql
@@MM_SEM_CFD_CREDIT.sql

prompt MM_SEM_CFD_REPORTS.sql
@@MM_SEM_CFD_REPORTS.sql

prompt MM_SEM_CFD_ADJUSTMENT.sql
@@MM_SEM_CFD_ADJUSTMENT.sql

prompt MM_SEM_CFD_INV.sql
@@MM_SEM_CFD_INV.sql

prompt MM_SEM_CFD_ALERTS.sql
@@MM_SEM_CFD_ALERTS.sql

prompt MM_SEM_CFD_DIFF_PMTS.sql
@@MM_SEM_CFD_DIFF_PMTS.sql

prompt SEM_CFD_SCHEDULE_FILL.sql
@@SEM_CFD_SCHEDULE_FILL.sql

prompt SEM_SETTLEMENT_COMP.sql
@@SEM_SETTLEMENT_COMP.sql

prompt MM_SEM_TLAF.sql
@@MM_SEM_TLAF.sql

prompt MM_SEM_PIR_IMPORT.sql
@@MM_SEM_PIR_IMPORT.sql

prompt MM_SEM_PIR_IMPORT_UI.sql
@@MM_SEM_PIR_IMPORT_UI.sql

prompt MM_SEM_SETTLEMENT_CALENDAR.sql
@@MM_SEM_SETTLEMENT_CALENDAR.sql

prompt VIEWS  	
@@SEM_VIEWS.sql

SET DEFINE ON  
