PROMPT Drop Table SEM_STATEMENT_H_TEMP
DROP TABLE SEM_STATEMENT_H_TEMP CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_STATEMENT_S_TEMP
DROP TABLE SEM_STATEMENT_S_TEMP CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_STATEMENT_D_TEMP
DROP TABLE SEM_STATEMENT_D_TEMP CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_MP_INFO_H_TEMP
DROP TABLE SEM_MP_INFO_H_TEMP CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_MP_INFO_D_TEMP
DROP TABLE SEM_MP_INFO_D_TEMP CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_SRA_H_TEMP
DROP TABLE SEM_SRA_H_TEMP CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_SRA_D_TEMP
DROP TABLE SEM_SRA_D_TEMP CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_DETAIL_CHARGE
DROP TABLE SEM_DETAIL_CHARGE CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_MP_STATEMENT
DROP TABLE SEM_MP_STATEMENT CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_MP_INFO
DROP TABLE SEM_MP_INFO CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_SRA
DROP TABLE SEM_SRA CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_INVOICE
DROP TABLE SEM_INVOICE CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_INVOICE_JOB
DROP TABLE SEM_INVOICE_JOB CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_LOAD
DROP TABLE SEM_LOAD CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_DISPATCH_INSTR
DROP TABLE SEM_DISPATCH_INSTR CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_LOSS_FACTOR
DROP TABLE SEM_LOSS_FACTOR CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_GEN_FORECAST
DROP TABLE SEM_GEN_FORECAST CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_LOSS_LOAD_PROB_FORECAST
DROP TABLE SEM_LOSS_LOAD_PROB_FORECAST CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_IC_DATA
DROP TABLE SEM_IC_DATA CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_IC_ERR_UNIT_BALANCE
DROP TABLE SEM_IC_ERR_UNIT_BALANCE CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_IC_NET_ACTUAL
DROP TABLE SEM_IC_NET_ACTUAL CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_IC_CAP_HOLDINGS
DROP TABLE SEM_IC_CAP_HOLDINGS CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_METER_SUMMARY
DROP TABLE SEM_METER_SUMMARY CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_METER_DETAIL
DROP TABLE SEM_METER_DETAIL CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_OUTAGE_SCHEDULE
DROP TABLE SEM_OUTAGE_SCHEDULE CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_INACTIVE_PART
DROP TABLE SEM_INACTIVE_PART CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_SYSTEM_FREQUENCY
DROP TABLE SEM_SYSTEM_FREQUENCY CASCADE CONSTRAINTS;

PROMPT Drop Table SEM_SERVICE_POINT_PSE
DROP TABLE SEM_SERVICE_POINT_PSE CASCADE CONSTRAINTS;




