CREATE OR REPLACE PACKAGE MM_SEM_SETTLEMENT_PARSE IS

  -- Author  : JHUMPHRIES
  -- Created : 3/27/2007 5:14:09 PM
  -- Purpose : Parse settlement CSV files into temp tables

FUNCTION WHAT_VERSION RETURN VARCHAR;

FUNCTION PARSE_STATEMENT_REPORT
	(
	p_REPORT IN CLOB,
	p_LOGGER IN OUT NOCOPY MM_LOGGER_ADAPTER
	) RETURN NUMBER;

FUNCTION PARSE_PARTICIPANT_INFO_REPORT
	(
	p_REPORT IN CLOB,
	p_LOGGER IN OUT NOCOPY MM_LOGGER_ADAPTER
	) RETURN NUMBER;

FUNCTION PARSE_REALLOCATION_REPORT
	(
	p_REPORT IN CLOB,
	p_LOGGER IN OUT NOCOPY MM_LOGGER_ADAPTER
	) RETURN NUMBER;

FUNCTION PARSE_GENERAL_PUBLIC_REPORT
	(
	p_REPORT IN CLOB,
	p_LOGGER IN OUT NOCOPY MM_LOGGER_ADAPTER
	) RETURN NUMBER;

-- Procedure used to store a PIR Import file record into the table
-- SEM_MP_INFO_FILES for later processing.
PROCEDURE INS_SEM_MP_INFO_FILES(p_REC IN OUT SEM_MP_INFO_FILES%ROWTYPE);

-- Procedure used to delete a PIR Import file record from the table
-- SEM_MP_INFO_FILES.
PROCEDURE DEL_SEM_MP_INFO_FILES(p_IMPORT_FILE_ID IN SEM_MP_INFO_FILES.IMPORT_FILE_ID%TYPE);


END MM_SEM_SETTLEMENT_PARSE;
/