CREATE OR REPLACE PACKAGE MM_SEM_PIR_IMPORT IS
-- AUTHOR  : LDUMITRIU
-- CREATED : 01/18/2008 12:50:05
-- PURPOSE : Viridian wants to run the settlement calculations with the SMO's published numbers.
--           This can be accomplished by saving PIR data into transactions.

PROCEDURE IMPORT_PIR (
    p_BEGIN_DATE IN DATE,
    p_END_DATE   IN DATE,
    p_LOG_TYPE   IN NUMBER,
    p_TRACE_ON   IN NUMBER,
    p_STATUS     OUT NUMBER,
    p_MESSAGE    OUT VARCHAR2);

$IF $$UNIT_TEST_MODE = 1 $THEN
PROCEDURE PUT_DETAIL_PIR(
   p_STATEMENT_ID   IN SEM_MP_STATEMENT.STATEMENT_ID%TYPE,
   p_STATEMENT_TYPE IN SEM_MP_STATEMENT.STATEMENT_TYPE%TYPE,
   p_ENTITY_ID      IN SEM_MP_STATEMENT.ENTITY_ID%TYPE,
   p_LOGGER         IN OUT NOCOPY MM_LOGGER_ADAPTER);
$END

FUNCTION WHAT_VERSION RETURN VARCHAR;

END MM_SEM_PIR_IMPORT;
/