CREATE OR REPLACE PACKAGE MM_SEM_CFD_CALC IS

-- Purpose: Handle Calculations needed by CFD Components
-- $Revision: 1.4 $
FUNCTION WHAT_VERSION RETURN VARCHAR;

FUNCTION GET_CURRENCY
	(
	p_CONTRACT_ID IN INTERCHANGE_CONTRACT.CONTRACT_ID%TYPE
	) RETURN NUMBER;

FUNCTION GET_STRIKE_PRICE
	(
	p_TXN_NAME IN INTERCHANGE_TRANSACTION.TRANSACTION_NAME%TYPE,
	p_STATEMENT_TYPE IN STATEMENT_TYPE.STATEMENT_TYPE_ID%TYPE,
	p_SCHEDULE_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_STRIKE_PRICE_WITH_ID
	(
	p_TXN_ID IN INTERCHANGE_TRANSACTION.TRANSACTION_ID%TYPE,
	p_STATEMENT_TYPE IN STATEMENT_TYPE.STATEMENT_TYPE_ID%TYPE,
	p_SCHEDULE_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_CONTRACT_LEVEL
	(p_TXN_NAME IN INTERCHANGE_TRANSACTION.TRANSACTION_NAME%TYPE,
	p_STATEMENT_TYPE IN STATEMENT_TYPE.STATEMENT_TYPE_ID%TYPE,
	p_SCHEDULE_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_CONTRACT_LEVEL_WITH_ID
	(p_TXN_ID IN INTERCHANGE_TRANSACTION.TRANSACTION_ID%TYPE,
	p_STATEMENT_TYPE IN STATEMENT_TYPE.STATEMENT_TYPE_ID%TYPE,
	p_SCHEDULE_DATE IN DATE
	) RETURN NUMBER;

-- FAST GET ASSUMES THAT THE PRICE INTERVAL MATCHES THE REQUEST
FUNCTION FAST_GET_MARKET_PRICE
	(
	p_MARKET_PRICE_ID IN MARKET_PRICE_VALUE.MARKET_PRICE_ID%TYPE,
	p_CUT_DATE IN DATE,
    p_ERROR_ON_MISSING IN CHAR DEFAULT 'Y'
	) RETURN NUMBER;
END MM_SEM_CFD_CALC;
/