CREATE OR REPLACE PACKAGE SEM_CREDIT_REPORTS IS
--Revision: $Revision: 1.8 $

  -- Author  : MWEATHERS
  -- Created : 8/20/2007
  -- Purpose : Report procedures for SEM Credit Cover Reports
TYPE REF_CURSOR IS REF CURSOR;
FUNCTION WHAT_VERSION RETURN VARCHAR;

PROCEDURE GET_CREDIT_SUMMARY_PARTY_RPT
	(
	p_ENTITY_GROUP_ID IN NUMBER,
	p_STATEMENT_STATE IN NUMBER,
	p_STATEMENT_TYPE IN NUMBER,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_CREDIT_SUMMARY_PSE_RPT
	(
	p_ENTITY_GROUP_ID IN NUMBER,
	p_STATEMENT_STATE IN NUMBER,
	p_STATEMENT_TYPE IN NUMBER,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_CREDIT_SUMMARY_ALL_RPT
	(
	p_ENTITY_GROUP_ID IN NUMBER,
	p_STATEMENT_STATE IN NUMBER,
	p_STATEMENT_TYPE IN NUMBER,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_CREDIT_CALC_EXTERNAL_RPT
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_YEARLY_INPUTS_RPT
	(
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE PUT_YEARLY_INPUTS_RPT
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_ANALYSIS_PERCENTILE_PARAM IN NUMBER,
	p_FIXED_CREDIT_REQT_SUP IN NUMBER,
	p_FIXED_CREDIT_REQT_GEN IN NUMBER,
	p_VAR_MO_PRICE IN NUMBER,
	p_IMPERFECTIONS_PRICE IN NUMBER,
	p_HIST_ASSESSMENT_PERIOD_EN IN NUMBER,
	p_HIST_ASSESSMENT_PERIOD_CA IN NUMBER,
	p_OLD_BEGIN_DATE IN DATE
	);

PROCEDURE CREATE_CREDIT_ATTRIBUTES;

PROCEDURE GET_ATTRIBUTE_INPUTS_RPT
	(
	p_ENTITY_TYPE IN VARCHAR2,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE PUT_ATTRIBUTE_INPUTS_RPT
	(
	p_ATTRIBUTE_ID IN NUMBER,
	p_OWNER_ENTITY_ID IN NUMBER,
	p_ATTRIBUTE_VAL IN VARCHAR2,
	p_ATTRIBUTE_BEGIN_DATE IN DATE,
	p_ATTRIBUTE_END_DATE IN DATE,
	p_OLD_ATTRIBUTE_ID IN NUMBER,
	p_OLD_OWNER_ENTITY_ID IN NUMBER,
	p_OLD_ATTRIBUTE_BEGIN_DATE IN DATE
	);

PROCEDURE DEL_ATTRIBUTE_INPUTS_RPT
	(
	p_ATTRIBUTE_ID IN NUMBER,
	p_OWNER_ENTITY_ID IN NUMBER,
	p_ATTRIBUTE_BEGIN_DATE IN DATE
	);

PROCEDURE GET_ATTRIBUTE_LIST
	(
	p_ENTITY_TYPE IN VARCHAR2,
	p_STATUS OUT NUMBER,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_PARTY_LIST
	(
	p_INCLUDE_ALL IN NUMBER,
	p_STATUS OUT NUMBER,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_PARTICIPANT_PSE_LIST
	(
	p_INCLUDE_ALL IN NUMBER,
	p_STATUS OUT NUMBER,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_CALC_CURRENCY_RPT
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_CALC_PSE_RPT
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE CREATE_UNIT_FCAST_TXNS
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE
	);

PROCEDURE GET_UNIT_FORECAST_RPT
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_TIME_ZONE IN VARCHAR2,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE PUT_UNIT_FORECAST_RPT
	(
	p_TRANSACTION_ID IN NUMBER,
	p_STATEMENT_TYPE IN NUMBER,
	p_CUT_DATE_SCHEDULING IN DATE,
	p_AMOUNT IN NUMBER,
	p_STATUS OUT NUMBER
	);

PROCEDURE GET_POSTED_CREDIT_COVER_RPT
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_TIME_ZONE IN VARCHAR2,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE PUT_POSTED_CREDIT_COVER_RPT
	(
	p_ENTITY_GROUP_ID IN NUMBER,
	p_ASSESSMENT_DAY IN DATE,
	p_POSTED_CREDIT_COVER IN NUMBER
	);

PROCEDURE GET_TEST_ONLY_BILL_DATA_RPT
	(
	p_ENTITY_ID IN NUMBER,
	p_PRODUCT_ID IN NUMBER,
	p_COMPONENT_ID IN NUMBER,
	p_STATEMENT_TYPE IN NUMBER,
	p_STATEMENT_STATE IN NUMBER,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_TIME_ZONE IN VARCHAR2,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE PUT_TEST_ONLY_BILL_DATA_RPT
	(
	p_ENTITY_ID IN NUMBER,
	p_PRODUCT_ID IN NUMBER,
	p_COMPONENT_ID IN NUMBER,
	p_STATEMENT_TYPE IN NUMBER,
	p_STATEMENT_STATE IN NUMBER,
	p_CUT_DATE IN DATE,
	p_BILL_AMOUNT IN NUMBER
	);

PROCEDURE GET_SEM_EXPOSURE_PERIOD_RPT
	(
	p_STATEMENT_TYPE IN NUMBER,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_DAILY_BILLING_DATA_RPT
	(
	p_ASSESSMENT_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_PSE_ID IN NUMBER,
	p_CREDIT_MARKET IN VARCHAR2,
	p_CREDIT_CATEGORY IN VARCHAR2,
	p_RANGE_BEGIN_DATE OUT VARCHAR2,
	p_RANGE_END_DATE OUT VARCHAR2,
	p_ASSESSMENT_DATE_LBL OUT VARCHAR2,
	p_CURSOR OUT SYS_REFCURSOR
	);

PROCEDURE GET_DAILY_SRA_DATA_RPT
	(
	p_ASSESSMENT_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_PSE_ID IN NUMBER,
	p_CREDIT_MARKET IN VARCHAR2,
	p_CREDIT_CATEGORY IN VARCHAR2,
	p_RANGE_BEGIN_DATE OUT VARCHAR2,
	p_RANGE_END_DATE OUT VARCHAR2,
	p_ASSESSMENT_DATE_LBL OUT VARCHAR2,
	p_CURSOR OUT SYS_REFCURSOR
	);

PROCEDURE GET_DAILY_UNDEF_ADJ_RPT
	(
	p_ASSESSMENT_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_PSE_ID IN NUMBER,
	p_CREDIT_MARKET IN VARCHAR2,
	p_RANGE_BEGIN_DATE OUT VARCHAR2,
	p_RANGE_END_DATE OUT VARCHAR2,
	p_ASSESSMENT_DATE_LBL OUT VARCHAR2,
	p_EXPOSURE_PERIOD OUT NUMBER,
	p_CURSOR OUT SYS_REFCURSOR
	);

PROCEDURE GET_DAILY_UNDEF_STD_RPT
	(
	p_ASSESSMENT_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_PSE_ID IN NUMBER,
	p_CREDIT_MARKET IN VARCHAR2,
	p_AVG_SAMPLE OUT NUMBER,
	p_STDDEV_SAMPLE OUT NUMBER,
	p_ANPP OUT NUMBER,
	p_TOTAL_UNDEFINED OUT NUMBER,
	p_EXPOSURE_PERIOD OUT NUMBER,
	p_CURSOR OUT SYS_REFCURSOR
	);

FUNCTION GET_EXCHANGE_MARKET_PRICE_ID
	(
	p_FROM_CURRENCY IN VARCHAR2,
	p_TO_CURRENCY IN VARCHAR2
	) RETURN NUMBER;

PROCEDURE GET_SRA_FORECAST_RPT
	(
	p_PSE_ID IN NUMBER,
	p_CREDIT_MARKET IN VARCHAR2,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_STATEMENT_TYPE IN NUMBER,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_SRA_FORECAST_CONFIG_RPT
	(
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE PUT_SRA_FORECAST_CONFIG_RPT
	(
	p_PERIOD_NAME IN VARCHAR2,
	p_CREDIT_MARKET IN VARCHAR2,
	p_SORT_ORDER IN NUMBER,
	p_MULTIPLIER IN NUMBER,
	p_DAYS_UNTIL_POSTED IN NUMBER,
	p_DAY_TYPE IN VARCHAR2,
	p_IS_RELATIVE_TO_PERIOD_BEGIN IN NUMBER,
	p_OLD_PERIOD_NAME IN VARCHAR2,
	p_OLD_CREDIT_MARKET IN VARCHAR2
	);

PROCEDURE DEL_SRA_FORECAST_CONFIG_RPT
	(
	p_PERIOD_NAME IN VARCHAR2,
	p_CREDIT_MARKET IN VARCHAR2
	);

PROCEDURE GET_TYPE3_CREDIT_SUM_PARTY_RPT
	(
	p_STATEMENT_STATE IN NUMBER,
    p_ENTITY_GROUP_ID IN NUMBER,
	p_VERSION_ID IN NUMBER,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_TYPE3_CREDIT_PSE_RPT
	(
	p_VERSION IN VARCHAR2,
	p_TIME_STAMP IN DATE,
	p_ASSESMENT_DATE IN DATE,
	p_ENTITY_GROUP_NAME IN VARCHAR2,
    p_STATEMENT_STATE IN NUMBER,
	p_ENTITY_GROUP_ID IN NUMBER,
	p_DETAIL_TYPE IN VARCHAR2,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_TYPE3_CREDIT_VERSION
	(
	p_STATUS OUT NUMBER,
	p_CURSOR IN OUT REF_CURSOR
	);

PROCEDURE GET_SEM_ACC_SUMMARY_PARTY_RPT
    (
    p_ENTITY_GROUP_ID   IN NUMBER,
    p_SELECTED_RUN_TYPE IN VARCHAR2,
    p_BEGIN_DATE        IN DATE,
    p_END_DATE          IN DATE,
    p_TIME_ZONE         IN VARCHAR2,
    p_CURSOR            IN OUT GA.REFCURSOR
    );

PROCEDURE GET_SEM_ACC_REPORT_DETAIL
    (
    p_CODE_PARTICIPANT_NAME IN VARCHAR2,
    p_SELECTED_RUN_TYPE     IN VARCHAR2,
    p_TRADE_DATE            IN DATE,
    p_TIME_ZONE             IN VARCHAR2,
    p_DETAIL_TYPE           IN VARCHAR2,
    p_CURSOR                IN OUT GA.REFCURSOR
    );

c_LOW_DATE CONSTANT DATE := LOW_DATE;
c_LABEL_DATE_FORMAT CONSTANT VARCHAR2(16) := 'DD-MON-YYYY';

END SEM_CREDIT_REPORTS;
/