prompt Inserting SEM Report Attributes
prompt @SEM_REPORT_ATTRIBUTES_before_MPUD5.sql
@@SEM_REPORT_ATTRIBUTES_before_MPUD5.sql
prompt @SEM_REPORT_ATTRIBUTES_after_MPUD5.sql
@@SEM_REPORT_ATTRIBUTES_after_MPUD5.sql
prompt SEM_REPORT_ATTRIBUTES_MPUD6.sql
@@SEM_REPORT_ATTRIBUTES_MPUD6.sql
prompt SEM_REPORT_ATTRIBUTES_R2_0_0.sql
@@SEM_REPORT_ATTRIBUTES_R2_0_0.sql
commit;
/
