PROMPT Alter Table Ancillary_Service_Allocation
CREATE TABLE X_ANCILLARY_SERVICE_ALLOCATION AS SELECT * FROM ANCILLARY_SERVICE_ALLOCATION;
UPDATE ANCILLARY_SERVICE_ALLOCATION SET ALLOCATION_VAL = NULL, DEFAULT_VAL = NULL;
ALTER TABLE ANCILLARY_SERVICE_ALLOCATION MODIFY(ALLOCATION_VAL NUMBER(16,6), DEFAULT_VAL NUMBER(16,6));
UPDATE ANCILLARY_SERVICE_ALLOCATION X SET (ALLOCATION_VAL, DEFAULT_VAL) = (SELECT ALLOCATION_VAL, DEFAULT_VAL FROM X_ANCILLARY_SERVICE_ALLOCATION WHERE ANCILLARY_SERVICE_ID = X.ANCILLARY_SERVICE_ID AND ALLOCATION_NAME = X.ALLOCATION_NAME AND BEGIN_DATE = X.BEGIN_DATE);
DROP TABLE X_ANCILLARY_SERVICE_ALLOCATION;
