DECLARE
v_COUNT PLS_INTEGER;
BEGIN
   SELECT COUNT(*) INTO v_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CDI_MV90_ARCHIVE' AND COLUMN_NAME = 'PROCESS_ID' AND DATA_PRECISION IS NULL;
   IF v_COUNT = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE CDI_MV90_ARCHIVE MODIFY(PROCESS_ID NUMBER)';
      DBMS_OUTPUT.PUT_LINE('CDI_MV90_ARCHIVE table altered');
   END IF;
   SELECT COUNT(*) INTO v_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PROCESS_LOG_EVENT' AND COLUMN_NAME = 'PROCEDURE_NAME' AND DATA_LENGTH = 128;
   IF v_COUNT = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_LOG_EVENT MODIFY(PROCEDURE_NAME VARCHAR2(128))';
      DBMS_OUTPUT.PUT_LINE('PROCESS_LOG_EVENT table altered');
   END IF;
   SELECT COUNT(*) INTO v_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PROCESS_LOG_TRACE' AND COLUMN_NAME = 'PROCEDURE_NAME' AND DATA_LENGTH = 128;
   IF v_COUNT = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_LOG_TRACE MODIFY(PROCEDURE_NAME VARCHAR2(128))';
      DBMS_OUTPUT.PUT_LINE('PROCESS_LOG_TRACE table altered');
   END IF;
   SELECT COUNT(*) INTO v_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PROCESS_LOG_TEMP_TRACE' AND COLUMN_NAME = 'PROCEDURE_NAME' AND DATA_LENGTH = 128;
   IF v_COUNT = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_LOG_TEMP_TRACE MODIFY(PROCEDURE_NAME VARCHAR2(128))';
      DBMS_OUTPUT.PUT_LINE('PROCESS_LOG_TEMP_TRACE table altered');
   END IF;
   SELECT COUNT(*) INTO v_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ANCILLARY_SERVICE_ALLOCATION' AND COLUMN_NAME = 'DEFAULT_VAL' AND DATA_LENGTH = 128 AND DATA_SCALE = 6;
   IF v_COUNT = 0 THEN
      UPDATE ANCILLARY_SERVICE_ALLOCATION SET DEFAULT_VAL = NULL;
      EXECUTE IMMEDIATE 'ALTER TABLE ANCILLARY_SERVICE_ALLOCATION MODIFY(DEFAULT_VAL NUMBER(16,6))';
      DBMS_OUTPUT.PUT_LINE('ANCILLARY_SERVICE_ALLOCATION table altered');
      COMMIT;
   END IF;
   SELECT COUNT(*) INTO v_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'IT_SCHEDULE' AND COLUMN_NAME = 'AMOUNT' AND DATA_PRECISION = 15 AND DATA_SCALE = 7;
   IF v_COUNT = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE IT_SCHEDULE MODIFY AMOUNT NUMBER(15,7)';
      DBMS_OUTPUT.PUT_LINE('IT_SCHEDULE table altered');
   END IF;
END;
/

