BEGIN CDI_DROP_OBJECT('CDI_MISSING_PLC_NSPL_TAG_CACHE','TABLE'); END;
/

CREATE TABLE CDI_MISSING_PLC_NSPL_TAG_CACHE
(
  TAG_TYPE             CHAR(1),
  BILL_ACCOUNT         NUMBER,
  SERVICE_POINT        NUMBER,
  PREMISE_NUMBER       NUMBER,
  EFFECTIVE_DATE       DATE,
  TERMINATION_DATE     DATE,
  RATE_CLASS           VARCHAR2(32),
  VOLTAGE_LEVEL        VARCHAR2(32),
  SOURCE_BILL_ACCOUNT  NUMBER,
  SOURCE_SERVICE_POINT NUMBER
);
