BEGIN CDI_DROP_OBJECT('CDI_MV90_ARCHIVE_CACHE','TABLE'); END;
/

CREATE TABLE CDI_MV90_ARCHIVE_CACHE
(
  CHANNEL                     VARCHAR2(8) NOT NULL,
  CUT_INTERVAL                DATE NOT NULL,
  IS_ALTERNATE_FORMAT         CHAR(1),
  PULSE_MULTIPLIER            NUMBER,
  PULSE_OFFSET                NUMBER,
  ALTERNATE_PULSE_MULTIPLIER  NUMBER,
  PREMISE_NUMBER              NUMBER,
  KW                          NUMBER,
  STATUS_CODE                 CHAR(1),
  PROCESS_ID                  NUMBER,
  CREATE_DATE_TIME            DATE,
  LAST_UPDATE_DATE_TIME       DATE,
  CONSTRAINT PK_CDI_MV90_ARCHIVE_CACHE PRIMARY KEY(CUT_INTERVAL, CHANNEL)
) TABLESPACE &&NERO_DATA_TABLESPACE;

CREATE INDEX CDI_MV90_ARCHIVE_CACHE_IX01 ON CDI_MV90_ARCHIVE_CACHE(PROCESS_ID) TABLESPACE &&NERO_INDEX_TABLESPACE;
