BEGIN CDI_DROP_OBJECT('CDI_PJM_ECAPACITY_ADJ','TABLE'); END;
/

CREATE TABLE CDI_PJM_ECAPACITY_ADJ
(
  PLC_DATE        DATE,
  PJM_SHORT_NAME  VARCHAR2(64),
  ICAP_VAL        NUMBER,
  NSPL_VAL        NUMBER,
  CONSTRAINT PK_CDI_PJM_ECAPACITY_ADJ PRIMARY KEY (PLC_DATE, PJM_SHORT_NAME)
) ORGANIZATION INDEX TABLESPACE &&NERO_INDEX_TABLESPACE INCLUDING ICAP_VAL OVERFLOW TABLESPACE &&NERO_DATA_TABLESPACE;
