BEGIN CDI_DROP_OBJECT('CDI_ANCILLARY_SERVICE_EXTERNAL','TABLE'); END;
/

CREATE TABLE CDI_ANCILLARY_SERVICE_EXTERNAL
(
  BILL_ACCOUNT   NUMBER,
  SERVICE_POINT  NUMBER,
  PREMISE_NUMBER NUMBER,
  PEAK_DATE      DATE,
  POINT_VAL      NUMBER
)
ORGANIZATION EXTERNAL(
   TYPE ORACLE_LOADER
   DEFAULT DIRECTORY ABB_IMPORT_DIRECTORY
   ACCESS PARAMETERS( 
      RECORDS DELIMITED BY NEWLINE 
      BADFILE 'ancillary_service_import.bad' 
      LOGFILE 'ancillary_service_import.log' 
      NODISCARDFILE 
      FIELDS TERMINATED BY ',' LRTRIM
      MISSING FIELD VALUES ARE NULL
      REJECT ROWS WITH ALL NULL FIELDS
      (BILL_ACCOUNT, SERVICE_POINT, PREMISE_NUMBER, PEAK_DATE DATE 'MM/DD/YYYY HH24:MI:SS', POINT_VAL)) 
   LOCATION (ABB_IMPORT_DIRECTORY:'ancillary_service_import.dat')
   )
REJECT LIMIT UNLIMITED;
