BEGIN CDI_DROP_OBJECT('CDI_MV90_IMPORT_ACCOUNT','TABLE'); END;
/

CREATE GLOBAL TEMPORARY TABLE CDI_MV90_IMPORT_ACCOUNT
(
  ACCOUNT_ID                  NUMBER(9),
  ACCOUNT_NAME                VARCHAR2(128),
  ACCOUNT_EXTERNAL_IDENTIFIER VARCHAR2(128),
  CONSTRAINT PK_CDI_SERVICE_DATE_MAP PRIMARY KEY (ACCOUNT_ID)
) ON COMMIT PRESERVE ROWS;
