BEGIN CDI_DROP_OBJECT('CDI_NETWORK_RECON_FACTOR','TABLE'); END;
/

CREATE TABLE CDI_NETWORK_RECON_FACTOR
(
  PLC_DATE     DATE,
  FACTOR       NUMBER(9,7),
  ICAP_FACTOR  NUMBER(9,7)
) TABLESPACE &&NERO_DATA_TABLESPACE;
