CREATE OR REPLACE VIEW ACCOUNT_SL_EDC_ESP( ACCOUNT_NAME, 
ACCOUNT_ID, ACCOUNT_MODEL_OPTION, BEGIN_DATE, END_DATE, 
SERVICE_LOCATION_NAME, ESP_BEGIN_DATE, ESP_END_DATE, ESP_NAME, 
ESP_ID, EDC_BEGIN_DATE, EDC_END_DATE, EDC_NAME, 
EDC_ID ) AS SELECT A.ACCOUNT_NAME,
	A.ACCOUNT_ID,
	A.ACCOUNT_MODEL_OPTION,
	C.BEGIN_DATE,
	C.END_DATE,
	D.SERVICE_LOCATION_NAME,
	E.BEGIN_DATE "ESP_BEGIN_DATE",
	E.END_DATE "ESP_END_DATE",
	F.ESP_NAME,
	F.ESP_ID,
	G.BEGIN_DATE "EDC_BEGIN_DATE",
	G.END_DATE "EDC_END_DATE",
	H.EDC_NAME,
	H.EDC_ID 
FROM ACCOUNT A,
	ACCOUNT_STATUS B,	
	ACCOUNT_STATUS_NAME STATUS_NAME,
	ACCOUNT_SERVICE_LOCATION C,
	SERVICE_LOCATION D,
	ACCOUNT_ESP E,
	ENERGY_SERVICE_PROVIDER F,
	ACCOUNT_EDC G,
	ENERGY_DISTRIBUTION_COMPANY H
WHERE B.ACCOUNT_ID = A.ACCOUNT_ID
	AND TRUNC(SYSDATE) BETWEEN B.BEGIN_DATE AND NVL(B.END_DATE, HIGH_DATE)
	AND B.STATUS_NAME = STATUS_NAME.STATUS_NAME
	AND STATUS_NAME.IS_ACTIVE = 1   
	AND C.ACCOUNT_ID = B.ACCOUNT_ID
	AND D.SERVICE_LOCATION_ID = C.SERVICE_LOCATION_ID
	AND E.ACCOUNT_ID = C.ACCOUNT_ID
	AND F.ESP_ID = E.ESP_ID
	AND G.ACCOUNT_ID = E.ACCOUNT_ID
	AND H.EDC_ID = G.EDC_ID
UNION
SELECT A.ACCOUNT_NAME,
	A.ACCOUNT_ID,
	A.ACCOUNT_MODEL_OPTION,
	C.BEGIN_DATE,
	C.END_DATE,
	'Aggregate Account',
	D.BEGIN_DATE "ESP_BEGIN_DATE",
	D.END_DATE "ESP_END_DATE",
	E.ESP_NAME,
	E.ESP_ID,
	F.BEGIN_DATE "EDC_BEGIN_DATE",
	F.END_DATE "EDC_END_DATE",
	G.EDC_NAME,
	G.EDC_ID 
FROM ACCOUNT A,
	ACCOUNT_STATUS B,
	ACCOUNT_STATUS_NAME STATUS_NAME,
	ACCOUNT_SERVICE_LOCATION C,
	AGGREGATE_ACCOUNT_ESP D,
	ENERGY_SERVICE_PROVIDER E,
	ACCOUNT_EDC F,
	ENERGY_DISTRIBUTION_COMPANY G
WHERE B.ACCOUNT_ID = A.ACCOUNT_ID
	AND TRUNC(SYSDATE) BETWEEN B.BEGIN_DATE AND NVL(B.END_DATE, HIGH_DATE)
	AND B.STATUS_NAME = STATUS_NAME.STATUS_NAME
	AND STATUS_NAME.IS_ACTIVE = 1    
	AND C.ACCOUNT_ID = B.ACCOUNT_ID
	AND D.ACCOUNT_ID = C.ACCOUNT_ID
	AND E.ESP_ID = D.ESP_ID
	AND F.ACCOUNT_ID = D.ACCOUNT_ID
	AND G.EDC_ID = F.EDC_ID;
