CREATE OR REPLACE VIEW ACCOUNT_ESP_CSB AS
(SELECT A.ACCOUNT_ID, A.ESP_ID, A.POOL_ID,		 
		A.BEGIN_DATE, 		 
		A.END_DATE,  			 
		A.ESP_ACCOUNT_NUMBER
FROM (		
		(WITH AST1 AS
		 (SELECT ACCOUNT_ID,
		 		 ESP_ID,
				 POOL_ID,
				 BEGIN_DATE,
				 NVL(END_DATE,  DATE '9999-12-31') END_DATE,
				 ESP_ACCOUNT_NUMBER,
				 CASE LAG(END_DATE) OVER(PARTITION BY ACCOUNT_ID, ESP_ID, POOL_ID ORDER BY BEGIN_DATE, END_DATE) + 1
					 WHEN BEGIN_DATE THEN
					  0
					 ELSE
					  1
				 END WINDOW_RANK
		  FROM ACCOUNT_ESP),
		AST2 AS
		 (SELECT ACCOUNT_ID,
		 		 ESP_ID,
				 POOL_ID,
				 BEGIN_DATE,
				 END_DATE,
				 ESP_ACCOUNT_NUMBER,
				 SUM(WINDOW_RANK) OVER(PARTITION BY ACCOUNT_ID,  ESP_ID, POOL_ID ORDER BY BEGIN_DATE, END_DATE) PARTITIONED_GROUP
		  FROM AST1)
		SELECT ACCOUNT_ID, ESP_ID, POOL_ID, ESP_ACCOUNT_NUMBER, MIN(BEGIN_DATE) BEGIN_DATE, MAX(END_DATE) END_DATE
		FROM AST2
		GROUP BY ACCOUNT_ID, ESP_ID, POOL_ID, ESP_ACCOUNT_NUMBER, PARTITIONED_GROUP
		ORDER BY ACCOUNT_ID, ESP_ID, POOL_ID, BEGIN_DATE
		)
) A);  