CREATE OR REPLACE VIEW ACCOUNT_MODEL_METER_TREE ( ACCOUNT, 
			ACCOUNT_ID, SERVICE_LOCATION, SERVICE_LOCATION_ID, METER, 
			METER_ID, BEGIN_DATE, END_DATE, METER_STATUS, 
			METER_TYPE, METER_INTERVAL, METER_UNIT ) AS
SELECT A.ACCOUNT_NAME "ACCOUNT",    
	A.ACCOUNT_ID,    
	D.SERVICE_LOCATION_NAME "SERVICE_LOCATION",    
	D.SERVICE_LOCATION_ID,    
	'Meter' "METER",    
	0 "METER_ID",    
	C.BEGIN_DATE,    
	NVL(C.END_DATE,HIGH_DATE),    
	'Active' "METER_STATUS",    
	A.ACCOUNT_METER_TYPE "METER_TYPE",    
	DECODE(SUBSTR(A.ACCOUNT_METER_TYPE,1,1),'I','Hour','Month') "METER_INTERVAL",    
	'KWH' "METER_UNIT"    
FROM ACCOUNT A,
	ACCOUNT_STATUS B,
	ACCOUNT_SERVICE_LOCATION C,
	SERVICE_LOCATION D,
	ACCOUNT_STATUS_NAME E
WHERE UPPER(SUBSTR(A.ACCOUNT_MODEL_OPTION,1,1)) = 'A'
	AND B.ACCOUNT_ID = A.ACCOUNT_ID
	AND TRUNC(SYSDATE) BETWEEN B.BEGIN_DATE AND NVL(B.END_DATE, HIGH_DATE)
	AND E.STATUS_NAME = B.STATUS_NAME
	AND E.IS_ACTIVE = 1   
	AND C.ACCOUNT_ID = B.ACCOUNT_ID   
	AND D.SERVICE_LOCATION_ID = C.SERVICE_LOCATION_ID;
