CREATE OR REPLACE VIEW AGGREGATE_ACCOUNT_ESP_ALL ( ACCOUNT_ID, 
ESP_ID, POOL_ID, BEGIN_DATE, END_DATE, 
AGGREGATE_ID, ENTRY_DATE, ESP_NAME, POOL_NAME, 
ACCOUNT_NAME ) AS SELECT A.ACCOUNT_ID, A.ESP_ID, A.POOL_ID, A.BEGIN_DATE, A.END_DATE, 
	A.AGGREGATE_ID, A.ENTRY_DATE, E.ESP_NAME, P.POOL_NAME, z.account_name 
FROM AGGREGATE_ACCOUNT_ESP A, ENERGY_SERVICE_PROVIDER E, POOL P, account z 
WHERE A.ESP_ID = E.ESP_ID AND A.POOL_ID = P.POOL_ID and a.account_id = z.account_id;


