CREATE OR REPLACE VIEW AGGREGATE_ACCOUNT_GROUP_INFO ( ACCOUNT_ID, 
EDC_ID, ESP_ID, BEGIN_DATE, END_DATE, 
AGGREGATE_ID, ENTRY_DATE, EDC_NAME, ESP_NAME
 ) AS SELECT A.ACCOUNT_ID, A.EDC_ID, A.ESP_ID, A.BEGIN_DATE, A.END_DATE,
A.AGGREGATE_ID, A.ENTRY_DATE, D.EDC_NAME, S.ESP_NAME
FROM AGGREGATE_ACCOUNT_GROUP A, ENERGY_DISTRIBUTION_COMPANY D, ENERGY_SERVICE_PROVIDER S
WHERE A.EDC_ID = D.EDC_ID AND A.ESP_ID = S.ESP_ID;

