CREATE OR REPLACE VIEW EDC_ACCOUNT_FORECAST ( EDC_ID, 
SCENARIO_ID, FORECAST_DATE, FORECAST_ENERGY ) AS 
SELECT B.EDC_ID,
	A.SCENARIO_ID,
	A.FORECAST_DATE,
	SUM(A.FORECAST_VAL) "FORECAST_ENERGY"
FROM ACCOUNT_FORECAST A,
	ACCOUNT_EDC B
WHERE A.ACCOUNT_ID = B.ACCOUNT_ID
	AND A.FORECAST_DATE BETWEEN B.BEGIN_DATE AND NVL(B.END_DATE,A.FORECAST_DATE)
GROUP BY B.EDC_ID,
	A.SCENARIO_ID,
	A.FORECAST_DATE;
