CREATE OR REPLACE VIEW FORECAST_TREE ( ACCOUNT_NAME, 
ACCOUNT_ID, EDC_ID, PSE_ID, ESP_ID, 
SERVICE_LOCATION_NAME, SERVICE_LOCATION_ID, METER_NAME, METER_ID, 
BEGIN_DATE, END_DATE, ENTITY_ID, ENTITY_CODE
 ) AS SELECT A.ACCOUNT_NAME, 
	A.ACCOUNT_ID, 
	B.EDC_ID, 
	B.PSE_ID, 
	B.ESP_ID, 
	D.SERVICE_LOCATION_NAME, 
	D.SERVICE_LOCATION_ID, 
	'' "METER_NAME", 
	0 "METER_ID", 
	B.BEGIN_DATE, 
	B.END_DATE, 
	B.AGGREGATE_ID "ENTITY_ID", 
	1 "ENTITY_CODE" 
FROM RETAIL_ACCOUNT A, 
	AGGREGATE_ACCOUNT_GROUP B, 
	ACCOUNT_SERVICE_LOCATION C, 
	SERVICE_LOCATION D 
WHERE A.ACCOUNT_IS_ACTIVE = 1 
    AND A.IS_AGGREGATE_ACCOUNT = 1 
	AND UPPER(SUBSTR(A.ACCOUNT_MODEL_OPTION,1,1)) = 'A' 
	AND B.ACCOUNT_ID = A.ACCOUNT_ID 
	AND C.ACCOUNT_ID = A.ACCOUNT_ID 
	AND D.SERVICE_LOCATION_ID = C.SERVICE_LOCATION_ID 
UNION 
SELECT A.ACCOUNT_NAME, 
	A.ACCOUNT_ID, 
	B.EDC_ID, 
	F.PSE_ID, 
	C.ESP_ID, 
	E.SERVICE_LOCATION_NAME, 
	E.SERVICE_LOCATION_ID, 
	'' "METER_NAME", 
	0 "METER_ID", 
	C.BEGIN_DATE, 
	C.END_DATE, 
	A.ACCOUNT_ID "ENTITY_ID", 
	2 "ENTITY_CODE" 
FROM RETAIL_ACCOUNT A, 
	ACCOUNT_EDC B, 
	ACCOUNT_ESP C, 
	ACCOUNT_SERVICE_LOCATION D, 
	SERVICE_LOCATION E, 
	PSE_ESP F 
WHERE A.ACCOUNT_IS_ACTIVE = 1 
	AND UPPER(SUBSTR(A.ACCOUNT_MODEL_OPTION,1,1)) = 'A' 
	AND B.ACCOUNT_ID = A.ACCOUNT_ID 
	AND C.ACCOUNT_ID = A.ACCOUNT_ID 
	AND D.ACCOUNT_ID = A.ACCOUNT_ID 
	AND E.SERVICE_LOCATION_ID = D.SERVICE_LOCATION_ID 
	AND F.ESP_ID = C.ESP_ID 
	AND F.BEGIN_DATE <= NVL(C.END_DATE, F.BEGIN_DATE) 
	AND NVL(F.END_DATE, C.BEGIN_DATE) >= C.BEGIN_DATE 
UNION 
SELECT A.ACCOUNT_NAME, 
	A.ACCOUNT_ID, 
	B.EDC_ID, 
	H.PSE_ID, 
	C.ESP_ID, 
	E.SERVICE_LOCATION_NAME, 
	E.SERVICE_LOCATION_ID, 
	G.METER_NAME, 
	G.METER_ID, 
	C.BEGIN_DATE, 
	C.END_DATE, 
	G.METER_ID "ENTITY_ID", 
	3 "ENTITY_CODE" 
FROM RETAIL_ACCOUNT A, 
	ACCOUNT_EDC B, 
	ACCOUNT_ESP C, 
	ACCOUNT_SERVICE_LOCATION D, 
	SERVICE_LOCATION E, 
	SERVICE_LOCATION_METER F, 
	METER G, 
	PSE_ESP H 
WHERE A.ACCOUNT_IS_ACTIVE = 1 
	AND UPPER(SUBSTR(A.ACCOUNT_MODEL_OPTION,1,1)) = 'M' 
	AND B.ACCOUNT_ID = A.ACCOUNT_ID 
	AND C.ACCOUNT_ID = A.ACCOUNT_ID 
	AND D.ACCOUNT_ID = A.ACCOUNT_ID 
	AND E.SERVICE_LOCATION_ID = D.SERVICE_LOCATION_ID 
	AND F.SERVICE_LOCATION_ID = D.SERVICE_LOCATION_ID 
	AND G.METER_ID = F.METER_ID 
	AND G.METER_IS_ACTIVE = 1 
	AND H.ESP_ID = C.ESP_ID 
	AND H.BEGIN_DATE <= NVL(C.END_DATE, H.BEGIN_DATE) 
	AND NVL(H.END_DATE, C.BEGIN_DATE) >= C.BEGIN_DATE;
	
