CREATE OR REPLACE VIEW METER_MODEL_METER_TREE ( ACCOUNT, 
ACCOUNT_ID, SERVICE_LOCATION, SERVICE_LOCATION_ID, METER, 
METER_ID, BEGIN_DATE, END_DATE, METER_STATUS, 
METER_TYPE, METER_INTERVAL, METER_UNIT ) AS SELECT B.ACCOUNT_NAME "ACCOUNT", 
	B.ACCOUNT_ID, 
	C.SERVICE_LOCATION_NAME "SERVICE_LOCATION", 
	C.SERVICE_LOCATION_ID, 
	D.METER_NAME "METER", 
	D.METER_ID, 
	A.BEGIN_DATE, 
	A.END_DATE, 
	D.METER_STATUS, 
	D.METER_TYPE, 
	D.METER_INTERVAL, 
	D.METER_UNIT 
FROM ACCOUNT_SERVICE_LOCATION_METER A, 
	RETAIL_ACCOUNT B, 
	SERVICE_LOCATION C, 
	METER D 
WHERE B.ACCOUNT_ID = A.ACCOUNT_ID 
	AND B.ACCOUNT_IS_ACTIVE = 1 
	AND UPPER(SUBSTR(B.ACCOUNT_MODEL_OPTION,1,1)) = 'M' 
	AND C.SERVICE_LOCATION_ID = A.SERVICE_LOCATION_ID 
	AND D.METER_ID = A.METER_ID;

