CREATE OR REPLACE VIEW PHYSICAL_POSITION AS
SELECT A.TRANSACTION_ID,
		A.PURCHASER_ID,
		A.SELLER_ID,
		A.POR_ID,
		A.POD_ID,
		A.SERVICE_TYPE_ID,
		A.TRANSACTION_INTERVAL,
		B.COMMODITY_TYPE,
		C.TP_ID,
		C.EDC_ID,
		C.SERVICE_POINT_TYPE,
		D.SCHEDULE_TYPE,
		D.SCHEDULE_STATE,
		D.SCHEDULE_DATE,
		DECODE(UPPER(SUBSTR(A.TRANSACTION_TYPE,1,2)), 'LO', D.AMOUNT, 'RE', D.AMOUNT, NULL) "LOAD_STATISTIC",
		DECODE(UPPER(SUBSTR(A.TRANSACTION_TYPE,1,2)), 'LO', NVL(D.AMOUNT,0),'RE', NVL(D.AMOUNT,0), 0) "LOAD",
		DECODE(UPPER(SUBSTR(A.TRANSACTION_TYPE,1,2)), 'GE', NVL(D.AMOUNT,0),0) "GENERATION",
		DECODE(UPPER(SUBSTR(A.TRANSACTION_TYPE,1,2)), 'PU', NVL(D.AMOUNT,0),0) "PURCHASE_AMOUNT",
		DECODE(UPPER(SUBSTR(A.TRANSACTION_TYPE,1,2)), 'PU', NVL(D.PRICE,0),0) "PURCHASE_PRICE",
		DECODE(UPPER(SUBSTR(A.TRANSACTION_TYPE,1,2)), 'SA', NVL(D.AMOUNT,0),0) "SALE_AMOUNT",
		DECODE(UPPER(SUBSTR(A.TRANSACTION_TYPE,1,2)), 'SA', NVL(D.PRICE,0),0) "SALE_PRICE",
		DECODE(UPPER(SUBSTR(A.TRANSACTION_TYPE,1,2)), 'PA', NVL(D.AMOUNT,0),0) "PASS_THRU_AMOUNT",
		DECODE(UPPER(SUBSTR(A.TRANSACTION_TYPE,1,2)), 'PA', NVL(D.PRICE,0),0) "PASS_THRU_PRICE",
		E.ROLLUP_ID_1,
		E.ROLLUP_ID_2,
		E.ROLLUP_ID_3,
		E.ROLLUP_ID_4,
		D.AS_OF_DATE
	FROM INTERCHANGE_TRANSACTION A,
		IT_COMMODITY B,
		SERVICE_POINT C,
		IT_SCHEDULE D,
		RTO_ROLLUP_HIERARCHY E
	WHERE A.TRANSACTION_ID = D.TRANSACTION_ID
		AND A.POD_ID = C.SERVICE_POINT_ID
		AND C.ROLLUP_ID = E.ROLLUP_ID_1
		AND UPPER(SUBSTR(E.ROLLUP_CATEGORY,1,1))  = 'D'
		AND A.COMMODITY_ID = B.COMMODITY_ID;

