CREATE OR REPLACE VIEW PRODUCT_COMPONENT_INFO ( PRODUCT_ID, 
COMPONENT_ID, BEGIN_DATE, END_DATE, ENTRY_DATE, 
COMPONENT_NAME ) AS 
SELECT P.PRODUCT_ID, P.COMPONENT_ID, P.BEGIN_DATE, P.END_DATE, P.ENTRY_DATE,
	C.COMPONENT_NAME 
FROM PRODUCT_COMPONENT P, COMPONENT C
WHERE P.COMPONENT_ID = C.COMPONENT_ID;

