CREATE OR REPLACE VIEW SERVICE_LOCATION_METER_INFO ( SERVICE_LOCATION_ID, 
METER_ID, BEGIN_DATE, END_DATE, IS_ESTIMATED_END_DATE, 
EDC_IDENTIFIER, ESP_IDENTIFIER, NEXT_ACTION_DATE, EDC_RATE_CLASS, 
ENTRY_DATE, METER_NAME ) AS SELECT S.SERVICE_LOCATION_ID, S.METER_ID, S.BEGIN_DATE, S.END_DATE, S.IS_ESTIMATED_END_DATE, 
S.EDC_IDENTIFIER, S.ESP_IDENTIFIER, S.NEXT_ACTION_DATE, S.EDC_RATE_CLASS, 
S.ENTRY_DATE, M.METER_NAME 
FROM SERVICE_LOCATION_METER S, METER M 
WHERE S.METER_ID = M.METER_ID;

