CREATE OR REPLACE VIEW TP_CONTRACT_NUMBER_INFO
	(
	CONTRACT_ID, TP_ID, BEGIN_DATE, END_DATE,
	CONTRACT_NAME, CONTRACT_NUMBER, ENTRY_DATE, TP_NAME
	) AS
SELECT C.CONTRACT_ID, C.TP_ID, C.BEGIN_DATE, C.END_DATE,
	C.CONTRACT_NAME, C.CONTRACT_NUMBER,	C.ENTRY_DATE, T.TP_NAME
FROM TP_CONTRACT_NUMBER C, TRANSMISSION_PROVIDER T
WHERE C.TP_ID = T.TP_ID;

