CREATE OR REPLACE VIEW TX_TRANSACTION_ENTITY ( ENTITY_NAME, 
ENTITY_ALIAS, ENTITY_ID ) AS 
SELECT
        A.TRANSACTION_NAME "ENTITY_NAME",
        A.TRANSACTION_ALIAS "ENTITY_ALIAS",
        A.TRANSACTION_ID "ENTITY_ID"
FROM INTERCHANGE_TRANSACTION A,
     IT_COMMODITY B
WHERE A.TRANSACTION_ID > 0
      AND B.COMMODITY_ID = A.COMMODITY_ID
      AND UPPER(LTRIM(RTRIM(B.COMMODITY_TYPE))) = 'TRANSMISSION';
