CREATE OR REPLACE VIEW UNASSIGNED_SERVICE_LOC_INFO ( SERVICE_LOCATION_ID, 
SERVICE_LOCATION_NAME, METER_ID, METER_NAME, METER_EDC, 
METER_ESP ) AS SELECT SL.SERVICE_LOCATION_ID, SL.SERVICE_LOCATION_NAME, 
SLM.METER_ID, M.METER_NAME, SLM.EDC_IDENTIFIER, SLM.ESP_IDENTIFIER 
FROM SERVICE_LOCATION SL, SERVICE_LOCATION_METER SLM, METER M 
WHERE NUM_SERVICE_LOC_ASSIGNMENTS(SL.SERVICE_LOCATION_ID) = 0 AND 
SLM.SERVICE_LOCATION_ID(+) = SL.SERVICE_LOCATION_ID AND SLM.METER_ID = M.METER_ID(+);


