--Season Template Script for BGE.
DECLARE
	TYPE t_DAYS IS VARRAY(7) OF VARCHAR2(3);
	v_SEASON_ID NUMBER(9);
	
	FUNCTION GET_SEASON
		(
		p_SEASON_NAME IN VARCHAR2,
		p_BEGIN_DATE IN DATE,
		p_END_DATE IN DATE
		) RETURN NUMBER IS
		v_SEASON_ID NUMBER(9);
	BEGIN
		SELECT SEASON_ID INTO v_SEASON_ID FROM SEASON WHERE SEASON_NAME = p_SEASON_NAME;
		RETURN v_SEASON_ID;
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			IO.PUT_SEASON(v_SEASON_ID, p_SEASON_NAME, p_SEASON_NAME, NULL, 0, p_BEGIN_DATE, p_END_DATE);
			RETURN v_SEASON_ID; 
	END GET_SEASON;
	
	PROCEDURE CREATE_SEASON_TEMPLATE
		(
		p_SEASON_ID IN NUMBER,
		p_TEMPLATE_NAME IN VARCHAR2,
		p_DAYS IN t_DAYS
		) AS
		v_TEMPLATE_ID NUMBER(9);
		v_PERIOD_ID NUMBER(9) := 1;
	BEGIN
		BEGIN
			SELECT TEMPLATE_ID INTO v_TEMPLATE_ID FROM TEMPLATE WHERE TEMPLATE_NAME = p_TEMPLATE_NAME;
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				IO.PUT_TEMPLATE(v_TEMPLATE_ID, p_TEMPLATE_NAME, NULL, NULL, 0, 1);
		END;
		
		FOR i IN p_DAYS.FIRST .. p_DAYS.LAST LOOP
			SP.PUT_SEASON_TEMPLATE(v_TEMPLATE_ID, p_SEASON_ID, p_DAYS(i), 1, 24, v_PERIOD_ID);
		END LOOP;	
	END CREATE_SEASON_TEMPLATE;
BEGIN

	v_SEASON_ID := GET_SEASON('BGE Summer', '01-JUN-2000', '30-SEP-2000');
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE Summer Weekday', t_DAYS('Mon','Tue','Wed','Thu','Fri'));
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE Summer Saturday', t_DAYS('Sat'));
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE Summer Sunday', t_DAYS('Sun', 'Hol'));
	
	--Used by G asn GS profiles.  Tue_Thur is actually called Weekday in import.
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE Summer Monday', t_DAYS('Mon'));
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE Summer Tue_Thur', t_DAYS('Tue','Wed','Thu'));
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE Summer Friday', t_DAYS('Fri'));
	
	v_SEASON_ID := GET_SEASON('BGE NonSummer', '1-OCT-2000', '31-MAY-2001');
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE NonSummer Weekday', t_DAYS('Mon','Tue','Wed','Thu','Fri'));
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE NonSummer Saturday', t_DAYS('Sat'));
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE NonSummer Sunday', t_DAYS('Sun', 'Hol'));
	
	--Used by G asn GS profiles.  Tue_Thur is actually called Weekday in import.
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE NonSummer Monday', t_DAYS('Mon'));
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE NonSummer Tue_Thur', t_DAYS('Tue','Wed','Thu'));
	CREATE_SEASON_TEMPLATE(v_SEASON_ID, 'BGE NonSummer Friday', t_DAYS('Fri'));

	COMMIT;
END;
