SET DEFINE OFF	

BEGIN
    SECURITY_CONTROLS.SET_CURRENT_ROLES(ID_TABLE(ID_TYPE(SECURITY_CONTROLS.g_SUPER_USER_ROLE_ID)));    
END;
/

prompt OASIS_STATUS_NAMES
@@OASIS_STATUS_NAMES.SQL

prompt OASIS_TRAITS
@@OASIS_TRAITS.SQL

prompt OASIS_SYSTEM_DICTIONARY
@@OASIS_SYSTEM_DICTIONARY.SQL

prompt OASIS_ACTIONS
@@OASIS_ACTIONS.SQL

prompt Enabling OASIS external system...
BEGIN
UPDATE EXTERNAL_SYSTEM SET IS_ENABLED=1 WHERE EXTERNAL_SYSTEM_ID=EC.ES_OASIS;
END;
/

COMMIT;

SET DEFINE ON
