CREATE OR REPLACE PACKAGE CU AS
--Revision $Revision: 1.98 $

-- Product Component Utility Package --.
FUNCTION WHAT_VERSION RETURN VARCHAR;


FUNCTION NULL_CURSOR RETURN GA.REFCURSOR;

FUNCTION PRODUCT_HAS_SWING_COMPONENT
	(
	p_PRODUCT_ID IN NUMBER,
	p_SERVICE_DATE IN DATE
	) RETURN BOOLEAN;

FUNCTION COMPONENT_IS_SWING_COMPONENT
	(
	p_COMPONENT_ID IN NUMBER,
	p_SERVICE_DATE IN DATE
	) RETURN BOOLEAN;

FUNCTION GET_TAX_AREA_TAX_RATE
    (
	p_GEOGRAPHY_ID IN NUMBER,
	p_TAX IN OUT NOCOPY TAX_TABLE
	) RETURN NUMBER;

PROCEDURE GET_PRODUCT_TAX_COMPONENT
    (
	p_PRODUCT_ID IN NUMBER,
	p_SERVICE_DATE IN DATE,
	p_COMPONENT_ID IN OUT NUMBER,
	p_TAX IN OUT NOCOPY TAX_TABLE
	);

PROCEDURE GET_TOU_PERIODS
	(
	p_TEMPLATE_ID IN NUMBER,
	p_SERVICE_DATE IN DATE,
	p_TOU_PERIODS IN OUT NOCOPY TOU_TABLE
	);

PROCEDURE GET_SYSTEM_EVENTS
    (
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_EVENTS IN OUT NOCOPY EVENT_TABLE
	);

PROCEDURE GET_PRORATED_CONSUMPTION
    (
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_DETERMINANTS IN DETERMINANT_TABLE,
	p_CONSUMPTION IN CONSUMPTION_TABLE,
	p_TRACE_ON IN BOOLEAN,
	p_PRORATION IN OUT NOCOPY DETERMINANT_TABLE
	);

PROCEDURE GET_PRORATED_DETERMINANTS
    (
	p_CALENDAR_ID IN NUMBER,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_AS_OF_DATE IN DATE,
	p_CONSUMPTION IN CONSUMPTION_TABLE,
	p_TRACE_ON IN BOOLEAN,
	p_DETERMINANTS IN OUT NOCOPY DETERMINANT_TABLE
	);

PROCEDURE APPLY_PRODUCT_COMPONENT
	(
	p_PRODUCT_ID IN NUMBER,
	p_COMPONENT IN COMPONENT%ROWTYPE,
	p_DETERMINANTS IN DETERMINANT_TABLE,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_ENROLLMENT IN NUMBER,
	p_LOSS_FACTOR IN NUMBER,
	p_BILL_CYCLE_ID IN NUMBER,
	p_TRACE_ON IN BOOLEAN,
	p_CHARGE_COMPONENTS IN OUT NOCOPY CHARGE_COMPONENT_TABLE,
    p_NEED_PERIOD_IDs IN BOOLEAN := FALSE,
    p_INTERVAL_DETERMINANTS IN BOOLEAN := FALSE
	);

PROCEDURE APPLY_PRODUCT_COMPONENTS
	(
	p_PRODUCT_ID IN NUMBER,
	p_DETERMINANTS IN DETERMINANT_TABLE,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_ENROLLMENT IN NUMBER,
	p_LOSS_FACTOR IN NUMBER,
	p_BILL_CYCLE_ID IN NUMBER,
	p_TRACE_ON IN BOOLEAN,
	p_CHARGE_COMPONENTS IN OUT NOCOPY CHARGE_COMPONENT_TABLE
	);

PROCEDURE APPLY_PRODUCT_COMPONENTS
	(
	p_PRODUCT_ID IN NUMBER,
	p_DETERMINANTS IN DETERMINANT_TABLE,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_ENROLLMENT IN NUMBER,
	p_LOSS_FACTOR IN NUMBER,
	p_TRACE_ON IN BOOLEAN,
	p_CHARGE_COMPONENTS IN OUT NOCOPY CHARGE_COMPONENT_TABLE
	);

PROCEDURE APPLY_PRODUCT_COMPONENTS
	(
	p_PRODUCT_ID IN NUMBER,
	p_DETERMINANTS IN DETERMINANT_TABLE,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_TRACE_ON IN BOOLEAN,
	p_CHARGE_COMPONENTS IN OUT NOCOPY CHARGE_COMPONENT_TABLE
	);

PROCEDURE TRACE_DETERMINANTS
	(
	p_NAME IN VARCHAR,
	p_DETERMINANTS IN DETERMINANT_TABLE
	);

PROCEDURE TRACE_CHARGE_COMPONENTS
    (
	p_NAME IN VARCHAR,
	p_CHARGE_COMPONENTS IN CHARGE_COMPONENT_TABLE
	);

PROCEDURE COPY_DETERMINANTS
	(
	p_IN IN DETERMINANT_TABLE,
	p_OUT IN OUT NOCOPY DETERMINANT_TABLE
	);

PROCEDURE GET_PROJECTION_DETERMINANTS
    (
	p_CALENDAR_ID IN NUMBER,
	p_PROJECTION_TYPE IN VARCHAR,
	p_TEMPLATE_ID IN NUMBER,
	p_STATION_ID IN NUMBER,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_AS_OF_DATE IN DATE,
	p_TRACE_ON BOOLEAN,
	p_DETERMINANTS IN OUT NOCOPY DETERMINANT_TABLE
	);

PROCEDURE GET_HOURLY_FORWARD_PRICES
	(
	p_MARKET_PRICE_ID IN NUMBER,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_WORK_ID OUT NUMBER
	);

PROCEDURE APPLY_CONSUMPTION_CHARGE
	(
	p_PRODUCT_ID IN NUMBER,
	p_COMPONENT IN COMPONENT%ROWTYPE,
	p_DETERMINANTS IN DETERMINANT_TABLE,
	p_CHARGE_COMPONENTS IN OUT NOCOPY CHARGE_COMPONENT_TABLE
	);

FUNCTION GET_INITIAL_DATE_FOR_INTERVAL
    (
	p_DATE IN DATE,
	p_INTERVAL IN VARCHAR,
	p_BILL_CYCLE_ID IN NUMBER
	) RETURN DATE;

FUNCTION GET_NEXT_DATE_FOR_INTERVAL
    (
	p_DATE IN DATE,
	p_INTERVAL IN VARCHAR,
	p_BILL_CYCLE_ID IN NUMBER
	) RETURN DATE;

FUNCTION GET_COMPONENT_FLAT_RATE
    (
	p_COMPONENT_ID IN NUMBER,
	p_QUANTITY IN OUT NUMBER,
	p_SERVICE_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_COMPONENT_TOU_RATE
    (
	p_COMPONENT_ID IN NUMBER,
	p_PERIOD_ID IN NUMBER,
	p_SERVICE_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_COMPONENT_TIERED_RATE
    (
	p_COMPONENT_ID IN NUMBER,
	p_QUANTITY IN OUT NUMBER,
	p_SERVICE_DATE IN DATE,
	p_DEMAND IN NUMBER DEFAULT NULL
	) RETURN NUMBER;

FUNCTION GET_COMPONENT_BLOCK_RATE
    (
	p_COMPONENT_ID IN NUMBER,
	p_QUANTITY IN OUT NUMBER,
	p_SERVICE_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_COMPOSITE_COMPONENT_RATE
    (
	p_COMPONENT_ID IN NUMBER,
	p_CHARGE_TYPE IN CHAR,
	p_PERIOD_ID IN NUMBER,
	p_ENERGY IN OUT NUMBER,
	p_DEMAND IN NUMBER,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_COMPONENT_MARKET_RATE
	(
	p_COMPONENT_ID IN NUMBER,
	p_MARKET_PRICE_ID IN NUMBER,
	p_SERVICE_DATE IN DATE,
    p_MARKET_PRICE_TABLE IN OUT GA.NUMBER_TABLE,
	p_PRICE_CODE IN CHAR DEFAULT 'A'
	) RETURN NUMBER;

PROCEDURE GET_CHARGE_QUANTITY
    (
	p_COMPONENT IN COMPONENT%ROWTYPE,
	p_PERIOD_ID IN NUMBER,
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_DETERMINANTS IN DETERMINANT_TABLE,
	p_ENERGY OUT NUMBER,
	p_DEMAND OUT NUMBER,
    p_NEED_PERIOD_IDs IN BOOLEAN := FALSE,
    p_INTERVAL_DETERMINANTS IN BOOLEAN := FALSE
	);

FUNCTION GET_COMPOSITE_COMPONENT_QUANT
    (
	p_COMPONENT_ID IN NUMBER,
	p_CHARGE_TYPE IN CHAR,
	p_ENERGY IN OUT NUMBER,
	p_DEMAND IN NUMBER,
	p_BEGIN_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_COMPONENT_FACTOR
    (
	p_COMPONENT_ID IN NUMBER,
	p_SERVICE_DATE IN DATE
	) RETURN NUMBER;

FUNCTION GET_COMPONENT
    (
	p_COMPONENT_ID IN NUMBER
	) RETURN COMPONENT%ROWTYPE;

g_NO_SUB_TYPE CHAR(1) := '?';
g_TRACE_TARGET CHAR(1) := 'T';
g_UNKNOWN NUMBER(4) := -999;
g_ANYTIME_SEASON NUMBER(1) := 1;
g_ANYTIME_TEMPLATE NUMBER(1) := 1;
g_PROJECTION_TEMPLATE NUMBER(1) := 2;
g_FORWARDS FORWARD_TABLE := FORWARD_TABLE();
g_TOU_PERIODS TOU_TABLE := TOU_TABLE();
g_SECOND NUMBER(6,5) :=  .00001;

TYPE COMPONENT_BAND_TABLE IS TABLE OF COMPONENT_IMBALANCE_BAND%ROWTYPE INDEX BY BINARY_INTEGER;

END;
/