CREATE OR REPLACE PACKAGE EC AS
--Revision $Revision: 1.13 $

--PRAGMA RESTRICT_REFERENCES(GA, WNDS, WNPS, RNDS);

--Entity Constants package.

--===================================
--     External System Constants
--===================================
-- Constants defining an EXTERNAL_SYSTEM_ID for the EXTERNAL_SYSTEM table.
ES_IMO CONSTANT NUMBER(9) := 100;
ES_MISO CONSTANT NUMBER(9) := 200;
ES_NYISO CONSTANT NUMBER(9) := 400;
ES_PJM CONSTANT NUMBER(9) := 500;
ES_OASIS CONSTANT NUMBER(9) := 600;
ES_ISONE CONSTANT NUMBER(9) := 700;
ES_ERCOT CONSTANT NUMBER(9) := 900;
ES_SEM CONSTANT NUMBER(9) := 1000;
ES_TSIN CONSTANT NUMBER(9) := 1100;
ES_NYISO_DSS CONSTANT NUMBER(9) := 1200;
ES_SMART_GRID CONSTANT NUMBER(9) := 1300;
ES_SCHEDULE_MANAGEMENT CONSTANT NUMBER(9) := 1400;
ES_TDIE CONSTANT NUMBER(9) := 1500;

--These constants are no longer supported markets:
--ES_CAISO CONSTANT NUMBER(9) := 300;
--ES_CA_MRTU CONSTANT NUMBER(9) := 800;

-- other systems - not ISOs though
ES_MEX_SWITCHBOARD CONSTANT NUMBER(9) := 3000;
ES_SMTP CONSTANT NUMBER(9) := 4000;
ES_MONACO CONSTANT NUMBER(9) := 5000;

--===================================
--     Entity Domain Constants
--===================================
-- Constants for the ENTITY_DOMAIN_ID on the ENTITY_DOMAIN table.
-- Can be generated with this query:
/*
 	SELECT 'ED_' ||ENTITY_DOMAIN_TABLE_ALIAS||' CONSTANT NUMBER(9) := ' || TO_CHAR(ENTITY_DOMAIN_ID) || ';'
 	FROM ENTITY_DOMAIN X
	WHERE ENTITY_DOMAIN_ID <> 0
 	ORDER BY ENTITY_DOMAIN_ID DESC;
*/

ED_EDC CONSTANT NUMBER(9) := -100;
ED_ESP CONSTANT NUMBER(9) := -110;
ED_MRSP CONSTANT NUMBER(9) := -120;
ED_SC CONSTANT NUMBER(9) := -130;
ED_TP CONSTANT NUMBER(9) := -140;
ED_CA CONSTANT NUMBER(9) := -150;
ED_PSE CONSTANT NUMBER(9) := -160;
ED_ACCOUNT CONSTANT NUMBER(9) := -170;
ED_SERVICE_LOCATION CONSTANT NUMBER(9) := -180;
ED_METER CONSTANT NUMBER(9) := -190;
ED_TRANSACTION CONSTANT NUMBER(9) := -200;
ED_SERVICE_POINT CONSTANT NUMBER(9) := -210;
ED_QUOTE_REQUEST CONSTANT NUMBER(9) := -220;
ED_POOL CONSTANT NUMBER(9) := -230;
ED_CONTRACT CONSTANT NUMBER(9) := -240;
ED_BILL_PARTY CONSTANT NUMBER(9) := -250;
ED_ACCOUNT_GROUP CONSTANT NUMBER(9) := -260;
ED_SERVICE_CONSUMPTION CONSTANT NUMBER(9) := -280;
ED_PIPELINE CONSTANT NUMBER(9) := -290;
ED_SCHEDULER CONSTANT NUMBER(9) := -310;
ED_ANCILLARY_SERVICE CONSTANT NUMBER(9) := -320;
ED_IT_COMMODITY CONSTANT NUMBER(9) := -330;
ED_SERVICE_REGION CONSTANT NUMBER(9) := -340;
ED_PATH CONSTANT NUMBER(9) := -350;
ED_SEGMENT CONSTANT NUMBER(9) := -360;
ED_SERVICE_TYPE CONSTANT NUMBER(9) := -370;
ED_SUB_STATION CONSTANT NUMBER(9) := -380;
ED_SUB_STATION_METER CONSTANT NUMBER(9) := -390;
ED_BILL_CYCLE CONSTANT NUMBER(9) := -410;
ED_SALES_REP CONSTANT NUMBER(9) := -460;
ED_SCHEDULE_GROUP CONSTANT NUMBER(9) := -480;
ED_SERVICE_AREA CONSTANT NUMBER(9) := -490;
ED_SERVICE_ZONE CONSTANT NUMBER(9) := -500;
ED_AREA CONSTANT NUMBER(9) := -510;
ED_SYSTEM_EVENT CONSTANT NUMBER(9) := -520;
ED_SYSTEM_LOAD CONSTANT NUMBER(9) := -530;
ED_WEATHER_PARAMETER CONSTANT NUMBER(9) := -540;
ED_WEATHER_STATION CONSTANT NUMBER(9) := -550;
ED_CUSTOMER CONSTANT NUMBER(9) := -560;
ED_CONTACT CONSTANT NUMBER(9) := -570;
ED_CATEGORY CONSTANT NUMBER(9) := -590;
ED_CUSTOMER_CONSUMPTION CONSTANT NUMBER(9) := -600;
ED_MARKET_PRICE CONSTANT NUMBER(9) := -610;
ED_PRODUCT CONSTANT NUMBER(9) := -620;
ED_COMPONENT CONSTANT NUMBER(9) := -630;
ED_CALC_COMPONENT CONSTANT NUMBER(9) := -631;
ED_INVOICE_GROUP CONSTANT NUMBER(9) := -640;
ED_INTERCHANGE_CONTRACT CONSTANT NUMBER(9) := -650;
ED_CONTRACT_LIMIT CONSTANT NUMBER(9) := -660;
ED_SUPPLY_RESOURCE CONSTANT NUMBER(9) := -670;
ED_TRANSACTION_TRAIT_GROUP CONSTANT NUMBER(9) := -680;
ED_PORTFOLIO CONSTANT NUMBER(9) := -720;
ED_STATEMENT_TYPE CONSTANT NUMBER(9) := -740;
ED_RESOURCE_GROUP CONSTANT NUMBER(9) := -750;
ED_HOLIDAY CONSTANT NUMBER(9) := -770;
ED_HOLIDAY_SET CONSTANT NUMBER(9) := -780;
ED_PERIOD CONSTANT NUMBER(9) := -790;
ED_SEASON CONSTANT NUMBER(9) := -800;
ED_TEMPLATE CONSTANT NUMBER(9) := -810;
ED_DAY_TYPE_TEMPLATE CONSTANT NUMBER(9) := -811;
ED_GEOGRAPHY CONSTANT NUMBER(9) := -820;
ED_ENTITY_DOMAIN CONSTANT NUMBER(9) := -830;
ED_LOAD_PROFILE CONSTANT NUMBER(9) := -840;
ED_EXTERNAL_TRANSACTION CONSTANT NUMBER(9) := -850;
ED_SCENARIO CONSTANT NUMBER(9) := -860;
ED_CASE_LABEL CONSTANT NUMBER(9) := -870;
ED_SETTLEMENT_TYPE CONSTANT NUMBER(9) := -880;
ED_SYSTEM_ACTION CONSTANT NUMBER(9) := -890;
ED_SYSTEM_REALM CONSTANT NUMBER(9) := -900;
ED_FORMULA_REALM CONSTANT NUMBER(9) := -901;
ED_CALC_REALM CONSTANT NUMBER(9) := -902;
ED_HEAT_RATE_CURVE CONSTANT NUMBER(9) := -950;
ED_SYSTEM_ALERT CONSTANT NUMBER(9) := -960;
ED_ETAG CONSTANT NUMBER(9) := -970;
ED_CONDITIONAL_FORMAT CONSTANT NUMBER(9) := -980;
ED_OASIS_NODE CONSTANT NUMBER(9) := -990;
ED_EXTERNAL_SYSTEM CONSTANT NUMBER(9) := -1000;
ED_ENTITY_GROUP CONSTANT NUMBER(9) := -1010;
ED_CALC_PROCESS CONSTANT NUMBER(9) := -1020;
ED_SUB_STATION_METER_POINT CONSTANT NUMBER(9) := -1030;
ED_MEASUREMENT_SOURCE CONSTANT NUMBER(9) := -1040;
ED_SYSTEM_TABLE CONSTANT NUMBER(9) := -1050;
ED_REACTOR_PROCEDURE CONSTANT NUMBER(9) := -1060;
ED_JOB_THREAD CONSTANT NUMBER(9) := -1070;
ED_LOSS_FACTOR CONSTANT NUMBER(9) := -1080;
ED_DATA_LOCK_GROUP CONSTANT NUMBER(9) := -1090;
ED_CALENDAR CONSTANT NUMBER(9) := -1100;
ED_GROWTH_PATTERN CONSTANT NUMBER(9) := -1110;
ED_DER_TYPE CONSTANT NUMBER(9) := -1120;
ED_DER CONSTANT NUMBER(9) := -1130;
ED_PROGRAM CONSTANT NUMBER(9) := -1140;
ED_VPP CONSTANT NUMBER(9) := -1150;
ED_DR_EVENT CONSTANT NUMBER(9) := -1160;
ED_TX_FEEDER CONSTANT NUMBER(9) := -1170;
ED_TX_FEEDER_SEGMENT CONSTANT NUMBER(9) := -1180;
ED_PROXY_DAY_METHOD CONSTANT NUMBER(9) := -1190;
ED_LOAD_PROFILE_LIBRARY CONSTANT NUMBER(9) := -1200;

FUNCTION WHAT_VERSION RETURN VARCHAR2;

END EC;
/
CREATE OR REPLACE PACKAGE BODY EC AS
FUNCTION WHAT_VERSION RETURN VARCHAR2 IS
BEGIN
    RETURN '$Revision: 1.13 $';
END WHAT_VERSION;
END EC;
/
