CREATE OR REPLACE PACKAGE GA_UTIL IS
-- $Revision: 1.3 $

FUNCTION WHAT_VERSION RETURN VARCHAR2;

FUNCTION LOAD_BOOLEAN
	(
	p_MODULE IN VARCHAR2,
	p_SETTING_NAME IN VARCHAR2,
	p_DEFAULT_VALUE IN BOOLEAN := FALSE
	) RETURN BOOLEAN;

FUNCTION LOAD_NUMBER
	(
	p_MODULE IN VARCHAR2,
	p_SETTING_NAME IN VARCHAR2,
	p_DEFAULT_VALUE IN NUMBER := 0,
	p_MIN_VAL IN NUMBER := NULL,
	p_MAX_VAL IN NUMBER := NULL
	) RETURN NUMBER;

FUNCTION LOAD_NUMBER
	(
	p_MODULE IN VARCHAR2,
	p_SETTING_NAME IN VARCHAR2,
	p_DEFAULT_VALUE IN NUMBER := 0,
	p_MUST_BE_ONE_OF IN NUMBER_COLLECTION
	) RETURN NUMBER;

FUNCTION LOAD_STRING
	(
	p_MODULE IN VARCHAR2,
	p_SETTING_NAME IN VARCHAR2,
	p_DEFAULT_VALUE IN VARCHAR2 := NULL,
	p_MIN_LENGTH IN PLS_INTEGER := NULL,
	p_MAX_LENGTH IN PLS_INTEGER := NULL,
	p_CASE_SENSITIVE IN BOOLEAN := FALSE
	) RETURN VARCHAR2;

FUNCTION LOAD_STRING
	(
	p_MODULE IN VARCHAR2,
	p_SETTING_NAME IN VARCHAR2,
	p_DEFAULT_VALUE IN VARCHAR2,
	p_MUST_BE_ONE_OF IN STRING_COLLECTION,
	p_CASE_SENSITIVE IN BOOLEAN := FALSE
	) RETURN VARCHAR2;

END GA_UTIL;
/
