CREATE OR REPLACE PACKAGE MEX_ERCOT_SETTLEMENT IS
-- $Revision: 1.10 $

  -- Author  : CNAVALTA
  -- Created : 4/19/2006 9:22:43 AM
  -- Purpose : import files needed for settlement

FUNCTION WHAT_VERSION RETURN VARCHAR2;

PROCEDURE FETCH_TOTAL_CHARGES_FILE
	(
	p_BEGIN_DATE IN DATE,
    p_END_DATE IN DATE,
    p_SETTLEMENT_TYPE IN VARCHAR2,
    p_SETTLEMENT_PERIOD_TYPE IN VARCHAR2,
	p_CRED	IN mex_credentials,
	p_LOG_ONLY IN NUMBER,
	p_RECORDS OUT MEX_ERCOT_CHARGE_TOTAL_TBL,
	p_STATUS OUT NUMBER,
	p_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
	);

PROCEDURE PARSE_SETTLEMENT_FILE
	(
    v_RESPONSE_CLOB IN CLOB,
    p_RECORDS IN OUT MEX_ERCOT_CHARGE_TOTAL_TBL,
	p_STATUS OUT NUMBER,
	p_MESSAGE OUT VARCHAR2
    );

PROCEDURE FETCH_TOTAL_CHARGES_XLS_FILE
	(
     p_RESPONSE_XLS_FILE_LIST XMLTYPE,
     p_CRED IN mex_credentials,
	 p_LOG_ONLY	IN NUMBER,
     p_RECORDS OUT MEX_ERCOT_CHARGE_TOTAL_TBL,
     p_STATUS OUT NUMBER,
	 p_MESSAGE OUT VARCHAR2,
	 p_LOGGER IN OUT mm_logger_adapter
	);

END MEX_ERCOT_SETTLEMENT;
/