CREATE OR REPLACE TRIGGER ACCOUNT_UPDATE
	BEFORE INSERT OR UPDATE ON ACCOUNT
	FOR EACH ROW
BEGIN
	:new.ACCOUNT_DISPLAY_NAME := :new.ACCOUNT_NAME;
	:new.IS_AGGREGATE_ACCOUNT := CASE WHEN :new.ACCOUNT_MODEL_OPTION = 'Aggregate' THEN 1 ELSE 0 END;
END ACCOUNT_UPDATE;
/
