CREATE OR REPLACE TRIGGER ACCOUNT_SERVICE_LOC_UPDATE
	AFTER UPDATE ON ACCOUNT_SERVICE_LOCATION
	FOR EACH ROW

DECLARE
v_BEGIN_START DATE;
v_BEGIN_STOP DATE;
v_END_START DATE;
v_END_STOP DATE;

BEGIN

	IF NOT GA.ENABLE_SERVICE_RETENTION THEN

-- Determine the Begin and End Date Ranges reflecting the User Specified date modifications.
		BEGIN_END_START_STOP_RANGE(:old.BEGIN_DATE, :new.BEGIN_DATE, :old.END_DATE, :new.END_DATE, v_BEGIN_START, v_BEGIN_STOP, v_END_START, v_END_STOP);

		DELETE SERVICE
		WHERE SERVICE_ID IN
			(SELECT DISTINCT(C.SERVICE_ID)
			FROM ACCOUNT_SERVICE A,
				SERVICE B,
				SERVICE_STATE C
			WHERE A.ACCOUNT_ID = :old.ACCOUNT_ID
				AND A.SERVICE_LOCATION_ID = :old.SERVICE_LOCATION_ID
				AND B.ACCOUNT_SERVICE_ID = A.ACCOUNT_SERVICE_ID
				AND C.SERVICE_ID = B.SERVICE_ID
				AND (C.SERVICE_DATE BETWEEN v_BEGIN_START AND v_BEGIN_STOP
				OR C.SERVICE_DATE BETWEEN v_END_START AND v_END_STOP));
	END IF;
	
END ACCOUNT_SERVICE_LOC_UPDATE;
/ 
