CREATE OR REPLACE TRIGGER AREA_LOAD_UPDATE 
	BEFORE INSERT OR UPDATE ON AREA_LOAD
	FOR EACH ROW 
BEGIN 
	IF NOT GA.VERSION_AREA_LOAD THEN
		:new.AS_OF_DATE := LOW_DATE; 
	END IF; 
END AREA_LOAD_UPDATE;
/ 
