CREATE OR REPLACE TRIGGER LOSS_FACTOR_PATTERN_UPDATE
  BEFORE UPDATE OR INSERT ON LOSS_FACTOR_PATTERN  
  FOR EACH ROW
BEGIN
  -- IF THE LOSS VALUE HAS CHANGED, UPDATE EXPANSION VALUE
  -- AND VICE VERSA (ASSUME EXPANSION IS CORRECT IF BOTH HAVE CHANGED)
  IF :new.LOSS_VAL IS NULL AND :new.EXPANSION_VAL IS NULL THEN
  	:new.LOSS_VAL := 0.0;
	:new.EXPANSION_VAL := 0.0;
  ELSE IF (:new.LOSS_VAL IS NOT NULL AND :OLD.LOSS_VAL IS NULL )
		   OR :old.LOSS_VAL != :new.LOSS_VAL 
		   OR :new.EXPANSION_VAL IS NULL THEN
  		:new.EXPANSION_VAL := (1/(1 - :new.LOSS_VAL)) - 1;
	  ELSE
		:new.LOSS_VAL := 1 - 1 / (1 + :new.EXPANSION_VAL) ;
	  END IF;
  END IF;
END LOSS_FACTOR_PATTERN_UPDATE;
/
