CREATE OR REPLACE TRIGGER METER_DELETE
	AFTER DELETE ON METER
	FOR EACH ROW
BEGIN
	DELETE SERVICE_LOCATION_METER WHERE METER_ID = :old.METER_ID;
	DELETE METER_PRODUCT WHERE METER_ID = :old.METER_ID;
	DELETE METER_CALENDAR WHERE METER_ID = :old.METER_ID;
	DELETE METER_LOSS_FACTOR WHERE METER_ID = :old.METER_ID;
	DELETE METER_ANCILLARY_SERVICE WHERE METER_ID = :old.METER_ID;
	DELETE ACCOUNT_SERVICE WHERE METER_ID = :old.METER_ID;
END METER_DELETE;
/
