CREATE OR REPLACE TRIGGER PERIOD_DELETE
	AFTER DELETE ON PERIOD
	FOR EACH ROW

DECLARE

BEGIN
	IF :old.PERIOD_ID < 100 THEN
		ERRS.RAISE(MSGCODES.c_ERR_PRIVILEGES, :old.PERIOD_NAME || ' is a system Period which cannot be deleted.');
	END IF;
	DELETE COMPONENT_TOU_RATE WHERE PERIOD_ID = :old.PERIOD_ID;
END PERIOD_DELETE;
/
