CREATE OR REPLACE TRIGGER RTO_ROLLUP_INSERT
	BEFORE INSERT ON RTO_ROLLUP
	FOR EACH ROW
DECLARE v_ROLLUP_LEVEL NUMBER;
BEGIN
	IF :new.ROLLUP_PARENT_ID = 0 THEN
		v_ROLLUP_LEVEL := 0;
	ELSE
		BEGIN
			SELECT ROLLUP_LEVEL
			INTO v_ROLLUP_LEVEL
			FROM RTO_ROLLUP
			WHERE ROLLUP_ID = :new.ROLLUP_PARENT_ID;

			EXCEPTION
				WHEN NO_DATA_FOUND THEN
					v_ROLLUP_LEVEL := 0;
				WHEN OTHERS THEN
				RAISE;
		END;
	END IF;
	:new.ROLLUP_LEVEL := v_ROLLUP_LEVEL + 1;
END RTO_ROLLUP_INSERT;
/
