CREATE OR REPLACE TRIGGER SYSTEM_OBJECT_UPDATE
	BEFORE INSERT 
	OR UPDATE OF
		PARENT_OBJECT_ID, 
		OBJECT_NAME, 
		OBJECT_INDEX, 
		OBJECT_CATEGORY, 
		OBJECT_TYPE, 
		OBJECT_ALIAS, 
		OBJECT_DESC, 
		OBJECT_DISPLAY_NAME, 
		OBJECT_TAG, 
		OBJECT_ORDER, 
		OBJECT_IS_HIDDEN
	ON SYSTEM_OBJECT
	FOR EACH ROW
BEGIN
	IF INSERTING
			OR :new.PARENT_OBJECT_ID <> :old.PARENT_OBJECT_ID
			OR :new.OBJECT_NAME <> :old.OBJECT_NAME
			OR :new.OBJECT_INDEX <> :old.OBJECT_INDEX
			OR :new.OBJECT_CATEGORY <> :old.OBJECT_CATEGORY
			OR :new.OBJECT_TYPE <> :old.OBJECT_TYPE
			OR :new.OBJECT_ALIAS <> :old.OBJECT_ALIAS
			OR :new.OBJECT_DESC <> :old.OBJECT_DESC
			OR :new.OBJECT_DISPLAY_NAME <> :old.OBJECT_DISPLAY_NAME
			OR :new.OBJECT_TAG <> :old.OBJECT_TAG
			OR :new.OBJECT_ORDER <> :old.OBJECT_ORDER
			OR :new.OBJECT_IS_HIDDEN <> :old.OBJECT_IS_HIDDEN THEN
		
		:new.IS_MODIFIED := 1;
	END IF;
		
END SYSTEM_OBJECT_UPDATE;
/
