DECLARE

	PROCEDURE PUT_STATEMENT_TYPE(
		p_STATEMENT_TYPE_NAME IN VARCHAR2,
		p_STATEMENT_TYPE_ORDER IN NUMBER,
		p_STATEMENT_TYPE_ID IN NUMBER := 0
		) IS
	v_STATEMENT_TYPE_ID NUMBER;
	BEGIN
		BEGIN
			SELECT STATEMENT_TYPE_ID INTO v_STATEMENT_TYPE_ID FROM STATEMENT_TYPE
			WHERE UPPER(STATEMENT_TYPE_ALIAS) = 'MISO '||UPPER(TRIM(p_STATEMENT_TYPE_NAME));
		EXCEPTION
			WHEN OTHERS THEN
				v_STATEMENT_TYPE_ID := p_STATEMENT_TYPE_ID;
		END;
		
		IO.PUT_STATEMENT_TYPE(v_STATEMENT_TYPE_ID, p_STATEMENT_TYPE_NAME, 'MISO '||p_STATEMENT_TYPE_NAME, 'MISO '||p_STATEMENT_TYPE_NAME, v_STATEMENT_TYPE_ID, p_STATEMENT_TYPE_ORDER);
	END PUT_STATEMENT_TYPE;

BEGIN
	PUT_STATEMENT_TYPE('S7',1,1);
	PUT_STATEMENT_TYPE('S14',2,2);
	PUT_STATEMENT_TYPE('S55',3,3);
	PUT_STATEMENT_TYPE('S105',4);
END;
/
