CREATE OR REPLACE PROCEDURE ASSERT
	(
	p_CONDITION IN BOOLEAN,
	p_MESSAGE IN VARCHAR2,
	p_MESSAGE_CODE IN VARCHAR2 := MSGCODES.c_ERR_ASSERT
	) IS
BEGIN
	IF NOT NVL(p_CONDITION,FALSE) THEN
		ERRS.RAISE(p_MESSAGE_CODE, p_MESSAGE);
	END IF;
END ASSERT;
/
