CREATE OR REPLACE PROCEDURE SET_SYSTEM_STATE 
	(
	p_SETTING_NAME IN VARCHAR2,
	p_NUMBER_VAL IN NUMBER DEFAULT NULL,
	p_STRING_VAL IN VARCHAR2 DEFAULT NULL,
	p_DATE_VAL IN DATE DEFAULT NULL
	) AS
-- Revision: $Revision: 1.2 $
BEGIN
	UPDATE SYSTEM_STATE
	SET NUMBER_VAL = p_NUMBER_VAL,
		STRING_VAL = p_STRING_VAL,
		DATE_VAL = p_DATE_VAL
	WHERE SETTING_NAME = p_SETTING_NAME;

	IF SQL%NOTFOUND THEN
		INSERT INTO SYSTEM_STATE (
			SETTING_NAME,
			NUMBER_VAL,
			STRING_VAL,
			DATE_VAL)
		VALUES (
			p_SETTING_NAME,
			p_NUMBER_VAL,
			p_STRING_VAL,
			p_DATE_VAL);
	END IF;
END SET_SYSTEM_STATE;
/
