-- Run This Script Multiple Time Until There Are No Exceptions--
SET SERVEROUTPUT ON;
DECLARE
CURSOR c_SELECT(p_OBJECT_TYPE IN VARCHAR2) IS
   SELECT OBJECT_NAME, OBJECT_TYPE
   FROM USER_OBJECTS
   WHERE (OBJECT_NAME LIKE 'MEX_%' OR OBJECT_NAME LIKE 'MM_%' OR OBJECT_NAME LIKE 'PJM_%')
      AND p_OBJECT_TYPE IN ('ALL', OBJECT_TYPE)
   ORDER BY CASE WHEN OBJECT_TYPE = 'TYPE' AND OBJECT_NAME LIKE '%TABLE' THEN 1 ELSE 2 END;
v_SQLERRM VARCHAR2(1000);
BEGIN
   FOR v_SELECT IN c_SELECT('ALL') LOOP
      BEGIN
         EXECUTE IMMEDIATE 'DROP ' || v_SELECT.OBJECT_TYPE || ' ' || v_SELECT.OBJECT_NAME || CASE v_SELECT.OBJECT_TYPE WHEN 'TABLE' THEN ' CASCADE CONSTRAINTS' WHEN 'TYPE' THEN ' FORCE' ELSE '' END;
      EXCEPTION
         WHEN OTHERS THEN
            IF SQLCODE <> -04043 THEN
               v_SQLERRM := SQLERRM;
               DBMS_OUTPUT.PUT_LINE('Type: ' || v_SELECT.OBJECT_TYPE || ', Object: ' || v_SELECT.OBJECT_NAME || ', Error: ' || v_SQLERRM);
            END IF;
      END;
   END LOOP; 
END;
/
