ALTER TRIGGER ZREALM_ACCOUNT DISABLE;

Insert into ACCOUNT(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_DESC, ACCOUNT_EXTERNAL_IDENTIFIER, ACCOUNT_MODEL_OPTION, ACCOUNT_METER_TYPE, ACCOUNT_DISPLAY_NAME, ACCOUNT_ROLLUP_ID, IS_EXTERNAL_INTERVAL_USAGE, IS_EXTERNAL_BILLED_USAGE, IS_AGGREGATE_ACCOUNT, IS_UFE_PARTICIPANT, IS_CREATE_SETTLEMENT_PROFILE, IS_EXTERNAL_FORECAST, IS_SUB_AGGREGATE, TX_SERVICE_TYPE_ID, MODEL_ID, ENTRY_DATE)
Values(101, 'GF_BWI', '','GF_BWI', 'Aggregate', 'Period', 'GF_BWI', 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, SYSDATE);
Insert into ACCOUNT(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_DESC, ACCOUNT_EXTERNAL_IDENTIFIER, ACCOUNT_MODEL_OPTION, ACCOUNT_METER_TYPE, ACCOUNT_DISPLAY_NAME, ACCOUNT_ROLLUP_ID, IS_EXTERNAL_INTERVAL_USAGE, IS_EXTERNAL_BILLED_USAGE, IS_AGGREGATE_ACCOUNT, IS_UFE_PARTICIPANT, IS_CREATE_SETTLEMENT_PROFILE, IS_EXTERNAL_FORECAST, IS_SUB_AGGREGATE, TX_SERVICE_TYPE_ID, MODEL_ID, ENTRY_DATE)
Values(102, 'GL_BWI', '', 'GL_BWI', 'Aggregate', 'Period','GL_BWI',     0, 0, 0, 1, 1, 0, 0, 0, 0, 1, SYSDATE);
Insert into ACCOUNT(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_DESC, ACCOUNT_EXTERNAL_IDENTIFIER, ACCOUNT_MODEL_OPTION, ACCOUNT_METER_TYPE, ACCOUNT_DISPLAY_NAME, ACCOUNT_ROLLUP_ID, IS_EXTERNAL_INTERVAL_USAGE, IS_EXTERNAL_BILLED_USAGE, IS_AGGREGATE_ACCOUNT, IS_UFE_PARTICIPANT, IS_CREATE_SETTLEMENT_PROFILE, IS_EXTERNAL_FORECAST, IS_SUB_AGGREGATE, TX_SERVICE_TYPE_ID, MODEL_ID, ENTRY_DATE)
Values(103, 'GS_BWI', '', 'GS_BWI', 'Aggregate', 'Period', 'GS_BWI',    0, 0, 0, 1, 1, 0, 0, 0, 0, 1, SYSDATE);
Insert into ACCOUNT(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_DESC, ACCOUNT_EXTERNAL_IDENTIFIER, ACCOUNT_MODEL_OPTION, ACCOUNT_METER_TYPE, ACCOUNT_DISPLAY_NAME, ACCOUNT_ROLLUP_ID, IS_EXTERNAL_INTERVAL_USAGE, IS_EXTERNAL_BILLED_USAGE, IS_AGGREGATE_ACCOUNT, IS_UFE_PARTICIPANT, IS_CREATE_SETTLEMENT_PROFILE, IS_EXTERNAL_FORECAST, IS_SUB_AGGREGATE, TX_SERVICE_TYPE_ID, MODEL_ID, ENTRY_DATE)
Values(104, 'G_BWI', '','G_BWI', 'Aggregate', 'Period', 'G_BWI',        0, 0, 0, 1, 1, 0, 0, 0, 0, 1, SYSDATE);
Insert into ACCOUNT(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_DESC, ACCOUNT_EXTERNAL_IDENTIFIER, ACCOUNT_MODEL_OPTION, ACCOUNT_METER_TYPE, ACCOUNT_DISPLAY_NAME, ACCOUNT_ROLLUP_ID, IS_EXTERNAL_INTERVAL_USAGE, IS_EXTERNAL_BILLED_USAGE, IS_AGGREGATE_ACCOUNT, IS_UFE_PARTICIPANT, IS_CREATE_SETTLEMENT_PROFILE, IS_EXTERNAL_FORECAST, IS_SUB_AGGREGATE, TX_SERVICE_TYPE_ID, MODEL_ID, ENTRY_DATE)
Values(105, 'PL_BWI', '', 'PL_BWI', 'Aggregate', 'Period', 'PL_BWI',    0, 0, 0, 1, 1, 0, 0, 0, 0, 1, SYSDATE);
Insert into ACCOUNT(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_DESC, ACCOUNT_EXTERNAL_IDENTIFIER, ACCOUNT_MODEL_OPTION, ACCOUNT_METER_TYPE, ACCOUNT_DISPLAY_NAME, ACCOUNT_ROLLUP_ID, IS_EXTERNAL_INTERVAL_USAGE, IS_EXTERNAL_BILLED_USAGE, IS_AGGREGATE_ACCOUNT, IS_UFE_PARTICIPANT, IS_CREATE_SETTLEMENT_PROFILE, IS_EXTERNAL_FORECAST, IS_SUB_AGGREGATE, TX_SERVICE_TYPE_ID, MODEL_ID, ENTRY_DATE)
Values(106, 'RH_BWI', '','RH_BWI', 'Aggregate', 'Period', 'RH_BWI',     0, 0, 0, 1, 1, 0, 0, 0, 0, 1, SYSDATE);
Insert into ACCOUNT(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_DESC, ACCOUNT_EXTERNAL_IDENTIFIER, ACCOUNT_MODEL_OPTION, ACCOUNT_METER_TYPE, ACCOUNT_DISPLAY_NAME, ACCOUNT_ROLLUP_ID, IS_EXTERNAL_INTERVAL_USAGE, IS_EXTERNAL_BILLED_USAGE, IS_AGGREGATE_ACCOUNT, IS_UFE_PARTICIPANT, IS_CREATE_SETTLEMENT_PROFILE, IS_EXTERNAL_FORECAST, IS_SUB_AGGREGATE, TX_SERVICE_TYPE_ID, MODEL_ID, ENTRY_DATE)
Values(107, 'RLH_BWI', '', 'RLH_BWI', 'Aggregate', 'Period', 'RLH_BWI', 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, SYSDATE);
Insert into ACCOUNT(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_DESC, ACCOUNT_EXTERNAL_IDENTIFIER, ACCOUNT_MODEL_OPTION, ACCOUNT_METER_TYPE, ACCOUNT_DISPLAY_NAME, ACCOUNT_ROLLUP_ID, IS_EXTERNAL_INTERVAL_USAGE, IS_EXTERNAL_BILLED_USAGE, IS_AGGREGATE_ACCOUNT, IS_UFE_PARTICIPANT, IS_CREATE_SETTLEMENT_PROFILE, IS_EXTERNAL_FORECAST, IS_SUB_AGGREGATE, TX_SERVICE_TYPE_ID, MODEL_ID, ENTRY_DATE)
Values(108, 'RL_BWI', '', 'RL_BWI', 'Aggregate', 'Period','RL_BWI',     0, 0, 0, 1, 1, 0, 0, 0, 0, 1, SYSDATE);
Insert into ACCOUNT(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_DESC, ACCOUNT_EXTERNAL_IDENTIFIER, ACCOUNT_MODEL_OPTION, ACCOUNT_METER_TYPE, ACCOUNT_DISPLAY_NAME, ACCOUNT_ROLLUP_ID, IS_EXTERNAL_INTERVAL_USAGE, IS_EXTERNAL_BILLED_USAGE, IS_AGGREGATE_ACCOUNT, IS_UFE_PARTICIPANT, IS_CREATE_SETTLEMENT_PROFILE, IS_EXTERNAL_FORECAST, IS_SUB_AGGREGATE, TX_SERVICE_TYPE_ID, MODEL_ID, ENTRY_DATE)
Values(109, 'R_BWI', '','R_BWI', 'Aggregate', 'Period','R_BWI',         0, 0, 0, 1, 1, 0, 0, 0, 0, 1, SYSDATE);
Insert into ACCOUNT(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_DESC, ACCOUNT_EXTERNAL_IDENTIFIER, ACCOUNT_MODEL_OPTION, ACCOUNT_METER_TYPE, ACCOUNT_DISPLAY_NAME, ACCOUNT_ROLLUP_ID, IS_EXTERNAL_INTERVAL_USAGE, IS_EXTERNAL_BILLED_USAGE, IS_AGGREGATE_ACCOUNT, IS_UFE_PARTICIPANT, IS_CREATE_SETTLEMENT_PROFILE, IS_EXTERNAL_FORECAST, IS_SUB_AGGREGATE, TX_SERVICE_TYPE_ID, MODEL_ID, ENTRY_DATE)
Values(110, 'SL_BWI', '','SL_BWI', 'Aggregate', 'Period','SL_BWI',      0, 0, 0, 1, 1, 0, 0, 0, 0, 1, SYSDATE);
INSERT INTO ACCOUNT_LOSS_FACTOR(CASE_ID, ACCOUNT_ID, LOSS_FACTOR_ID, BEGIN_DATE, END_DATE, ENTRY_DATE)
SELECT 1, ACCOUNT_ID, CASE WHEN ACCOUNT_NAME = 'GL_BWI' THEN 105 ELSE 101 END LOSS_FACTOR_ID, LOW_DATE, HIGH_DATE, SYSDATE FROM ACCOUNT WHERE ACCOUNT_MODEL_OPTION = 'Aggregate';
INSERT INTO ACCOUNT_STATUS(ACCOUNT_ID, BEGIN_DATE, END_DATE, ENTRY_DATE, STATUS_NAME)
SELECT ACCOUNT_ID, LOW_DATE, NULL, SYSDATE, 'Active' FROM ACCOUNT WHERE ACCOUNT_MODEL_OPTION = 'Aggregate';
INSERT INTO ACCOUNT_CALENDAR(CASE_ID, ACCOUNT_ID, CALENDAR_ID, CALENDAR_TYPE, BEGIN_DATE, END_DATE, ENTRY_DATE)
SELECT 1 "CASE_ID", A.ACCOUNT_ID, B.CALENDAR_ID, 'Forecast' "CALENDAR_TYPE", LOW_DATE, NULL, SYSDATE
FROM ACCOUNT A
   JOIN CALENDAR B ON B.CALENDAR_NAME = A.ACCOUNT_NAME || '_Settlement' 
WHERE A.ACCOUNT_MODEL_OPTION = 'Aggregate';
INSERT INTO ACCOUNT_CALENDAR(CASE_ID, ACCOUNT_ID, CALENDAR_ID, CALENDAR_TYPE, BEGIN_DATE, END_DATE, ENTRY_DATE)
SELECT 1 "CASE_ID", A.ACCOUNT_ID, B.CALENDAR_ID, 'Backcast' "CALENDAR_TYPE", LOW_DATE, NULL, SYSDATE
FROM ACCOUNT A
   JOIN CALENDAR B ON B.CALENDAR_NAME = A.ACCOUNT_NAME || '_Settlement' 
WHERE A.ACCOUNT_MODEL_OPTION = 'Aggregate';
INSERT INTO ACCOUNT_CALENDAR(CASE_ID, ACCOUNT_ID, CALENDAR_ID, CALENDAR_TYPE, BEGIN_DATE, END_DATE, ENTRY_DATE)
SELECT 1 "CASE_ID", A.ACCOUNT_ID, B.CALENDAR_ID, 'Settlement' "CALENDAR_TYPE", LOW_DATE, NULL, SYSDATE
FROM ACCOUNT A
   JOIN CALENDAR B ON B.CALENDAR_NAME = A.ACCOUNT_NAME || '_Settlement' 
WHERE A.ACCOUNT_MODEL_OPTION = 'Aggregate';
INSERT INTO ACCOUNT_EDC(ACCOUNT_ID, EDC_ID, BEGIN_DATE, EDC_ACCOUNT_NUMBER, EDC_RATE_CLASS, EDC_STRATA, END_DATE, ENTRY_DATE)
SELECT ACCOUNT_ID, 101 "EDC_ID", LOW_DATE, '?', SUBSTR(ACCOUNT_NAME,1,INSTR(ACCOUNT_NAME,'_')-1) "EDC_RATE_CLASS", '?' "EDC_STRATA", NULL, SYSDATE
FROM ACCOUNT WHERE ACCOUNT_MODEL_OPTION = 'Aggregate';
DECLARE
v_SERVICE_LOCATION_ID PLS_INTEGER;
BEGIN
   SELECT MAX(SERVICE_LOCATION_ID) INTO v_SERVICE_LOCATION_ID FROM SERVICE_LOCATION WHERE SERVICE_LOCATION_NAME = 'BWI';
   INSERT INTO ACCOUNT_SERVICE_LOCATION(ACCOUNT_ID, SERVICE_LOCATION_ID, BEGIN_DATE, END_DATE, EDC_IDENTIFIER, ESP_IDENTIFIER, ENTRY_DATE)
   SELECT ACCOUNT_ID, v_SERVICE_LOCATION_ID "SERVICE_LOCATION_ID", LOW_DATE, NULL, '?', '?', SYSDATE
   FROM ACCOUNT WHERE ACCOUNT_MODEL_OPTION = 'Aggregate';
   COMMIT;
END;
/

ALTER TRIGGER ZREALM_ACCOUNT ENABLE;
