INSERT INTO TEMPLATE(TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_ALIAS, TEMPLATE_DESC, IS_DAY_TYPE, IS_DST_OBSERVANT, ENTRY_DATE)
VALUES(101, 'Weekday/Sat/Sun+Hol', 'Weekday/Sat/Sun+Hol', 'Weekday/Sat/Sun+Hol', 0, 1, CURRENT_DATE);
INSERT INTO PERIOD(PERIOD_ID, PERIOD_NAME, PERIOD_ALIAS, PERIOD_DESC, PERIOD_COLOR, ENTRY_DATE)
VALUES(101, 'Saturday Period', 'Saturday Period', 'Saturday Period', -13369345, CURRENT_DATE);
INSERT INTO PERIOD(PERIOD_ID, PERIOD_NAME, PERIOD_ALIAS, PERIOD_DESC, PERIOD_COLOR, ENTRY_DATE)
VALUES(102, 'Sunday Period', 'Sunday Period', 'Sunday Period', -103, CURRENT_DATE);
INSERT INTO PERIOD(PERIOD_ID, PERIOD_NAME, PERIOD_ALIAS, PERIOD_DESC, PERIOD_COLOR, ENTRY_DATE)
VALUES(103, 'Weekday Period', 'Weekday Period', 'Weekday Period', -10066432, CURRENT_DATE);
INSERT INTO SEASON_TEMPLATE(TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES(101, 1, 'Sat', '00:00:01', '24:00:00', 101, CURRENT_DATE);
INSERT INTO SEASON_TEMPLATE(TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES(101, 1, 'Sun', '00:00:01', '24:00:00', 102, CURRENT_DATE);
INSERT INTO SEASON_TEMPLATE(TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES(101, 1, 'Hol', '00:00:01', '24:00:00', 102, CURRENT_DATE);
INSERT INTO SEASON_TEMPLATE(TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES(101, 1, 'Mon', '00:00:01', '24:00:00', 103, CURRENT_DATE);
INSERT INTO SEASON_TEMPLATE(TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES(101, 1, 'Tue', '00:00:01', '24:00:00', 103, CURRENT_DATE);
INSERT INTO SEASON_TEMPLATE(TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES(101, 1, 'Wed', '00:00:01', '24:00:00', 103, CURRENT_DATE);
INSERT INTO SEASON_TEMPLATE(TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES(101, 1, 'Thu', '00:00:01', '24:00:00', 103, CURRENT_DATE);
INSERT INTO SEASON_TEMPLATE(TEMPLATE_ID, SEASON_ID, DAY_NAME, BEGIN_INTERVAL, END_INTERVAL, PERIOD_ID, ENTRY_DATE)
VALUES(101, 1, 'Fri', '00:00:01', '24:00:00', 103, CURRENT_DATE);
COMMIT;
