INSERT INTO ENTITY_DOMAIN(ENTITY_DOMAIN_ID, ENTITY_DOMAIN_NAME, ENTITY_DOMAIN_ALIAS, ENTITY_DOMAIN_DESC, ENTITY_DOMAIN_TABLE, ENTITY_DOMAIN_TABLE_ALIAS, INCLUDE_CONTACT_ADDRESS, INCLUDE_ENTITY_ATTRIBUTE, ENTRY_DATE)
VALUES(101, 'Tariff Code', 'TARIFF_CODE', 'BGE TARIFF CODE TABL,  do not delete!', 'RTO_BGE_TARIFF_CODES', 'RTO_BGE_TARIFF_CODES', 0, 0, SYSDATE);
INSERT INTO ENTITY_DOMAIN(ENTITY_DOMAIN_ID, ENTITY_DOMAIN_NAME, ENTITY_DOMAIN_ALIAS, ENTITY_DOMAIN_DESC, ENTITY_DOMAIN_TABLE, ENTITY_DOMAIN_TABLE_ALIAS, INCLUDE_CONTACT_ADDRESS, INCLUDE_ENTITY_ATTRIBUTE, ENTRY_DATE)
VALUES(102, 'Alm Input', 'ALM_CODE', 'BGE ALM CODE TABL,  do not delete!', 'BGE_ALM_INPUT', 'BGE_ALM_INPUT', 0, 0, SYSDATE);
INSERT INTO ENTITY_DOMAIN(ENTITY_DOMAIN_ID, ENTITY_DOMAIN_NAME, ENTITY_DOMAIN_ALIAS, ENTITY_DOMAIN_DESC, ENTITY_DOMAIN_TABLE, ENTITY_DOMAIN_TABLE_ALIAS, INCLUDE_CONTACT_ADDRESS, INCLUDE_ENTITY_ATTRIBUTE, ENTRY_DATE)
VALUES(103, 'Rider Input', 'RIDER_CODE', 'BGE RIDER CODE TABL,  do not delete!', 'BGE_RIDER_INPUT', 'BGE_RIDER_INPUT', 0, 0, SYSDATE);
INSERT INTO ENTITY_DOMAIN(ENTITY_DOMAIN_ID, ENTITY_DOMAIN_NAME, ENTITY_DOMAIN_ALIAS, ENTITY_DOMAIN_DESC, ENTITY_DOMAIN_TABLE, ENTITY_DOMAIN_TABLE_ALIAS, INCLUDE_CONTACT_ADDRESS, INCLUDE_ENTITY_ATTRIBUTE, ENTRY_DATE)
VALUES(104, 'Account_Ignored', 'ACCOUNT_IGNORED', 'BGE_IGNORE_ACCOUNT TABL,  do not delete!', 'BGE_IGNORE_ACCOUNT', 'BGE_IGNORE_ACCOUNT', 0, 0, SYSDATE);
INSERT INTO ENTITY_DOMAIN(ENTITY_DOMAIN_ID, ENTITY_DOMAIN_NAME, ENTITY_DOMAIN_ALIAS, ENTITY_DOMAIN_DESC, ENTITY_DOMAIN_TABLE, ENTITY_DOMAIN_TABLE_ALIAS, INCLUDE_CONTACT_ADDRESS, INCLUDE_ENTITY_ATTRIBUTE, ENTRY_DATE)
VALUES(105, 'PLC_ICAP_Value', 'CDI_PLC_ICAP_TX_TRG', 'CDI_PLC_ICAP_TX  TABL,  do not delete!', 'CDI_PLC_ICAP_TX', 'CDI_PLC_ICAP_TX', 0, 0, SYSDATE);
INSERT INTO ENTITY_DOMAIN(ENTITY_DOMAIN_ID, ENTITY_DOMAIN_NAME, ENTITY_DOMAIN_ALIAS, ENTITY_DOMAIN_DESC, ENTITY_DOMAIN_TABLE, ENTITY_DOMAIN_TABLE_ALIAS, INCLUDE_CONTACT_ADDRESS, INCLUDE_ENTITY_ATTRIBUTE, ENTRY_DATE)
VALUES(106, 'Monthly_Usage', 'MONTHLY_USAGE', 'BGE_RTO_MONTHLY_USAGE  TABL,  do not delete!', 'BGE_RTO_MONTHLY_USAGE', 'BGE_RTO_MONTHLY_USAGE', 0, 0, SYSDATE);
INSERT INTO ENTITY_DOMAIN(ENTITY_DOMAIN_ID, ENTITY_DOMAIN_NAME, ENTITY_DOMAIN_ALIAS, ENTITY_DOMAIN_DESC, ENTITY_DOMAIN_TABLE, ENTITY_DOMAIN_TABLE_ALIAS, INCLUDE_CONTACT_ADDRESS, INCLUDE_ENTITY_ATTRIBUTE, ENTRY_DATE)
VALUES(107, 'Create_PJM_SHORT_NAME_EMAIL', 'Create_PJM_SHORT_NAME_EMAIL', 'CDI_PJM_SHORT_NAME  TABL,  do not delete!', 'CDI_PJM_SHORT_NAME', 'CDI_PJM_SHORT_NAME', 0, 0, SYSDATE);
INSERT INTO ENTITY_DOMAIN(ENTITY_DOMAIN_ID, ENTITY_DOMAIN_NAME, ENTITY_DOMAIN_ALIAS, ENTITY_DOMAIN_DESC, ENTITY_DOMAIN_TABLE, ENTITY_DOMAIN_TABLE_ALIAS, INCLUDE_CONTACT_ADDRESS, INCLUDE_ENTITY_ATTRIBUTE, ENTRY_DATE)
VALUES(108, 'Polr_Type', 'Polr_Type', 'BGE_POLR_TYPES  TABL,  do not delete!', 'BGE_POLR_TYPES', 'BGE_POLR_TYPES', 0, 0, SYSDATE);
INSERT INTO ENTITY_DOMAIN(ENTITY_DOMAIN_ID, ENTITY_DOMAIN_NAME, ENTITY_DOMAIN_ALIAS, ENTITY_DOMAIN_DESC, ENTITY_DOMAIN_TABLE, ENTITY_DOMAIN_TABLE_ALIAS, INCLUDE_CONTACT_ADDRESS, INCLUDE_ENTITY_ATTRIBUTE, ENTRY_DATE)
VALUES(109, 'Polr_Dormant', 'POLR_DORMANT', 'CDI_PLC_DORMANT_ALLOC  TABL,  do not delete!', 'CDI_PLC_DORMANT_ALLOC', 'CDI_PLC_DORMANT_ALLOC', 0, 0, SYSDATE);
INSERT INTO ENTITY_DOMAIN(ENTITY_DOMAIN_ID, ENTITY_DOMAIN_NAME, ENTITY_DOMAIN_ALIAS, ENTITY_DOMAIN_DESC, ENTITY_DOMAIN_TABLE, ENTITY_DOMAIN_TABLE_ALIAS, INCLUDE_CONTACT_ADDRESS, INCLUDE_ENTITY_ATTRIBUTE, ENTRY_DATE)
VALUES(110, 'Time_Mapping', 'TIME_MAPPING', 'CDI_BGE_TO_RTO_TEMPLATES  TABL,  do not delete!', 'CDI_BGE_TO_RTO_TEMPLATES', 'CDI_BGE_TO_RTO_TEMPLATES', 0, 0, SYSDATE);
INSERT INTO ENTITY_DOMAIN(ENTITY_DOMAIN_ID, ENTITY_DOMAIN_NAME, ENTITY_DOMAIN_ALIAS, ENTITY_DOMAIN_DESC, ENTITY_DOMAIN_TABLE, ENTITY_DOMAIN_TABLE_ALIAS, INCLUDE_CONTACT_ADDRESS, INCLUDE_ENTITY_ATTRIBUTE, ENTRY_DATE)
VALUES(111, 'Dormant_PLC', 'DORMANT_PLC', 'CDI_PLC_DORMANT_ALLOCATION TABL, do not delete!', 'CDI_PLC_DORMANT_ALLOCATION', 'CDI_PLC_DORMANT_ALLOCATION', 0, 0, SYSDATE);
COMMIT;
