CREATE OR REPLACE TRIGGER ACCOUNT_SERVICE_LOC_DELETE
	AFTER DELETE ON ACCOUNT_SERVICE_LOCATION
	FOR EACH ROW

BEGIN

	IF NOT GA.ENABLE_SERVICE_RETENTION THEN
		DELETE ACCOUNT_SERVICE
		WHERE SERVICE_LOCATION_ID = :old.SERVICE_LOCATION_ID;
	END IF;
	
END ACCOUNT_SERVICE_LOC_DELETE;
/ 
