CREATE OR REPLACE TRIGGER BILLING_STATEMENT_UPDATE 
	BEFORE INSERT OR UPDATE ON BILLING_STATEMENT 
	FOR EACH ROW 
BEGIN 
	IF NOT GA.VERSION_STATEMENT THEN
		:new.AS_OF_DATE := LOW_DATE; 
	END IF; 
END BILLING_STATEMENT_UPDATE;
/
