CREATE OR REPLACE TRIGGER CALENDAR_ADJUSTMENT_POST
	AFTER INSERT OR UPDATE ON CALENDAR_ADJUSTMENT
BEGIN

	IF GA.ENABLE_CALENDAR_TRIGGERS THEN	
		UPDATE CALENDAR X
		SET X.HAS_ADJUSTMENTS =
			(SELECT DECODE(SUM(DECODE(NVL(B.CALENDAR_ID,0),0,0,1)),0,0,1)
			FROM CALENDAR A, CALENDAR_ADJUSTMENT B
			WHERE A.CALENDAR_ID = X.CALENDAR_ID
				AND B.CALENDAR_ID(+) = A.CALENDAR_ID
			GROUP BY B.CALENDAR_ID);
	END IF;

END CALENDAR_ADJUSTMENT_POST;

/ 
