CREATE OR REPLACE TRIGGER EMAIL_LOG_DELETE
	AFTER DELETE ON EMAIL_LOG
	FOR EACH ROW
BEGIN
	DELETE EMAIL_LOG_RECIPIENT WHERE EMAIL_ID = :old.EMAIL_ID;
	DELETE EMAIL_LOG_ATTACHMENT WHERE EMAIL_ID = :old.EMAIL_ID;
END EMAIL_LOG_DELETE;
/
