CREATE OR REPLACE TRIGGER ENTITY_ATTRIBUTE_DELETE
	AFTER DELETE ON ENTITY_ATTRIBUTE
	FOR EACH ROW
BEGIN
	DELETE TEMPORAL_ENTITY_ATTRIBUTE WHERE ATTRIBUTE_ID = :old.ATTRIBUTE_ID;
	DELETE COMPONENT_ENTITY_ATTRIBUTE WHERE ENTITY_ATTRIBUTE_ID = :old.ATTRIBUTE_ID;
	DELETE LOAD_SEGMENTATION_DEF_DETAILS WHERE ATTRIBUTE_ID = :old.ATTRIBUTE_ID;
END ENTITY_ATTRIBUTE_DELETE;
/
