CREATE OR REPLACE TRIGGER LOAD_PROFILE_STATISTICS_UPDATE 
	BEFORE INSERT OR UPDATE ON LOAD_PROFILE_STATISTICS
	FOR EACH ROW 
BEGIN 
	IF NOT GA.VERSION_PROFILE THEN
		:new.AS_OF_DATE := LOW_DATE; 
	END IF; 
END LOAD_PROFILE_STATISTICS_UPDATE;
/ 
