CREATE OR REPLACE TRIGGER PROSPECT_UPDATE
	AFTER UPDATE ON PROSPECT
	FOR EACH ROW
BEGIN
	DELETE PROSPECT_CONSUMPTION
	WHERE PROSPECT_ID = :old.PROSPECT_ID
	  AND :new.PROSPECT_ID <> :old.PROSPECT_ID;
	DELETE PROSPECT_EVALUATION
	WHERE PROSPECT_ID = :old.PROSPECT_ID
	  AND :new.PROSPECT_ID <> :old.PROSPECT_ID;
END PROSPECT_UPDATE;
/
