CREATE OR REPLACE TRIGGER SERVICE_LOCATION_DELETE
	AFTER DELETE ON SERVICE_LOCATION
	FOR EACH ROW
BEGIN
	DELETE ACCOUNT_SERVICE_LOCATION WHERE SERVICE_LOCATION_ID = :old.SERVICE_LOCATION_ID;
	DELETE SERVICE_LOCATION_METER WHERE SERVICE_LOCATION_ID = :old.SERVICE_LOCATION_ID;
	DELETE ACCOUNT_SERVICE WHERE SERVICE_LOCATION_ID = :old.SERVICE_LOCATION_ID;
	DELETE SERVICE_LOCATION_MRSP WHERE SERVICE_LOCATION_ID = :old.SERVICE_LOCATION_ID;
END SERVICE_LOCATION_DELETE;
/
