CREATE OR REPLACE TRIGGER SERVICE_STATE_DELETE
	AFTER DELETE ON SERVICE_STATE
	FOR EACH ROW
DECLARE
v_BEGIN_DATE DATE;
v_END_DATE DATE;
v_MODEL_ID NUMBER(9);
BEGIN
	--THIS MODEL_ID USED TO COME FROM THE SERVICE TABLE, BUT THAT CAUSED A MUTATING TRIGGER.
	UT.CUT_DATE_RANGE(GA.DEFAULT_MODEL, :old.SERVICE_DATE, LOCAL_TIME_ZONE, v_BEGIN_DATE, v_END_DATE);

    --Do not always delete the external forecast unless project wanted.
	IF GA.ENABLE_EXTERNAL_CAST_DELETE THEN   
		DELETE SERVICE_LOAD
		WHERE SERVICE_ID = :old.SERVICE_ID
			AND SERVICE_CODE = :old.SERVICE_CODE
			AND LOAD_DATE BETWEEN v_BEGIN_DATE AND v_END_DATE;
	ELSE -- Do not delete the external forecast
		DELETE SERVICE_LOAD
		WHERE SERVICE_ID = :old.SERVICE_ID
			AND SERVICE_CODE = :old.SERVICE_CODE
			AND LOAD_DATE BETWEEN v_BEGIN_DATE AND v_END_DATE
			AND LOAD_CODE <> GA.EXTERNAL;
	END IF;

END SERVICE_STATE_DELETE;
/
