CREATE OR REPLACE TRIGGER SERVICE_OBLIGATION_DELETE
	AFTER DELETE ON SERVICE_OBLIGATION
	FOR EACH ROW
BEGIN
	DELETE SERVICE_OBLIGATION_LOAD WHERE SERVICE_OBLIGATION_ID = :old.SERVICE_OBLIGATION_ID;
END SERVICE_OBLIGATION_DELETE;
/ 
