CREATE OR REPLACE PACKAGE MM_PJM_SETTLEMENT IS
-- $Revision: 1.62 $

  -- Author  : JHUMPHRIES
  -- Created : 9/7/2004 2:15:20 PM
  -- Purpose : Perform import of external settlement details from PJM into RetailOffice

FUNCTION WHAT_VERSION RETURN VARCHAR2;

PROCEDURE MARKET_EXCHANGE
	(
	p_BEGIN_DATE            	IN DATE,
	p_END_DATE              	IN DATE,
	p_EXCHANGE_TYPE  			IN VARCHAR2,
	p_ENTITY_LIST           	IN VARCHAR2,
	p_ENTITY_LIST_DELIMITER 	IN CHAR,
	p_LOG_ONLY					IN NUMBER :=0,
	p_LOG_TYPE 					IN NUMBER,
	p_TRACE_ON 					IN NUMBER,
	p_STATUS                	OUT NUMBER,
	p_MESSAGE               	OUT VARCHAR2);

FUNCTION GET_PSE
	(
	p_ORG_ID IN VARCHAR2,
	p_ORG_NAME IN VARCHAR2
	) RETURN NUMBER;

PROCEDURE FILL_NON_SHADOWED_TXNS
	(
    p_PSE_ID IN NUMBER,
    p_COMPONENT_ID IN NUMBER,
    p_CHARGE_AMOUNT IN NUMBER,
    p_DATE IN DATE
    );

FUNCTION ID_FOR_SERVICE_ZONE
	(
	p_ZONE_NAME IN VARCHAR2
	) RETURN NUMBER;

g_EXTERNAL_STATE NUMBER(1) := 2;

g_ET_IMP_SETTLEMENT_STMT VARCHAR2(30):= 'IMPORT SETTLEMENT STATEMENT';

END MM_PJM_SETTLEMENT;
/