CREATE OR REPLACE PACKAGE MM_TDIE_INVOICE_UI IS
-- $Revision: 1.23 $

FUNCTION WHAT_VERSION RETURN VARCHAR2;

PROCEDURE TUOS_DET_CODE_MAPPING (p_CURSOR OUT GA.REFCURSOR);

PROCEDURE RATE_NAME_LIST (p_CURSOR OUT GA.REFCURSOR);

PROCEDURE QUANTITY_NAME_LIST (p_CURSOR OUT GA.REFCURSOR);

PROCEDURE PUT_TUOS_DET_CODE_MAPPING
	(
	p_CHARGE_NAME    IN VARCHAR2,
	p_RATE_NAME  	 IN VARCHAR2,
	p_QUANTITY_NAME  IN VARCHAR2
	);

PROCEDURE TUOS_SUPPLY_UNIT_MAPPING (p_CURSOR OUT GA.REFCURSOR);

PROCEDURE ACCOUNT_CODE_LIST (p_CURSOR OUT GA.REFCURSOR);

PROCEDURE METER_NAME_LIST (p_ACCOUNT_CODE IN VARCHAR2, p_CURSOR OUT GA.REFCURSOR);

PROCEDURE SUPPLY_UNIT_LIST (p_CURSOR OUT GA.REFCURSOR);

PROCEDURE PUT_TUOS_SUPPLY_UNIT_MAPPING
	(
	p_ACCOUNT_CODE     IN VARCHAR2,
	p_OLD_ACCOUNT_CODE IN VARCHAR2,
	p_METER_NAME  	   IN VARCHAR2,
	p_OLD_METER_NAME   IN VARCHAR2,
	p_SUPPLY_UNIT      IN VARCHAR2
	);

PROCEDURE DEL_TUOS_SUPPLY_UNIT_MAPPING
	(
	p_ACCOUNT_CODE     IN VARCHAR2,
	p_METER_NAME  	   IN VARCHAR2
	);

PROCEDURE FINANCIAL_SETTLEMENTS
	(
	p_SENDER_CID    IN VARCHAR2,
	p_RECIPIENT_CID IN VARCHAR2,
	p_BEGIN_DATE    IN DATE,
	p_END_DATE      IN DATE,
	p_CURSOR        OUT GA.REFCURSOR
	);

PROCEDURE RECIPIENT_LIST
	(
	p_SENDER_CID IN VARCHAR2,
	p_CURSOR OUT GA.REFCURSOR
	);

PROCEDURE STATEMENT_TYPE_LIST(p_CURSOR OUT GA.REFCURSOR);

PROCEDURE ACCOUNT_MPRN_LIST
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_SEARCH_BY IN NUMBER, -- 0 By MPRN or 1 By Account
	p_SEARCH_STRING IN VARCHAR2,
	p_INTERVAL_TYPE IN NUMBER, -- 0 Non-Interval or 1 Interval
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE SENDER_LIST
	(
	p_INTERVAL_TYPE IN NUMBER, -- 0-Non-Interval or 1-Interval
	p_CURSOR IN OUT GA.REFCURSOR
	);

FUNCTION GET_INVOICE_TYPE_FROM_SENDER
	(
		p_SENDER_CID IN VARCHAR2
	) RETURN VARCHAR2;

FUNCTION GET_INVOICE_TYPE_FRM_SENDER_ID
	(
		p_SENDER_ID IN VARCHAR2
	) RETURN VARCHAR2;

PROCEDURE ACCOUNT_HISTORY
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_INTERVAL_TYPE IN NUMBER, -- 0-Non-Interval or 1-Interval
	p_ACCOUNT_ID IN NUMBER,
	p_TIME_ZONE IN VARCHAR2,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE ACCOUNT_HISTORY_DETAILS
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_SENDER_CID IN VARCHAR2,
	p_ACCOUNT_ID IN NUMBER,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE UNSETTLED_ACCOUNTS
	(
	p_DAYS_BACK NUMBER,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE UNMETERED_ACCOUNTS
	(
	p_DAYS_BACK NUMBER,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE UNINVOICED_ACCOUNTS
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_INVOICE_TYPE IN VARCHAR2, -- 'TUOS', 'DUOS' or 'UOS'
	p_RETAIL_INVOICE_ID IN NUMBER,
	p_METER_TYPE IN VARCHAR2, -- 'Interval' or 'Period'
	p_CURSOR IN OUT GA.REFCURSOR,
    p_RETAIL_INVOICE_NAME OUT VARCHAR2
	);

PROCEDURE ACCOUNT_VARIANCES
	(
	p_RETAIL_INVOICE_ID NUMBER,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE METERED_USAGE_VARIANCES
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_RETAIL_INVOICE_ID IN NUMBER,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE PSO_CCL_SSS_SENDER_LIST
    (
    p_CURSOR IN OUT GA.REFCURSOR
    );

PROCEDURE PSO_CCL_SSS_RECEPIENT_LIST
    (
    p_SENDER_ID IN NUMBER,
    p_CURSOR IN OUT GA.REFCURSOR
    );

PROCEDURE PSO_CCL_SSS_SENDER_GRID_LIST
    (
    p_SENDER_ID IN NUMBER,
    p_CURSOR IN OUT GA.REFCURSOR
    );

PROCEDURE PSO_CCL_SSS_RCPT_GRID_LIST
    (
    p_RECEPIENT_ID IN NUMBER,
    p_INVOICE_SENDER_ID IN NUMBER,
    p_CURSOR IN OUT GA.REFCURSOR
    );

PROCEDURE PSO_CCL_SSS_INVOICES
	(
	p_SENDER_ID    IN VARCHAR2,
	p_RECIPIENT_ID IN VARCHAR2,
	p_BEGIN_DATE    IN DATE,
	p_END_DATE      IN DATE,
	p_CURSOR        OUT GA.REFCURSOR
	);

PROCEDURE PUT_PSO_CCL_SSS_INVOICE
    (
    p_INVOICE_SENDER_ID IN NUMBER,
    p_INVOICE_RECIPIENT_ID IN NUMBER,
    p_RETAIL_INVOICE_ID IN NUMBER,
    p_INVOICE_NUMBER IN VARCHAR2,
    p_INVOICE_DATE IN DATE,
    p_INVOICE_BEGIN_DATE IN DATE,
    p_INVOICE_END_DATE IN DATE
    );

PROCEDURE REMOVE_PSO_CCL_SSS_INVOICE
    (
    p_RETAIL_INVOICE_ID IN NUMBER
    );

END MM_TDIE_INVOICE_UI;
/