CREATE OR REPLACE PACKAGE MM_TDIE_BACKING_SHEETS_UI IS
-- $Revision: 1.5 $

FUNCTION WHAT_VERSION RETURN VARCHAR2;

PROCEDURE DUOS_RECIPIENT_LIST
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE DUOS_INV_SUMMARY
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_RECIPIENT_CID IN VARCHAR2,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE DUOS_INV_DETAILS
	(
	p_DETAIL_TYPE IN VARCHAR2, -- MPRN Details or Group Summary
	p_INVOICE_NUMBER IN VARCHAR2,
	p_MPRN_SEARCH_STRING IN VARCHAR2, -- Used when DETAIL_TYPE is MPRN Details
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE DUOS_NI_RECIPIENT_LIST
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CURSOR IN OUT GA.REFCURSOR
	);
    
PROCEDURE DUOS_NI_INV_SUMMARY
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_SUPPLIER IN VARCHAR2,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE DUOS_NI_INV_DETAILS
	(
	p_DETAIL_TYPE IN VARCHAR2, -- MPRN Details or Group Summary
	p_INVOICE_NUMBER IN VARCHAR2,
    p_DUOS_GROUP IN VARCHAR2,
	p_MPRN_SEARCH_STRING IN VARCHAR2, -- Used when DETAIL_TYPE is MPRN Details
	p_CURSOR IN OUT GA.REFCURSOR
	);	
	
PROCEDURE TUOS_INV_SUMMARY
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE TUOS_INV_DETAILS
	(
	p_DETAIL_TYPE IN VARCHAR2, -- Account Details or Tariff Summary
	p_INVOICE_NUMBER IN VARCHAR2,
	p_SEARCH_BY IN VARCHAR2,
	p_SEARCH_STRING IN VARCHAR2, -- Used when DETAIL_TYPE is Account Details
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE UOS_RECIPIENT_LIST
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE UOS_INV_SUMMARY
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_RECIPIENT_CID IN VARCHAR2,
	p_CURSOR IN OUT GA.REFCURSOR
	);

PROCEDURE UOS_INV_DETAILS
	(
	p_DETAIL_TYPE IN VARCHAR2, -- MPRN Details or Tariff Summary
	p_INVOICE_NUMBER IN VARCHAR2,
	p_MPRN_SEARCH_STRING IN VARCHAR2, -- Used when DETAIL_TYPE is MPRN Details
	p_CURSOR IN OUT GA.REFCURSOR
	);

END MM_TDIE_BACKING_SHEETS_UI;
/