CREATE OR REPLACE FUNCTION STD_TIME_ZONE
	(
	p_TIME_ZONE IN VARCHAR
	) RETURN VARCHAR IS
--Revision: $Revision: 1.20 $

BEGIN

	IF p_TIME_ZONE = 'GMT' THEN
		RETURN 'GMT';
   ELSIF p_TIME_ZONE = 'CES' OR p_TIME_ZONE = 'CET' THEN
    RETURN 'CET';  
	ELSE
    RETURN UPPER(SUBSTR(p_TIME_ZONE,1,1)) || 'ST';
	END IF;

END STD_TIME_ZONE;
/
