CREATE OR REPLACE PACKAGE MM_SEM_CFD_DIFF_PMTS IS

  -- Author  : MWEATHERS
  -- Created : 3/3/2008 6:18:38 AM
  -- Purpose : CFD Difference Payments Package
  -- $Revision: 1.3 $

FUNCTION WHAT_VERSION RETURN VARCHAR;

FUNCTION GET_FILTERED_TRANSACTION_IDS
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CONTRACT_IDS IN VARCHAR2,
	p_CONTRACT_TYPE_FILTER IN VARCHAR2,
	p_AGREEMENT_TYPE_FILTER IN VARCHAR2,
	p_COUNTERPARTY_ID_FILTER IN NUMBER,
	p_CURRENCY_FILTER IN VARCHAR2
	) RETURN NUMBER_COLLECTION;

PROCEDURE GET_MONTHLY_INVOICE_DATA_RPT
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CONTRACT_IDS IN VARCHAR2,
	p_CONTRACT_TYPE_FILTER IN VARCHAR2,
	p_AGREEMENT_TYPE_FILTER IN VARCHAR2,
	p_COUNTERPARTY_ID_FILTER IN NUMBER,
	p_CURRENCY_FILTER IN VARCHAR2,
   	p_STATEMENT_TYPE IN NUMBER,
	p_STATEMENT_TYPE_ID_2 IN NUMBER,
	p_SHOW_STATEMENT_TYPE_ID_2 IN NUMBER,
	p_STATEMENT_TYPE_NAME_1 OUT VARCHAR2,
	p_STATEMENT_TYPE_NAME_2 OUT VARCHAR2,
	p_CURSOR IN OUT SYS_REFCURSOR
	);
	
PROCEDURE GET_DIFF_PAYMENTS_SUMMARY_RPT
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CONTRACT_IDS IN VARCHAR2,
	p_CONTRACT_TYPE_FILTER IN VARCHAR2,
	p_AGREEMENT_TYPE_FILTER IN VARCHAR2,
	p_COUNTERPARTY_ID_FILTER IN NUMBER,
	p_CURRENCY_FILTER IN VARCHAR2,
   	p_STATEMENT_TYPE IN NUMBER,
	p_STATEMENT_TYPE_ID_2 IN NUMBER,
	p_SHOW_STATEMENT_TYPE_ID_2 IN NUMBER,
	p_VAT_STYLE_FILTER IN VARCHAR2,
	p_STATEMENT_TYPE_NAME_1 OUT VARCHAR2,
	p_STATEMENT_TYPE_NAME_2 OUT VARCHAR2,
	p_CURSOR IN OUT SYS_REFCURSOR
	);

PROCEDURE GET_DIFF_PAYMENTS_DETAIL_RPT
	(
	p_STATEMENT_MONTH_STR IN VARCHAR2,
	p_TRANSACTION_ID IN NUMBER,
	p_STATEMENT_TYPE IN NUMBER,
	p_STATEMENT_TYPE_ID_2 IN NUMBER,
	p_SHOW_STATEMENT_TYPE_ID_2 IN NUMBER,
	p_VAT_STYLE_FILTER IN VARCHAR2,
	p_STATEMENT_TYPE_NAME_1 OUT VARCHAR2,
	p_STATEMENT_TYPE_NAME_2 OUT VARCHAR2,
	p_CURSOR IN OUT SYS_REFCURSOR
	);

PROCEDURE GET_DIFF_PAYMENTS_MATRIX_RPT
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_CONTRACT_IDS IN VARCHAR2,
	p_CONTRACT_TYPE_FILTER IN VARCHAR2,
	p_AGREEMENT_TYPE_FILTER IN VARCHAR2,
	p_COUNTERPARTY_ID_FILTER IN NUMBER,
	p_CURRENCY_FILTER IN VARCHAR2,
   	p_STATEMENT_TYPE IN NUMBER,
	p_STATEMENT_TYPE_ID_2 IN NUMBER,
	p_SHOW_STATEMENT_TYPE_ID_2 IN NUMBER,
	p_MATRIX_TYPE_FILTER IN VARCHAR2,
	p_STATEMENT_TYPE_NAME_1 OUT VARCHAR2,
	p_STATEMENT_TYPE_NAME_2 OUT VARCHAR2,
	p_CURSOR IN OUT SYS_REFCURSOR
	);

PROCEDURE CACHE_DIFF_PAYMENTS_DETAILS
	(
	p_BEGIN_DATE IN DATE,
	p_END_DATE IN DATE,
	p_TRANSACTION_IDS IN NUMBER_COLLECTION,
	p_STATEMENT_TYPE_ID IN NUMBER,
	p_STATEMENT_TYPE_ID_2 IN NUMBER,
	p_VAT_STYLE_FILTER IN VARCHAR2
	);

END MM_SEM_CFD_DIFF_PMTS;
/