CREATE OR REPLACE PACKAGE MM_SEM_SRA_OFFER IS
-- $Revision: 1.14 $

  -- Author  : JHUMPHRIES
  -- Created : 4/3/2007 12:52:18 PM
  -- Purpose : Build XML pieces of submission, query, and cancellation of Generation offers

FUNCTION WHAT_VERSION RETURN VARCHAR2;

FUNCTION CREATE_SUBMISSION_XML
       (
       p_DATE IN DATE,
       p_TRANSACTION_ID IN NUMBER,
       p_LOGGER IN OUT NOCOPY MM_LOGGER_ADAPTER
       ) RETURN XMLTYPE;

FUNCTION CREATE_QUERY_XML
	(
	p_DATE IN DATE,
	p_TRANSACTION_ID IN NUMBER,
	p_LOGGER IN OUT NOCOPY MM_LOGGER_ADAPTER
	) RETURN XMLTYPE;
  
FUNCTION CREATE_CANCELLATION_XML
(
    p_DATE           IN DATE,
    p_TRANSACTION_ID IN NUMBER,
    p_LOGGER         IN OUT NOCOPY MM_LOGGER_ADAPTER
) RETURN XMLTYPE;  

FUNCTION GET_TRANSACTION_IDs
	(
	p_DATE IN DATE,
	p_ACCOUNT_NAME IN VARCHAR2,
	p_GATE_WINDOW IN VARCHAR2 DEFAULT NULL,
	p_RESPONSE IN XMLTYPE
	) RETURN NUMBER_COLLECTION;

PROCEDURE RESET_FOR_PARSE;

FUNCTION PARSE_QUERY_XML
	(
	p_TRANSACTION_IDs IN NUMBER_COLLECTION,
	p_DATE IN DATE,
	p_RESPONSE IN XMLTYPE,
	p_LOGGER IN OUT NOCOPY MM_LOGGER_ADAPTER
	) RETURN VARCHAR2;

FUNCTION PARSE_SUBMISSION_RESPONSE_XML
	(
	p_TRANSACTION_IDs IN NUMBER_COLLECTION,
	p_DATE IN DATE,
	p_RESPONSE IN XMLTYPE,
	p_LOGGER IN OUT NOCOPY MM_LOGGER_ADAPTER
	) RETURN VARCHAR2;

FUNCTION VALUE_MATCHES
	(
	p_TRAIT_VAL1 IN VARCHAR2,
	p_TRAIT_VAL2 IN VARCHAR2,
	p_DAY IN DATE,
	p_METHOD IN CHAR := 's'
	) RETURN NUMBER;

FUNCTION GET_TRANSACTION_ID
	(
	p_DATE IN DATE,
	p_START_HR IN NUMBER,
	p_START_INT IN NUMBER,
	p_PURCHASER_NAME IN VARCHAR2,
	p_COMMODITY_ID IN NUMBER,
	p_AGREEMENT_NAME IN VARCHAR2,
	p_ACCOUNT_NAME IN VARCHAR2,
	p_VALUE IN NUMBER
	) RETURN NUMBER;

PROCEDURE IMPORT_SRA
	(
	p_TRANSACTION_ID IN NUMBER,
	p_TRADING_DATE IN DATE,
	p_START_HOUR IN NUMBER,
	p_START_INT IN NUMBER,
	p_EXT_ID IN VARCHAR2,
	p_SRA_AMOUNT IN NUMBER,
	p_VALIDITY_INDEX IN NUMBER,
	p_VALIDITY_STATUS IN NUMBER,
	p_LOGGER IN OUT NOCOPY MM_LOGGER_ADAPTER
	);

END MM_SEM_SRA_OFFER;
/
