DECLARE

PROCEDURE PUT_STATEMENT_TYPE(
		p_STATEMENT_TYPE_NAME IN VARCHAR2,
        p_STATEMENT_TYPE_ALIAS IN VARCHAR2,
        p_STATEMENT_DESCRIPTION IN VARCHAR2,
        p_STATEMENT_TYPE_ORDER IN NUMBER,
		p_STATEMENT_TYPE_ID IN NUMBER := 0
		) IS
	v_STATEMENT_TYPE_ID NUMBER;
    v_OID NUMBER;
	BEGIN
		BEGIN

			SELECT STATEMENT_TYPE_ID INTO v_STATEMENT_TYPE_ID FROM STATEMENT_TYPE
			WHERE UPPER(STATEMENT_TYPE_ALIAS) = UPPER(TRIM(p_STATEMENT_DESCRIPTION))
            OR UPPER(STATEMENT_TYPE_ALIAS) = UPPER(TRIM(p_STATEMENT_TYPE_NAME));
			
			-- statement type exists; update
			UPDATE STATEMENT_TYPE SET STATEMENT_TYPE_NAME=p_STATEMENT_TYPE_NAME, STATEMENT_TYPE_ALIAS=p_STATEMENT_TYPE_ALIAS,
						STATEMENT_TYPE_DESC=p_STATEMENT_DESCRIPTION
                        WHERE STATEMENT_TYPE_ID=v_STATEMENT_TYPE_ID;
		EXCEPTION
			WHEN OTHERS THEN
				-- new statement type; create
				v_STATEMENT_TYPE_ID := p_STATEMENT_TYPE_ID;
				IO.PUT_STATEMENT_TYPE(v_STATEMENT_TYPE_ID, p_STATEMENT_TYPE_NAME, p_STATEMENT_TYPE_ALIAS, p_STATEMENT_DESCRIPTION, v_STATEMENT_TYPE_ID, p_STATEMENT_TYPE_ORDER);
		END;
        
        -- save external identifier
        IF p_STATEMENT_TYPE_NAME = 'Ex-Ante' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_MKT_SCHED_EA, MM_SEM_UTIL.g_STATEMENT_TYPE_MKT_SCHED);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_MKT_SCHED_EA_ABR, MM_SEM_UTIL.g_STATEMENT_TYPE_GATE_WINDOW);            
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_MKT_SCHED_EA_ABR, MM_SEM_UTIL.g_STATEMENT_TYPE_RUN_TYPE);
                
        ELSIF p_STATEMENT_TYPE_NAME ='Indicative Actual' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_MKT_SCHED_INDIC_A, MM_SEM_UTIL.g_STATEMENT_TYPE_MKT_SCHED);
                            
        ELSIF p_STATEMENT_TYPE_NAME = 'Revised' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_CAP_HOLD_ACT_HOLDINGS, MM_SEM_UTIL.g_STATEMENT_TYPE_CAP_HOLD);
                
        ELSIF p_STATEMENT_TYPE_NAME = 'Indicative' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_MKT_SCHED_INDIC_EP, MM_SEM_UTIL.g_STATEMENT_TYPE_MKT_SCHED);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_CAP_HOLD_ACT_HOLDINGS, MM_SEM_UTIL.g_STATEMENT_TYPE_CAP_HOLD);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_SETTLEMENT_P, MM_SEM_UTIL.g_STATEMENT_TYPE_SETTLEMENT);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_MKT_SCHED_IND_ABR, MM_SEM_UTIL.g_STATEMENT_TYPE_RUN_TYPE);
                
        ELSIF p_STATEMENT_TYPE_NAME = 'Initial' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_MKT_SCHED_INIT_EP, MM_SEM_UTIL.g_STATEMENT_TYPE_MKT_SCHED);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_CAP_HOLD_ACT_HOLDINGS, MM_SEM_UTIL.g_STATEMENT_TYPE_CAP_HOLD);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_SETTLEMENT_F, MM_SEM_UTIL.g_STATEMENT_TYPE_SETTLEMENT);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_MKT_SCHED_INI_ABR, MM_SEM_UTIL.g_STATEMENT_TYPE_RUN_TYPE);
                
        ELSIF p_STATEMENT_TYPE_NAME = 'Revision #1' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_MKT_SCHED_REV_1, MM_SEM_UTIL.g_STATEMENT_TYPE_MKT_SCHED);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_CAP_HOLD_ACT_HOLDINGS, MM_SEM_UTIL.g_STATEMENT_TYPE_CAP_HOLD);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_SETTLEMENT_F1, MM_SEM_UTIL.g_STATEMENT_TYPE_SETTLEMENT);
                
        ELSIF p_STATEMENT_TYPE_NAME = 'Revision #2' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_MKT_SCHED_REV_2, MM_SEM_UTIL.g_STATEMENT_TYPE_MKT_SCHED);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_CAP_HOLD_ACT_HOLDINGS, MM_SEM_UTIL.g_STATEMENT_TYPE_CAP_HOLD);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_SETTLEMENT_F2, MM_SEM_UTIL.g_STATEMENT_TYPE_SETTLEMENT);

        ELSIF p_STATEMENT_TYPE_NAME = 'Within-day Actual' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_MKT_SCHED_WN_DAY_ACT, MM_SEM_UTIL.g_STATEMENT_TYPE_MKT_SCHED);
	
        ELSIF p_STATEMENT_TYPE_NAME = 'Ex-Ante Nom.' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_USER_NOMS_EA, MM_SEM_UTIL.g_STATEMENT_TYPE_USER_NOMS);
		
		ELSIF p_STATEMENT_TYPE_NAME = 'Ex-Ante Nom. EA2' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_USER_NOMS_EA2, MM_SEM_UTIL.g_STATEMENT_TYPE_USER_NOMS);
				
		ELSIF p_STATEMENT_TYPE_NAME = 'Ex-Ante Nom. WD1' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_USER_NOMS_WD1, MM_SEM_UTIL.g_STATEMENT_TYPE_USER_NOMS);
                
        ELSIF p_STATEMENT_TYPE_NAME = 'Modified Nom.' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_USER_NOMS_MOD, MM_SEM_UTIL.g_STATEMENT_TYPE_USER_NOMS);

		ELSIF p_STATEMENT_TYPE_NAME = 'Modified Nom. EA2' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_USER_NOMS_MOD_EA2, MM_SEM_UTIL.g_STATEMENT_TYPE_USER_NOMS);
		
		ELSIF p_STATEMENT_TYPE_NAME = 'Modified Nom. WD1' THEN
				EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_USER_NOMS_MOD_WD1, MM_SEM_UTIL.g_STATEMENT_TYPE_USER_NOMS);
		        
        ELSIF p_STATEMENT_TYPE_NAME = 'Revised Nom.' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_USER_NOMS_REV_MOD, MM_SEM_UTIL.g_STATEMENT_TYPE_USER_NOMS);
				
		ELSIF p_STATEMENT_TYPE_NAME = 'Revised Nom. EA2' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_USER_NOMS_REV_MOD_EA2, MM_SEM_UTIL.g_STATEMENT_TYPE_USER_NOMS);
		
		ELSIF p_STATEMENT_TYPE_NAME = 'Revised Nom. WD1' THEN
				EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_USER_NOMS_REV_MOD_WD1, MM_SEM_UTIL.g_STATEMENT_TYPE_USER_NOMS);               
      
        ELSIF p_STATEMENT_TYPE_NAME = 'Indicative Nom.' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_USER_NOMS_INDIC_EP, MM_SEM_UTIL.g_STATEMENT_TYPE_USER_NOMS);
               
        ELSIF p_STATEMENT_TYPE_NAME = 'Initial Nom.' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, MM_SEM_UTIL.g_EXTID_USER_NOMS_INIT_EP, MM_SEM_UTIL.g_STATEMENT_TYPE_USER_NOMS);
    
        ELSIF p_STATEMENT_TYPE_NAME = 'EA2' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, p_STATEMENT_TYPE_NAME, MM_SEM_UTIL.g_STATEMENT_TYPE_MKT_SCHED);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, p_STATEMENT_TYPE_NAME, MM_SEM_UTIL.g_STATEMENT_TYPE_RUN_TYPE);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, p_STATEMENT_TYPE_NAME, MM_SEM_UTIL.g_STATEMENT_TYPE_GATE_WINDOW);
        
        ELSIF p_STATEMENT_TYPE_NAME = 'WD1' THEN
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, p_STATEMENT_TYPE_NAME, MM_SEM_UTIL.g_STATEMENT_TYPE_MKT_SCHED);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, p_STATEMENT_TYPE_NAME, MM_SEM_UTIL.g_STATEMENT_TYPE_RUN_TYPE);
                EI.PUT_EXTERNAL_SYSTEM_IDENTIFIER(EC.ES_SEM, EC.ED_STATEMENT_TYPE, v_STATEMENT_TYPE_ID, p_STATEMENT_TYPE_NAME, MM_SEM_UTIL.g_STATEMENT_TYPE_GATE_WINDOW); 
    END IF;
        
	END PUT_STATEMENT_TYPE;

BEGIN
	PUT_STATEMENT_TYPE('Indicative Actual','Indicative Actual','Indicative Actual',2);
	PUT_STATEMENT_TYPE('Revised','Revised','Revised',3);
	PUT_STATEMENT_TYPE('Within-day Actual','Within-day Actual','Within-day Actual', 4);
    
	-- note the first 3 have specified IDs to overwrite Forecast, Prelim, and Actual 
	PUT_STATEMENT_TYPE('Ex-Ante','Ex-Ante','Ex-Ante',10, 1);
    PUT_STATEMENT_TYPE('Indicative','Indicative','Indicative',20, 2);
    PUT_STATEMENT_TYPE('Initial','Initial','Initial',30, 3);
    PUT_STATEMENT_TYPE('Revision #1','Revision #1','Revision #1',31);
    PUT_STATEMENT_TYPE('Revision #2','Revision #2','Revision #2',32);
    
    --new statement types for user nomination reports
    PUT_STATEMENT_TYPE('Ex-Ante Nom.','Ex-Ante Nom.','Ex-Ante Nom.',300);
    PUT_STATEMENT_TYPE('Modified Nom.','Modified Nom.','Modified Nom.',301);
	PUT_STATEMENT_TYPE('Revised Nom.','Revised Nom.','Revised Nom.',302);
    PUT_STATEMENT_TYPE('Indicative Nom.','Indicative Nom.','Indicative Nom.',303);
    PUT_STATEMENT_TYPE('Initial Nom.','Initial Nom.','Initial Nom.',304);
	PUT_STATEMENT_TYPE('Ex-Ante Nom. EA2','Ex-Ante Nom. EA2','Ex-Ante Nom. EA2',305);
	PUT_STATEMENT_TYPE('Ex-Ante Nom. WD1','Ex-Ante Nom. WD1','Ex-Ante Nom. WD1',306);
    
    --new statement types for IDT Changes to Market Schedule Detail reports
    PUT_STATEMENT_TYPE('EA2','EA2','Ex-Ante 2 Trading Window',11);
    PUT_STATEMENT_TYPE('WD1','WD1','Within-day 1 Trading Window',12);
	PUT_STATEMENT_TYPE('Modified Nom. EA2','Modified Nom. EA2','Modified Nom. Ex-Ante 2',13);
    PUT_STATEMENT_TYPE('Modified Nom. WD1','Modified Nom. WD1','Modified Nom. Within-day 1 Trading Window',14);
    PUT_STATEMENT_TYPE('Revised Nom. EA2','Revised Nom. EA2','Revised Nom. Ex-Ante 2 Trading Window',15);
    PUT_STATEMENT_TYPE('Revised Nom. WD1','Revised Nom. WD1','Revised Nom. Within-day 1 Trading Window',16);
    COMMIT;
END;
/