CREATE OR REPLACE PACKAGE SEM_CFD_SCHEDULE_FILL IS

  -- Author  : AHUSSAIN
  -- Created : 2/1/2008 11:34:44 AM
  -- $Revision: 1.4 $

	TYPE REF_CURSOR IS REF CURSOR;

	FUNCTION WHAT_VERSION RETURN VARCHAR;
	
	PROCEDURE SCHEDULE_FILL
		(
		p_TRANSACTION_ID IN NUMBER,
		p_BEGIN_DATE IN DATE,
		p_END_DATE IN DATE,
		p_AS_OF_DATE IN DATE,
		p_TIME_ZONE IN VARCHAR,
		p_AMOUNT IN VARCHAR,
		p_PRICE IN VARCHAR,
		p_TEMPLATE IN VARCHAR,
		p_BEGIN_INTERVAL IN NUMBER,
		p_END_INTERVAL IN NUMBER,
		p_INCLUDE_HOLIDAYS IN NUMBER,
		p_SCHEDULE_TYPE IN NUMBER,
		p_STATUS OUT NUMBER,
		p_TO_WORK IN NUMBER := 0,
		p_WORK_ID IN NUMBER := 0,
		p_USE_INTERVAL IN VARCHAR2 := NULL,
		p_AMOUNT2 IN NUMBER := NULL
		);

	PROCEDURE PUT_SCHEDULE_TEMPLATE
		(
		p_TEMPLATE_NAME IN VARCHAR,
		p_START_HOUR_NUM IN NUMBER,
		p_STOP_HOUR_NUM IN NUMBER,
		p_START_INTERVAL_NUM IN NUMBER,
		p_STOP_INTERVAL_NUM IN NUMBER,
		p_MON IN VARCHAR2,
		p_TUE IN VARCHAR2,
		p_WED IN VARCHAR2,
		p_THU IN VARCHAR2,
		p_FRI IN VARCHAR2,
		p_SAT IN VARCHAR2,
		p_SUN IN VARCHAR2,
		p_INTERIOR_PERIOD IN NUMBER,
		p_INCLUDE_HOLIDAYS IN NUMBER,
		p_TEMPLATE_ORDER IN NUMBER,
		p_OLD_TEMPLATE_NAME IN VARCHAR,
		p_STATUS OUT NUMBER
		);

	PROCEDURE GET_SCHEDULE_TEMPLATES
		(
		p_STATUS OUT NUMBER,
		p_CURSOR IN OUT REF_CURSOR
		);

	PROCEDURE DELETE_SCHEDULE_TEMPLATE
		(
		p_TEMPLATE_NAME IN VARCHAR,
		p_STATUS OUT NUMBER
		);

	INSUFFICIENT_PRIVILEGES EXCEPTION;
	PRAGMA EXCEPTION_INIT(INSUFFICIENT_PRIVILEGES, -1031);

END SEM_CFD_SCHEDULE_FILL;
/