CREATE OR REPLACE TYPE BID_OFFER_SET_TYPE AS OBJECT
(
--Revision: $Revision: 1.14 $
	SCHEDULE_DATE DATE,
	SET_NUMBER NUMBER(2),
	QUANTITY NUMBER(9,3),
	PRICE NUMBER(9,3),
	STATUS CHAR(1),
	HAS_CHANGES CHAR(1)
);
/

CREATE OR REPLACE TYPE BID_OFFER_SET_TABLE IS TABLE OF BID_OFFER_SET_TYPE;
/
