CREATE OR REPLACE TYPE CAST_TYPE AS OBJECT
(
--Revision: $Revision: 1.17 $
  SERVICE_ID NUMBER(9),
  CAST_DATE DATE,
  CAST_VAL NUMBER(18,4),
  CAST_ADJ NUMBER(18,4)
);
/

CREATE OR REPLACE TYPE CAST_TABLE IS TABLE OF CAST_TYPE;
/
