CREATE OR REPLACE TYPE EXT_FORECAST_SYNC_TYPE AS OBJECT
(
--Revision: $Revision: 1.15 $
  ACCOUNT_ID NUMBER(9),
  FORECAST_DATE DATE,
  FORECAST_VAL NUMBER(18,4)
);
/

CREATE OR REPLACE TYPE EXT_FORECAST_SYNC_TABLE IS TABLE OF EXT_FORECAST_SYNC_TYPE;
/
