CREATE OR REPLACE TYPE PROVIDER_POSITION_TYPE AS OBJECT
	(
--Revision: $Revision: 1.13 $
	EDC_ID NUMBER(9),
	PSE_ID NUMBER(9),
	ESP_ID NUMBER(9),
	POOL_ID NUMBER(9),
	POSITION_DATE DATE,
	POSITION_QUANTITY NUMBER(12,3),
	POSITION_COST NUMBER(12,2),
	POSITION_PRICE NUMBER(9,3)
	);
/

CREATE OR REPLACE TYPE PROVIDER_POSITION_TABLE IS TABLE OF PROVIDER_POSITION_TYPE; 
/
