CREATE OR REPLACE TYPE SCHEDULE_STATE_TYPE AS OBJECT
(
--Revision: $Revision: 1.13 $
	TRANSACTION_ID NUMBER(9),
	SCHEDULE_TYPE NUMBER(1),
	SCHEDULE_STATE NUMBER(1),	
	SCHEDULE_DATE DATE,
	SCHEDULE_QUANTITY NUMBER(10,3),
	SCHEDULE_PRICE NUMBER(10,3)
);
/

CREATE OR REPLACE TYPE SCHEDULE_STATE_TABLE IS TABLE OF SCHEDULE_STATE_TYPE;
/
