CREATE OR REPLACE PROCEDURE CDI_POST_TO_TRACE(p_TRACE_SOURCE IN VARCHAR2, p_TRACE_TEXT IN VARCHAR2, p_TRUNCATE_TRACE IN BOOLEAN DEFAULT FALSE) AS
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
   IF p_TRUNCATE_TRACE THEN
      EXECUTE IMMEDIATE 'TRUNCATE TABLE CDI_TRACE';
   END IF;
   INSERT INTO CDI_TRACE(TRACE_ID, TRACE_SOURCE, TRACE_TEXT)
   VALUES(CDI_TRACE_SEQ.NEXTVAL, p_TRACE_SOURCE, p_TRACE_TEXT);
   COMMIT;
END CDI_POST_TO_TRACE;
/
