CREATE OR REPLACE PACKAGE CDI_CUSTOMER AS

PROCEDURE RUN_CI_FILTER;

PROCEDURE IMPORT_CI_FILE
   (
   p_IMPORT_FILE      IN CLOB,
   p_IMPORT_FILE_PATH IN VARCHAR2,
   p_STATUS          OUT NUMBER,
   p_MESSAGE         OUT VARCHAR2
   );

PROCEDURE CI_VALIDATE_AND_POST(p_STATUS OUT NUMBER, p_MESSAGE OUT VARCHAR2);

END CDI_CUSTOMER;
/
