CREATE OR REPLACE PACKAGE MEX_ERCOT_EXTRACT IS
-- $Revision: 1.11 $

  -- Author  : CNAVALTA
  -- Created : 5/3/2006 10:47:06 AM
  -- Purpose : download Load Extract data

FUNCTION WHAT_VERSION RETURN VARCHAR2;

PROCEDURE FETCH_LOAD_EXTRACT_PAGE
	(
	p_CRED IN mex_credentials,
	p_BEGIN_DATE IN DATE,
    p_END_DATE IN DATE,
	p_LOG_ONLY IN NUMBER,
    p_WORK_ID OUT NUMBER,
	p_STATUS OUT NUMBER,
	p_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
	);

PROCEDURE PARSE_LOAD_EXTRACT_DATA
	(
    p_RESPONSE_CLOB IN CLOB,
    p_WORK_ID IN NUMBER,
	p_STATUS OUT NUMBER,
	p_MESSAGE OUT VARCHAR2
    );

PROCEDURE PARSE_LOAD_EXTRACT_HEADER
	(
    v_RESPONSE_CLOB IN CLOB,
    p_WORK_ID IN NUMBER,
	p_STATUS OUT NUMBER,
	p_MESSAGE OUT VARCHAR2
    );

PROCEDURE FETCH_ESIID_EXTRACT_PAGE
	(
	p_CRED	IN mex_credentials,
	p_BEGIN_DATE IN DATE,
    p_END_DATE IN DATE,
	p_LOG_ONLY IN NUMBER,
	p_STATUS OUT NUMBER,
	p_MESSAGE OUT VARCHAR2,
	p_LOGGER IN OUT mm_logger_adapter
	);

END MEX_ERCOT_EXTRACT;
/