EXEC ADD_TABLE_PARTITIONS(p_TABLE => 'SERVICE_STATE',           p_TABLESPACE => 'SERVICE_LOAD', p_YEAR => TO_DATE('1/1/2021','MM/DD/YYYY'), p_IS_DST => FALSE); 
EXEC ADD_TABLE_PARTITIONS(p_TABLE => 'SERVICE_STATE',           p_TABLESPACE => 'SERVICE_LOAD', p_YEAR => TO_DATE('1/1/2022','MM/DD/YYYY'), p_IS_DST => FALSE); 
EXEC ADD_TABLE_PARTITIONS(p_TABLE => 'SERVICE_LOAD',            p_TABLESPACE => 'SERVICE_LOAD', p_YEAR => TO_DATE('1/1/2021','MM/DD/YYYY')); 
EXEC ADD_TABLE_PARTITIONS(p_TABLE => 'SERVICE_LOAD',            p_TABLESPACE => 'SERVICE_LOAD', p_YEAR => TO_DATE('1/1/2022','MM/DD/YYYY')); 
EXEC ADD_TABLE_PARTITIONS(p_TABLE => 'SERVICE_OBLIGATION_LOAD', p_TABLESPACE => 'SERVICE_LOAD', p_YEAR => TO_DATE('1/1/2021','MM/DD/YYYY')); 
EXEC ADD_TABLE_PARTITIONS(p_TABLE => 'SERVICE_OBLIGATION_LOAD', p_TABLESPACE => 'SERVICE_LOAD', p_YEAR => TO_DATE('1/1/2022','MM/DD/YYYY')); 
