BEGIN CDI_DROP_OBJECT('CDI_ACCNT_USG_FACTOR_SYNC_LIST','TYPE'); END;
/
BEGIN CDI_DROP_OBJECT('CDI_ACCNT_USG_FACTOR_SYNC_TYPE','TYPE'); END;
/
CREATE OR REPLACE TYPE CDI_ACCNT_USG_FACTOR_SYNC_TYPE AS OBJECT
(
  ACCOUNT_IDENTIFIER VARCHAR2(64),
  BEGIN_DATE         DATE,
  END_DATE           DATE,
  FACTOR_VAL         NUMBER(20,6)
);
/
CREATE OR REPLACE TYPE CDI_ACCNT_USG_FACTOR_SYNC_LIST IS TABLE OF CDI_ACCNT_USG_FACTOR_SYNC_TYPE;
/
