CREATE OR REPLACE PACKAGE WS_TEST IS
-- $Revision: 1.3 $

FUNCTION WHAT_VERSION RETURN VARCHAR2;

PROCEDURE GET_TEST_DATA
	(
	p_NUMBER_IN          IN NUMBER,
	p_STRING_IN          IN VARCHAR2,
	p_DATE_IN            IN DATE,
	p_CLOB_IN            IN CLOB,
	p_STRING_ARRAY_IN    IN STRING_COLLECTION,
	p_NUMBER_ARRAY_IN    IN NUMBER_COLLECTION,
	p_NUMBER_2D_ARRAY_IN IN NUMBER_COLLECTION_COLLECTION,
	p_DATE_ARRAY_IN      IN DATE_COLLECTION,
	p_NUMBER_OUT         OUT NUMBER,
	P_NUMBER_OUT_ID	     OUT NUMBER,
	p_STRING_OUT         OUT VARCHAR2,
	p_DATE_OUT           OUT DATE,
	p_CLOB_OUT           OUT CLOB,
	p_STRING_ARRAY_OUT   OUT STRING_COLLECTION,
	p_NUMBER_ARRAY_OUT   OUT NUMBER_COLLECTION,
	p_DATE_ARRAY_OUT     OUT DATE_COLLECTION,
	p_MESSAGE            IN OUT VARCHAR2,
	p_CURSOR             IN OUT SYS_REFCURSOR
	);

END WS_TEST;
/
CREATE OR REPLACE PACKAGE BODY WS_TEST IS

FUNCTION WHAT_VERSION RETURN VARCHAR2 IS
BEGIN
    RETURN '$Revision: 1.3 $';
END WHAT_VERSION;
---------------------------------------------------------------------------------------------------
PROCEDURE GET_TEST_DATA
	(
	p_NUMBER_IN          IN NUMBER,
	p_STRING_IN          IN VARCHAR2,
	p_DATE_IN            IN DATE,
	p_CLOB_IN            IN CLOB,
	p_STRING_ARRAY_IN    IN STRING_COLLECTION,
	p_NUMBER_ARRAY_IN    IN NUMBER_COLLECTION,
	p_NUMBER_2D_ARRAY_IN IN NUMBER_COLLECTION_COLLECTION,
	p_DATE_ARRAY_IN      IN DATE_COLLECTION,
	p_NUMBER_OUT         OUT NUMBER,
	P_NUMBER_OUT_ID	     OUT NUMBER,
	p_STRING_OUT         OUT VARCHAR2,
	p_DATE_OUT           OUT DATE,
	p_CLOB_OUT           OUT CLOB,
	p_STRING_ARRAY_OUT   OUT STRING_COLLECTION,
	p_NUMBER_ARRAY_OUT   OUT NUMBER_COLLECTION,
	p_DATE_ARRAY_OUT     OUT DATE_COLLECTION,
	p_MESSAGE            IN OUT VARCHAR2,
	p_CURSOR             IN OUT SYS_REFCURSOR
	) AS
	I                     NUMBER(9);
	J                     NUMBER(9);
	v_NUMS                NUMBER_COLLECTION;
	v_FIRST_TIME_OUTER    BOOLEAN;
	v_FIRST_TIME_INNER 	  BOOLEAN;
	v_NUMBER_2D_ARRAY_MSG VARCHAR2(32767);
BEGIN

	LOGS.LOG_INFO('Entering the WebService WS_TEST.GET_TEST_DATA');

	p_NUMBER_OUT := 123456.45678;
	P_NUMBER_OUT_ID := 123;
	p_STRING_OUT := 'FOOBAR';
	p_DATE_OUT := DATE '1975-08-19';

	v_NUMBER_2D_ARRAY_MSG := 'p_NUMBER_2D_ARRAY_IN = ' || TEXT_UTIL.TO_CHAR_2D_NUMBER_LIST(p_NUMBER_2D_ARRAY_IN);

	p_MESSAGE := 'p_MESSAGE = ' || p_MESSAGE || UTL_TCP.CRLF
		|| 'p_NUMBER_IN = ' || p_NUMBER_IN || UTL_TCP.CRLF
		|| 'p_STRING_IN = ' || p_STRING_IN || UTL_TCP.CRLF
		|| 'p_DATE_IN = ' || TO_CHAR(p_DATE_IN, 'YYYY-MM-DD HH24:MI') || UTL_TCP.CRLF
		|| 'p_CLOB_IN = ' || p_CLOB_IN || UTL_TCP.CRLF
		|| v_NUMBER_2D_ARRAY_MSG;

	p_STRING_ARRAY_OUT := STRING_COLLECTION();
	p_STRING_ARRAY_OUT.EXTEND();
	p_STRING_ARRAY_OUT(p_STRING_ARRAY_OUT.LAST()) := 'FOO';
	p_STRING_ARRAY_OUT.EXTEND();
	p_STRING_ARRAY_OUT(p_STRING_ARRAY_OUT.LAST()) := 'BAR';

	p_NUMBER_ARRAY_OUT := NUMBER_COLLECTION();
	p_NUMBER_ARRAY_OUT.EXTEND();
	p_NUMBER_ARRAY_OUT(p_NUMBER_ARRAY_OUT.LAST()) := 123;
	p_NUMBER_ARRAY_OUT.EXTEND();
	p_NUMBER_ARRAY_OUT(p_NUMBER_ARRAY_OUT.LAST()) := 456;

	p_DATE_ARRAY_OUT := DATE_COLLECTION();
	p_DATE_ARRAY_OUT.EXTEND();
	p_DATE_ARRAY_OUT(p_DATE_ARRAY_OUT.LAST()) := DATE '2009-01-01';
	p_DATE_ARRAY_OUT.EXTEND();
	p_DATE_ARRAY_OUT(p_DATE_ARRAY_OUT.LAST()) := p_DATE_IN;

	OPEN p_CURSOR FOR
		SELECT * FROM APPLICATION_USER;

	DBMS_LOB.CREATETEMPORARY(p_CLOB_OUT,false);
	DBMS_LOB.WRITEAPPEND(p_CLOB_OUT,LENGTH('This is the out clob message.'), 'This is the out clob message.');

	LOGS.LOG_INFO('Leaving the WebService WS_TEST.GET_TEST_DATA. Message = ' || p_MESSAGE);

END GET_TEST_DATA;

END WS_TEST;
/
