SET DEFINE OFF;
SET SERVEROUTPUT ON;
BEGIN
	SECURITY_CONTROLS.SET_CURRENT_ROLES(ID_TABLE(ID_TYPE(SECURITY_CONTROLS.g_SUPER_USER_ROLE_ID)));
END;
/

DELETE CLOB_STAGING WHERE CLOB_IDENT ='ConfigImportClob';

DECLARE
	v_CLOB_IDENT CONSTANT VARCHAR2(32) := 'ConfigImportClob';
	v_CLOB CLOB;
BEGIN
	v_CLOB := 'H4sIAAAAAAAAAO1ZXY/iNhR976+wUmnVPsyEj6HbmQUkFpgt3Q1EwE61fUEmuSTuBJs6zgISP743eAiBhJm0y8N2hASR7eSee22fY8c39dE6VDAfTP8CR7UFnzEvklQxwclqHvCwYfhKLe5Mc7lcXnNYAgfprWkYCufaEXNzzjxfrU0nbWmQ0JFsodoSqIIO/htGpVS6vcJfuUZKt3eV6l31xiAstKVwI0eNts83jJLRrFuUcR1O2PyBkLoux0Ws2FT5uogVTufQ1PHXzW1ld8dBn56Q6+Ru0rB7Ig2UQDk+uFHAuHcIlwa0MN4AsoAZyCzo9UD5IMvH2NlwyQODZa4L86D/qdpBeYtv/25NRt3hQ6/dndjjydAepx3vXQ5hIaQ69lZ3WbgI6LofW7RclyAcGYH8yhwgtmBchXUz/Yy2EtIF2SzVTV3QjSz8jbku8Lg9KetbLaUkm0YKCHMbxlXVIHGIDWPkUwkuiflIrsjgK0jJXCC9kGhzI8ZKjPPBKi+AdTB6EsdeAOymVN6hfQBFkLUOTqoEUjaaljWJx7prfRxfxwW7P+h0R3rAX0JNYsRuIUPIPQsUSGJTDkGhsH7ZAQxhJiH0SWsWA4wgQM3EUswDSSvqNF0mH3CYTulK38uoKm/+n2XAmTlwZhZk4Kp7HthRmgca4YAKn8eTF+iQA1/bwbcpJ22fcg/IUCwx7IirgiH+ekSqEV4C7ClVFHGCaM7JJzrNJ1gWrpz0GIeKThGotWUW6YgorrUD5jyegDok2o5qrU5nMnpoT+xBrz8+vdLqUHOXQc2u8hHNXiDa2al2drJlAJOh77pMkfF6gYaP5Ke2D87jVKx+LoKRxNQXivSj4MS0Z+ze7uws3PCBFI24miIfjhz5w8fLv3BbKe1XNOqSAQ/WRS1vdpb3bAVuQavqfoxXThDhJN1LMSedaIG8RuYVhUmcI2naYj4V5L1YkXjeYs2c0Id5tBLn66Xz2bK+fINOjpfjtE7Kr0InF47/3zkeb5L9ltX9TzRPv4f2hat345zX05QmKq9+77ho4jVoYvzFPpMm4reH5zVRvWjioonvXBPb01Sv882SsLeaiIGeU8TNRRGn5jjhl5BziifTHy86+g51dFTLS/zEgppkt5njBOFTaion51N8p3n16aHaPj30lMnTZ3YHz+y7+cs7tGdgkrC02ScWosTeBOpdKwjeeOrdplYqbVqeJ8HD6di8j8JNj6O/GXVg86fgUMRJosYxrBRGZmpnHZjRKDj0VwQuSTuhjVgSCzHYlU5EFhu8ci3NdxrnzQsa3qYMh/B3xGRR0/TSoBOogpPTQaf1tC/XzYNvFnWEAgncAfepzcRGZBYKlwlOA71mblvNk59fmv8AEU6NCJoZAAA=';
	PARSE_UTIL.APPEND_TO_STAGING_CLOB(v_CLOB_IDENT, v_CLOB);
END;
/

DECLARE
	v_CLOB_IDENT CONSTANT VARCHAR2(32) := 'ConfigImportClob';
	v_COMPRESSED_ENCODED_CLOB CLOB;
	v_BLOB BLOB;
	v_CLOB CLOB;
	v_DEST_OFFSET INTEGER := 1;
	v_SRC_OFFSET INTEGER := 1;
	v_LANG_CONTEXT NUMBER := DBMS_LOB.DEFAULT_LANG_CTX;
	v_WARNING INTEGER;
	v_MESSAGE VARCHAR2(4000);
	v_PROCESS_ID VARCHAR2(32);
	v_PROCESS_STATUS NUMBER(9);
BEGIN
	SELECT CLOB_VAL INTO v_COMPRESSED_ENCODED_CLOB
	FROM CLOB_STAGING
	WHERE CLOB_IDENT = v_CLOB_IDENT;

	v_BLOB := UTL_COMPRESS.LZ_UNCOMPRESS(CD.BASE64DECODE(v_COMPRESSED_ENCODED_CLOB));

	DBMS_LOB.CREATETEMPORARY(v_CLOB, TRUE);
	DBMS_LOB.OPEN(v_CLOB, DBMS_LOB.LOB_READWRITE);

	DBMS_LOB.CONVERTTOCLOB(v_CLOB,
		v_BLOB,
		DBMS_LOB.GETLENGTH(v_BLOB),
		v_DEST_OFFSET,
		v_SRC_OFFSET, 
		1, 
		v_LANG_CONTEXT, 
		v_WARNING);

	IF v_WARNING <> DBMS_LOB.NO_WARNING THEN
		DBMS_OUTPUT.PUT_LINE('Warning converting BLOB of XML to CLOB: ' ||
			CASE WHEN v_WARNING = DBMS_LOB.WARN_INCONVERTIBLE_CHAR THEN
					'source contained character that could not be properly converted'
			ELSE
					'unknown warning – ' || v_WARNING
			END);
	END IF;

	DBMS_LOB.CLOSE(v_CLOB);

	SO_IMPORT_EXPORT.IMPORT_SYSTEM_OBJECT_XML_CLOB(v_CLOB, 'C:\CVSRoot\branch_v5_0_1_20090723\RetailOffice\Database\MINT\PJM\Reports\AddPJMServicePointsReport.xml', SO_IMPORT_EXPORT.c_IMODE_OVERWRITE_PRSV,v_PROCESS_STATUS ,v_PROCESS_ID , v_MESSAGE);
	DBMS_OUTPUT.PUT_LINE(v_MESSAGE);
END;
/
COMMIT;
SET DEFINE ON;
SET SERVEROUTPUT OFF;