	--SET SERVEROUTPUT ON SIZE 500000
DECLARE
	
    PROCEDURE PUT_CONDITIONAL_FORMAT_ITEM
    (
    p_CONDITIONAL_FORMAT_NAME IN VARCHAR2,
    p_ITEM_NUMBER IN NUMBER,
	p_COLOR_WHEN_FORMULA IN VARCHAR,
	p_FOREGROUND_COLOR IN NUMBER,
	p_BACKGROUND_COLOR IN NUMBER,
	p_IS_BOLD IN NUMBER := 0,
	p_IS_ITALIC IN NUMBER := 0,
	p_IS_STRIKE_THROUGH IN NUMBER := 0,
	p_IS_UNDERLINE IN NUMBER := 0
    ) AS
        
    v_FORMAT_ID NUMBER(9) := 0;
    v_STATUS NUMBER(9) := 0;
        
	BEGIN
		
        -- Check for existing CONDITIONAL_FORMAT    
        BEGIN
            SELECT CF.CONDITIONAL_FORMAT_ID
            INTO v_FORMAT_ID
            FROM CONDITIONAL_FORMAT CF
            WHERE UPPER(CF.CONDITIONAL_FORMAT_NAME) = UPPER(LTRIM(RTRIM(p_CONDITIONAL_FORMAT_NAME)));
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                v_FORMAT_ID := 0;
        END;
        
        -- Insert/Update CONDITIONAL_FORMAT 
        BEGIN        
            IO.PUT_CONDITIONAL_FORMAT(v_FORMAT_ID, p_CONDITIONAL_FORMAT_NAME, '?', '?', v_FORMAT_ID, '?');            
            DBMS_OUTPUT.PUT_LINE('UPDATED FORMAT SUCCESSFULLY: ' || p_CONDITIONAL_FORMAT_NAME || '.  FORMAT_ID=' || v_FORMAT_ID);            
        EXCEPTION
		    WHEN OTHERS THEN
			    DBMS_OUTPUT.PUT_LINE('IO.PUT_CONDITIONAL_FORMAT:DID NOT SUCCESSFULLY CREATE ' || p_CONDITIONAL_FORMAT_NAME || '.  STATUS=' || SQLCODE);        
        END;                   
        
        -- Insert/Update CONDITIONAL_FORMAT_ITEM
        IF v_FORMAT_ID > 0 THEN 
            BEGIN
                EM.PUT_CONDITIONAL_FORMAT_ITEM(v_FORMAT_ID, p_ITEM_NUMBER, p_COLOR_WHEN_FORMULA, p_FOREGROUND_COLOR, p_BACKGROUND_COLOR, p_IS_BOLD, p_IS_ITALIC, p_IS_STRIKE_THROUGH, p_IS_UNDERLINE);
                DBMS_OUTPUT.PUT_LINE('UPDATED FORMAT ITEM SUCCESSFULLY: ' || p_CONDITIONAL_FORMAT_NAME || '.  FORMAT_ID=' || v_FORMAT_ID);
            EXCEPTION
		        WHEN OTHERS THEN
			        DBMS_OUTPUT.PUT_LINE('EM.PUT_CONDITIONAL_FORMAT_ITEM:DID NOT SUCCESSFULLY CREATE FORMAT ITEM: ' || p_CONDITIONAL_FORMAT_NAME);        
            END;
        ELSE        
            DBMS_OUTPUT.PUT_LINE('DID NOT CALL EM.PUT_CONDITIONAL_FORMAT_ITEM(). FORMAT ID <= 0.');        
        END IF;
    
    END;

BEGIN -- MAIN

 
	PUT_CONDITIONAL_FORMAT_ITEM('BidOfferStatus', 1, 'X="Pending"', -16777216, -52);
	PUT_CONDITIONAL_FORMAT_ITEM('BidOfferStatus', 2, 'X="Submitted"', -16777216, -3342388);
	PUT_CONDITIONAL_FORMAT_ITEM('BidOfferStatus', 3, 'X="Accepted"', -16777216, -3342337);
	PUT_CONDITIONAL_FORMAT_ITEM('BidOfferStatus', 4, 'X="Submitted DA"', -16777216, -3355393);
	PUT_CONDITIONAL_FORMAT_ITEM('BidOfferStatus', 5, 'X="Rejected"', -16777216, -13108);
	PUT_CONDITIONAL_FORMAT_ITEM('BidOfferStatus', 6, 'X="Changed"', -16777216, -13159);
	PUT_CONDITIONAL_FORMAT_ITEM('BidOfferStatus', 7, 'X="Not Submitted"', -16777216, -26215);
	PUT_CONDITIONAL_FORMAT_ITEM('BidOfferStatus', 8, 'X="various"', -16777216, -3355393);
	PUT_CONDITIONAL_FORMAT_ITEM('BidOfferStatus', 9, 'X="Tested"', -16777216, -52);
	PUT_CONDITIONAL_FORMAT_ITEM('BidOfferStatus', 10, 'X="Failed"', -1, -16777216, 1);
	
   COMMIT;
END;
/
